import { useEffect, useState } from "react";
import { documentsApi, DocumentSummary, DocumentVersion } from "../../services/documentsApi";
import { Button } from "../ui/Button";
export function DocumentClassificationBadge({ value }: { value: string }) { const cls = value === "Public" ? "text-bg-success" : value === "SealedBid" ? "text-bg-danger" : value === "Confidential" ? "text-bg-warning" : "text-bg-secondary"; return <span className={`badge ${cls}`}>{value}</span>; }
export function DocumentPublicStatusBadge({ isPublic }: { isPublic: boolean }) { return <span className={`badge ${isPublic ? "text-bg-success" : "text-bg-light text-dark"}`}>{isPublic ? "Public" : "Private"}</span>; }
export function DocumentList({ documents }: { documents: DocumentSummary[] }) { return <div className="table-responsive"><table className="table table-hover align-middle"><thead><tr><th>Document number</th><th>Title</th><th>Entity</th><th>Document type</th><th>Classification</th><th>Status</th><th>Version</th><th>Uploaded date</th><th>Public</th><th>Actions</th></tr></thead><tbody>{documents.map(d=><tr key={d.id}><td>{d.documentNumber}</td><td>{d.title}</td><td>{d.entityType}</td><td>{d.documentType}</td><td><DocumentClassificationBadge value={d.classification}/></td><td>{d.status}</td><td>v{d.currentVersion}</td><td>{new Date(d.uploadedAt).toLocaleString()}</td><td><DocumentPublicStatusBadge isPublic={d.isPublic}/></td><td><a className="btn btn-sm btn-outline-primary" href={`/app/documents/${d.id}`}>Open</a></td></tr>)}</tbody></table></div>; }
export function DocumentVersionHistory({ versions }: { versions: DocumentVersion[] }) { return <ul className="list-group">{versions.map(v=><li className="list-group-item d-flex justify-content-between" key={v.id}><span>v{v.versionNumber} {v.originalFileName} {v.isCurrent && <span className="badge text-bg-primary ms-2">current</span>}</span><code>{v.contentHash.slice(0,16)}</code></li>)}</ul>; }
export function DocumentUploadButton() { return <Button variant="primary">Upload document</Button>; }
export function DocumentAccessLogPanel({ documentId }: { documentId: string }) { const [rows,setRows]=useState<any[]>([]); useEffect(()=>{documentsApi.accessLog(documentId).then(r=>setRows(r.data as any[]));},[documentId]); return <div className="card"><div className="card-header">Access log</div><div className="card-body"><ul className="list-group">{rows.map(r=><li className="list-group-item" key={r.id}>{r.action} by {r.userEmail} - {r.accessAllowed ? "allowed" : r.deniedReason}</li>)}</ul></div></div>; }
export function DocumentRequirementChecklist({ entityType, entityId, requirementSetId }: { entityType:string; entityId:string; requirementSetId:string }) { const [items,setItems]=useState<any[]>([]); useEffect(()=>{documentsApi.validate(entityType,entityId,requirementSetId).then(r=>setItems(r.data.items));},[entityType,entityId,requirementSetId]); return <div className="card"><div className="card-header">Document requirement checklist</div><div className="card-body"><ul className="list-group">{items.map(i=><li className="list-group-item d-flex justify-content-between" key={i.documentType}>{i.documentType}<span>{i.currentFiles}/{i.minimumFiles} {i.passed ? "✓" : "Required"}</span></li>)}</ul></div></div>; }
export function DocumentPanel({ entityType, entityId }: { entityType:string; entityId:string; allowedDocumentTypes?: string[]; canUpload?: boolean; canPublish?: boolean; canArchive?: boolean; classificationDefault?: string }) { const [docs,setDocs]=useState<DocumentSummary[]>([]); useEffect(()=>{documentsApi.list(`?entityType=${entityType}&entityId=${entityId}`).then(r=>setDocs(r.data));},[entityType,entityId]); return <div className="card"><div className="card-header d-flex justify-content-between"><strong>Documents</strong><DocumentUploadButton/></div><div className="card-body"><DocumentList documents={docs}/></div></div>; }
