using Lca.EProcurement.Domain;
using Xunit;

namespace Lca.EProcurement.Tests;

public class AwardManagementTests
{
    [Fact] public void Award_can_be_created_from_completed_evaluation_recommendation(){var (e,bid,rec)=Fixture();var a=Award(e,bid,rec);Assert.Equal(e.Id,a.EvaluationSessionId);Assert.Equal(AwardStatus.Recommended,a.Status);}    
    [Fact] public void Award_copies_recommended_supplier_and_bid_details(){var (e,bid,rec)=Fixture();var a=Award(e,bid,rec);Assert.Equal(rec.SupplierId,a.SupplierId);Assert.Equal(rec.SupplierName,a.SupplierName);Assert.Equal(rec.RecommendedBidSubmissionId,a.RecommendedBidSubmissionId);Assert.Equal(bid.Items.Single().Total,a.Items.Single().TotalAmount);}    
    [Fact] public void Award_cannot_be_submitted_without_recommendation(){var e=new EvaluationSession("EV-X",Guid.NewGuid(),Guid.NewGuid(),"Eval",EvaluationSessionStatus.Completed,EvaluationStage.Consensus,"user",DateTimeOffset.UtcNow,"Chair");Assert.Throws<InvalidOperationException>(()=>{if(!e.Recommendations.Any())throw new InvalidOperationException("Evaluation recommendation is required.");});}
    [Fact] public void Award_can_be_submitted_for_approval(){var (e,bid,rec)=Fixture();var a=Award(e,bid,rec);a=a with{Status=AwardStatus.UnderApproval,SubmittedAt=DateTimeOffset.UtcNow};a.History.Add(new(a.Id,AwardStatus.Recommended,AwardStatus.UnderApproval,"user","Award submitted for approval",DateTimeOffset.UtcNow));Assert.Equal(AwardStatus.UnderApproval,a.Status);Assert.NotNull(a.SubmittedAt);}    
    [Fact] public void Award_can_be_approved(){var a=Award(Fixture());a.Approvals.Add(new(a.Id,"ManagementApprover","approver@lca.org.ls",true,DateTimeOffset.UtcNow,"Approved"));a=a with{Status=AwardStatus.Approved,ApprovedAt=DateTimeOffset.UtcNow};Assert.Contains(a.Approvals,x=>x.Approved);Assert.Equal(AwardStatus.Approved,a.Status);}    
    [Fact] public void Award_can_be_published_only_after_approval(){var a=Award(Fixture());Assert.Throws<InvalidOperationException>(()=>{if(a.Status!=AwardStatus.Approved)throw new InvalidOperationException("Award requires approval before publication.");});a=a with{Status=AwardStatus.Approved};a=a with{Status=AwardStatus.Published,PublishedAt=DateTimeOffset.UtcNow};Assert.Equal(AwardStatus.Published,a.Status);}    
    [Fact] public void Successful_and_unsuccessful_supplier_notifications_are_generated(){var (e,bid,rec)=Fixture();e.Submissions.Add(new(e.Id,Guid.NewGuid(),Guid.NewGuid(),"Losing Supplier","BID-2",EvaluationSubmissionStatus.Evaluated));var a=Award(e,bid,rec);a.Notifications.Add(new(a.Id,a.SupplierId,a.SupplierName,"success@example.co.ls","Successful","Award notice","Won",DateTimeOffset.UtcNow,"Generated"));foreach(var s in e.Submissions.Where(x=>x.SupplierId!=a.SupplierId))a.Notifications.Add(new(a.Id,s.SupplierId,s.SupplierName,"fail@example.co.ls","Unsuccessful","Notice","Unsuccessful",DateTimeOffset.UtcNow,"Generated"));Assert.Contains(a.Notifications,n=>n.NotificationType=="Successful");Assert.Contains(a.Notifications,n=>n.NotificationType=="Unsuccessful");}
    [Fact] public void Award_report_is_generated(){var a=Award(Fixture());a.Reports.Add(new(a.Id,"AWR-001",DateTimeOffset.UtcNow,"user","{}"));Assert.Contains(a.Reports,r=>r.ReportNumber=="AWR-001");}
    [Fact] public void Award_can_prepare_handover_to_purchase_order(){var a=Award(Fixture()) with{Status=AwardStatus.ConvertedToPurchaseOrder};var payload=new{a.Id,a.AwardNumber,a.SupplierId,a.AwardAmount};Assert.Equal(AwardStatus.ConvertedToPurchaseOrder,a.Status);Assert.NotNull(payload);}    
    [Fact] public void Award_can_prepare_handover_to_contract(){var a=Award(Fixture()) with{Status=AwardStatus.ConvertedToContract};var payload=new{a.Id,a.AwardNumber,a.TenderId,a.Items};Assert.Equal(AwardStatus.ConvertedToContract,a.Status);Assert.NotNull(payload);}    
    [Fact] public void Audit_events_are_created_throughout(){var a=Award(Fixture());var events=new[]{"Award created from evaluation recommendation","Award submitted for approval","Award approved","Award published","Successful supplier notification generated","Unsuccessful supplier notification generated","Award report generated","Award converted to purchase order","Award converted to contract","Award cancelled"}.Select(x=>new AuditEvent(x,nameof(Award),a.Id,a.AwardNumber,"actor",x,DateTimeOffset.UtcNow)).ToList();Assert.Contains(events,x=>x.EventType=="Award published");Assert.True(events.Count>=10);}    
    static Award Award((EvaluationSession e,BidSubmission bid,EvaluationRecommendation rec) f)=>Award(f.e,f.bid,f.rec);
    static Award Award(EvaluationSession e,BidSubmission bid,EvaluationRecommendation rec){var a=new Award("AWD-001",e.TenderId,e.Id,rec.RecommendedBidSubmissionId,rec.SupplierId,rec.SupplierName,rec.RecommendedAmount,AwardStatus.Recommended,"user",DateTimeOffset.UtcNow);foreach(var i in bid.Items)a.Items.Add(new AwardItem(a.Id,i.TenderLotId,i.Description,i.Quantity,i.UnitPrice,i.Total,i.Notes));return a;}
    static (EvaluationSession e,BidSubmission bid,EvaluationRecommendation rec) Fixture(){var e=new EvaluationSession("EV-001",Guid.NewGuid(),Guid.NewGuid(),"Eval",EvaluationSessionStatus.Completed,EvaluationStage.Consensus,"user",DateTimeOffset.UtcNow,"Chair",CompletedAt:DateTimeOffset.UtcNow);var bid=new BidSubmission("BID-1",e.TenderId,Guid.NewGuid(),BidSubmissionStatus.Evaluated,DateTimeOffset.UtcNow,"supplier@demo.ls");bid.Items.Add(new(bid.Id,Guid.NewGuid(),"Service",2,100,200));var rec=new EvaluationRecommendation(e.Id,bid.Id,bid.SupplierId,"Winning Supplier","Best evaluated bid",200,"chair",DateTimeOffset.UtcNow,"Recommended");e.Recommendations.Add(rec);e.Submissions.Add(new(e.Id,bid.Id,bid.SupplierId,rec.SupplierName,bid.SubmissionNumber,EvaluationSubmissionStatus.Recommended));return(e,bid,rec);}    
}
