using Lca.EProcurement.Domain;

namespace Lca.EProcurement.Tests;

public class ContractManagementTests
{
    [Fact] public void Award_creates_contract_and_copies_supplier_items_and_value(){var (award,_,contract)=Fixture();Assert.Equal(award.Id,contract.AwardId);Assert.Equal(award.SupplierId,contract.SupplierId);Assert.Equal(award.SupplierName,contract.SupplierName);Assert.Equal(award.AwardAmount,contract.OriginalValue);Assert.Equal(award.Items.Count,contract.Lines.Count);}
    [Fact] public void Purchase_order_creates_contract_and_copies_lines(){var (_,po,_)=Fixture();var contract=new Contract("CTR-PO",po.AwardId,po.Id,po.SupplierId,po.SupplierName,"PO Contract","From PO",ContractType.SupplyContract,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow.AddMonths(6),po.TotalAmount,po.TotalAmount,ContractStatus.Draft,"user",DateTimeOffset.UtcNow);foreach(var l in po.Lines)contract.Lines.Add(new(contract.Id,l.ItemNumber,l.Description,l.Quantity,l.UnitPrice,l.Total));Assert.Equal(po.Id,contract.PurchaseOrderId);Assert.Equal(po.Lines.Count,contract.Lines.Count);}
    [Fact] public void Milestones_are_tracked(){var (_,_,contract)=Fixture();contract.Milestones.Add(new(contract.Id,"Completion","Complete work",DateTimeOffset.UtcNow.AddDays(30),null,"Pending"));contract.Milestones[0]=contract.Milestones[0] with{CompletedDate=DateTimeOffset.UtcNow,Status="Completed"};Assert.All(contract.Milestones,m=>Assert.Equal("Completed",m.Status));}
    [Fact] public void Variations_update_value(){var (_,_,contract)=Fixture();var variation=new ContractVariation(contract.Id,"VAR-001","Scope change","Approved scope",500,"approver",DateTimeOffset.UtcNow);contract.Variations.Add(variation);contract=contract with{CurrentValue=contract.CurrentValue+variation.AmountAdjustment};Assert.Equal(1500,contract.CurrentValue);}
    [Fact] public void Renewals_extend_contract(){var (_,_,contract)=Fixture();var old=contract.EndDate;var renewal=new ContractRenewal(contract.Id,"REN-001",old,old.AddMonths(12),"Extend service","approver",DateTimeOffset.UtcNow);contract.Renewals.Add(renewal);contract=contract with{EndDate=renewal.NewEndDate};Assert.True(contract.EndDate>old);}
    [Fact] public void Performance_reviews_update_supplier_performance(){var (_,_,contract)=Fixture();var review=new ContractPerformanceReview(contract.Id,DateTimeOffset.UtcNow,"reviewer",85,88,82,"Good");var rating=new SupplierPerformanceRating(contract.SupplierId,review.SupplierScore,$"Contract {contract.ContractNumber}",DateTimeOffset.UtcNow);Assert.Equal(85,rating.Score);Assert.Equal(contract.Id,review.ContractId);}
    [Fact] public void Audit_events_are_created(){var (_,_,contract)=Fixture();var events=new[]{"Contract Created","Activated","Milestone Completed","Variation Approved","Renewal Approved","Performance Review Recorded","Completed","Terminated"}.Select(x=>new AuditEvent(x,nameof(Contract),contract.Id,contract.ContractNumber,"actor",x,DateTimeOffset.UtcNow)).ToList();Assert.Contains(events,x=>x.EventType=="Variation Approved");Assert.True(events.Count>=8);}
    static (Award award,PurchaseOrder po,Contract contract) Fixture(){var award=new Award("AWD-C",Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),"Winning Supplier",1000,AwardStatus.Approved,"user",DateTimeOffset.UtcNow,ApprovedAt:DateTimeOffset.UtcNow);award.Items.Add(new(award.Id,Guid.NewGuid(),"Service",2,500,1000));var po=new PurchaseOrder("PO-C",award.Id,award.SupplierId,award.SupplierName,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow.AddDays(30),"LSL",award.AwardAmount,PurchaseOrderStatus.Issued,"user",DateTimeOffset.UtcNow,IssuedAt:DateTimeOffset.UtcNow);po.Lines.Add(new(po.Id,1,"Service",2,500,1000,0,2));var contract=new Contract("CTR-C",award.Id,null,award.SupplierId,award.SupplierName,"Contract","Generated",ContractType.ServiceContract,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow.AddMonths(12),award.AwardAmount,award.AwardAmount,ContractStatus.Draft,"user",DateTimeOffset.UtcNow);foreach(var i in award.Items)contract.Lines.Add(new(contract.Id,1,i.Description,i.Quantity,i.UnitPrice,i.TotalAmount));return(award,po,contract);}    
}
