using Lca.EProcurement.Domain;

namespace Lca.EProcurement.Tests;

public class EvaluationManagementTests
{
    [Fact] public void Evaluation_session_can_be_created_from_completed_bid_opening(){var opening=Opening(BidOpeningSessionStatus.Completed);var evaluation=new EvaluationSession("EV-001",opening.TenderId,opening.Id,"Evaluation",EvaluationSessionStatus.Draft,EvaluationStage.Administrative,"user",DateTimeOffset.UtcNow,"Chair");Assert.Equal(opening.Id,evaluation.BidOpeningSessionId);Assert.Equal(EvaluationSessionStatus.Draft,evaluation.Status);}    
    [Fact] public void Opened_bid_submissions_are_attached_to_evaluation_session(){var opening=Opening(BidOpeningSessionStatus.Completed);var bid=OpeningSubmission(opening.Id,BidOpeningSubmissionStatus.Opened);var evaluation=Evaluation(opening,[bid]);Assert.Contains(evaluation.Submissions,x=>x.BidSubmissionId==bid.BidSubmissionId);}    
    [Fact] public void Evaluation_cannot_start_without_committee_members(){var e=new EvaluationSession("EV-002",Guid.NewGuid(),Guid.NewGuid(),"Eval",EvaluationSessionStatus.Scheduled,EvaluationStage.Administrative,"user",DateTimeOffset.UtcNow,"Chair");Assert.Throws<InvalidOperationException>(()=>{if(!e.CommitteeMembers.Any())throw new InvalidOperationException("Evaluation cannot start without committee members.");});}
    [Fact] public void Evaluation_cannot_start_without_declarations_accepted(){var e=Evaluation(Opening(BidOpeningSessionStatus.Completed),[]);e.CommitteeMembers.Add(new EvaluationCommitteeMember(e.Id,"Member","member@lca.org.ls","Evaluator"));Assert.Throws<InvalidOperationException>(()=>{if(e.CommitteeMembers.Any(x=>!x.HasAcceptedDeclaration))throw new InvalidOperationException("All evaluators must accept conflict of interest declarations.");});}
    [Fact] public void Evaluator_can_score_criteria(){var e=Evaluation(Opening(BidOpeningSessionStatus.Completed),[OpeningSubmission(Guid.NewGuid(),BidOpeningSubmissionStatus.Opened)]);var sub=e.Submissions.Single();var criterion=new EvaluationCriterion("TECH","Technical","",EvaluationStage.Technical,70,100,60,1);var score=new EvaluationScore(e.Id,sub.Id,criterion.Id,"evaluator@lca.org.ls",EvaluationStage.Technical,80,"Good",DateTimeOffset.UtcNow);e.Scores.Add(score);Assert.Contains(e.Scores,x=>x.Score==80&&x.EvaluatorEmail=="evaluator@lca.org.ls");}
    [Fact] public void Weighted_totals_are_calculated_correctly(){var technical=70m;var financial=25m;var total=technical+financial;Assert.Equal(95m,total);}    
    [Fact] public void Consensus_scores_are_recorded(){var e=Evaluation(Opening(BidOpeningSessionStatus.Completed),[OpeningSubmission(Guid.NewGuid(),BidOpeningSubmissionStatus.Opened)]);var sub=e.Submissions.Single();e.ConsensusScores.Add(new EvaluationConsensusScore(e.Id,sub.Id,Guid.NewGuid(),EvaluationStage.Consensus,92,"Consensus", "chair@lca.org.ls",DateTimeOffset.UtcNow));Assert.Single(e.ConsensusScores);}    
    [Fact] public void Submissions_are_ranked(){var subs=new[]{new EvaluationSubmission(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),"A","A",EvaluationSubmissionStatus.Evaluated,TotalScore:90),new EvaluationSubmission(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),"B","B",EvaluationSubmissionStatus.Evaluated,TotalScore:95)}.OrderByDescending(x=>x.TotalScore).Select((x,i)=>x with{Rank=i+1}).ToList();Assert.Equal("B",subs.First().SupplierName);Assert.Equal(1,subs.First().Rank);}    
    [Fact] public void Recommendation_is_required_before_completion(){var e=Evaluation(Opening(BidOpeningSessionStatus.Completed),[]);Assert.Throws<InvalidOperationException>(()=>{if(!e.Recommendations.Any())throw new InvalidOperationException("Recommendation exists before completion rule failed.");});}
    [Fact] public void Evaluation_report_is_generated(){var e=Evaluation(Opening(BidOpeningSessionStatus.Completed),[]);e.Reports.Add(new EvaluationReport(e.Id,"EVR-001",DateTimeOffset.UtcNow,"chair@lca.org.ls","{}"));Assert.Contains(e.Reports,r=>r.ReportNumber=="EVR-001");}
    [Fact] public void Completed_evaluation_can_be_referred_to_award(){var e=Evaluation(Opening(BidOpeningSessionStatus.Completed),[]) with { Status=EvaluationSessionStatus.Completed };e=e with{Status=EvaluationSessionStatus.ReferredToAward};Assert.Equal(EvaluationSessionStatus.ReferredToAward,e.Status);}    
    [Fact] public void Audit_events_are_created_throughout(){var id=Guid.NewGuid();var events=new[]{"Evaluation session created","Committee member added","Declaration accepted","Evaluation started","Technical score recorded","Financial score recorded","Consensus score recorded","Recommendation recorded","Evaluation completed","Evaluation report generated","Referred to award"}.Select(x=>new AuditEvent(x,nameof(EvaluationSession),id,"EV-003","actor",x,DateTimeOffset.UtcNow)).ToList();Assert.Contains(events,x=>x.EventType=="Consensus score recorded");Assert.True(events.Count>=11);}    
    static BidOpeningSession Opening(BidOpeningSessionStatus status)=>new("BO-EV",Guid.NewGuid(),"Opening",DateTimeOffset.UtcNow,status,"user",DateTimeOffset.UtcNow,"Chair");
    static BidOpeningSubmission OpeningSubmission(Guid openingId,BidOpeningSubmissionStatus status)=>new(openingId,Guid.NewGuid(),Guid.NewGuid(),"Supplier","BID-EV",DateTimeOffset.UtcNow,status);
    static EvaluationSession Evaluation(BidOpeningSession opening,IEnumerable<BidOpeningSubmission> opened){var e=new EvaluationSession("EV-SESSION",opening.TenderId,opening.Id,"Evaluation",EvaluationSessionStatus.Draft,EvaluationStage.Administrative,"user",DateTimeOffset.UtcNow,"Chair");foreach(var bid in opened.Where(x=>x.Status==BidOpeningSubmissionStatus.Opened||x.Status==BidOpeningSubmissionStatus.ReferredToEvaluation))e.Submissions.Add(new EvaluationSubmission(e.Id,bid.BidSubmissionId,bid.SupplierId,bid.SupplierName,bid.SubmissionNumber,EvaluationSubmissionStatus.Pending));return e;}
}
