using Lca.EProcurement.Domain;
using Xunit;

namespace Lca.EProcurement.Tests;

public class PurchaseOrderManagementTests
{
    [Fact] public void Award_generates_purchase_order_and_copies_supplier(){var (award, po)=Fixture();Assert.Equal(award.Id,po.AwardId);Assert.Equal(award.SupplierId,po.SupplierId);Assert.Equal(award.SupplierName,po.SupplierName);}
    [Fact] public void Items_are_copied_as_multiple_po_lines(){var (award, po)=Fixture();Assert.Equal(award.Items.Count,po.Lines.Count);Assert.Equal(award.Items.Sum(x=>x.TotalAmount),po.Lines.Sum(x=>x.Total));}
    [Fact] public void Workflow_starts_for_purchase_order(){var (_, po)=Fixture();var workflow=new WorkflowInstance(Guid.NewGuid(),Guid.NewGuid(),nameof(PurchaseOrder),po.Id,"Draft");Assert.Equal(nameof(PurchaseOrder),workflow.EntityType);Assert.Equal("Draft",workflow.CurrentNodeCode);}
    [Fact] public void Supplier_acknowledgement_updates_status_and_audit(){var (_, po)=Fixture();po=po with{Status=PurchaseOrderStatus.Acknowledged};po.History.Add(new(po.Id,"Supplier Acknowledged","supplier","Supplier confirmed receipt",DateTimeOffset.UtcNow));Assert.Equal(PurchaseOrderStatus.Acknowledged,po.Status);Assert.Contains(po.History,x=>x.EventType=="Supplier Acknowledged");}
    [Fact] public void Delivery_tracking_updates_outstanding_quantities(){var (_, po)=Fixture();var line=po.Lines.First();line=line with{DeliveredQuantity=1,OutstandingQuantity=line.Quantity-1};Assert.Equal(1,line.DeliveredQuantity);Assert.Equal(1,line.OutstandingQuantity);}
    [Fact] public void Goods_receipt_is_prepared_from_delivery(){var (_, po)=Fixture();po.Deliveries.Add(new(po.Id,DateTimeOffset.UtcNow,"Courier","Stores","Partial delivery"));po.GoodsReceipts.Add(new(po.Id,"GRN-001",DateTimeOffset.UtcNow,"Stores","Prepared"));Assert.Single(po.Deliveries);Assert.Contains(po.GoodsReceipts,x=>x.ReceiptNumber=="GRN-001");}
    [Fact] public void Budget_commitment_update_is_recorded_on_closure(){var (_, po)=Fixture();foreach(var line in po.Lines){var updated=line with{DeliveredQuantity=line.Quantity,OutstandingQuantity=0};Assert.Equal(0,updated.OutstandingQuantity);}po=po with{Status=PurchaseOrderStatus.Closed,ClosedAt=DateTimeOffset.UtcNow};po.History.Add(new(po.Id,"PO Closed","procurement","Budget commitment updated",DateTimeOffset.UtcNow));Assert.Equal(PurchaseOrderStatus.Closed,po.Status);Assert.Contains(po.History,x=>x.Details.Contains("Budget commitment"));}
    [Fact] public void Audit_events_are_generated(){var (_, po)=Fixture();var events=new[]{"PO Created","PO Issued","Supplier Acknowledged","Delivery Recorded","Goods Receipt","PO Closed","PO Cancelled","PO Amended"}.Select(x=>new AuditEvent(x,nameof(PurchaseOrder),po.Id,po.PurchaseOrderNumber,"actor",x,DateTimeOffset.UtcNow)).ToList();Assert.Contains(events,x=>x.EventType=="Delivery Recorded");Assert.True(events.Count>=8);}
    [Fact] public void Cancelled_po_cannot_be_delivered(){var (_, po)=Fixture();po=po with{Status=PurchaseOrderStatus.Cancelled};Assert.Throws<InvalidOperationException>(()=>{if(po.Status==PurchaseOrderStatus.Cancelled)throw new InvalidOperationException("Cancelled PO cannot be delivered.");});}
    [Fact] public void Closed_po_cannot_be_amended(){var (_, po)=Fixture();po=po with{Status=PurchaseOrderStatus.Closed};Assert.Throws<InvalidOperationException>(()=>{if(po.Status==PurchaseOrderStatus.Closed)throw new InvalidOperationException("Closed PO cannot be amended.");});}
    static (Award award,PurchaseOrder po) Fixture(){var award=new Award("AWD-001",Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),"Winning Supplier",300,AwardStatus.Approved,"user",DateTimeOffset.UtcNow,ApprovedAt:DateTimeOffset.UtcNow);award.Items.Add(new(award.Id,Guid.NewGuid(),"Service A",2,100,200));award.Items.Add(new(award.Id,Guid.NewGuid(),"Service B",1,100,100));var po=new PurchaseOrder("PO-001",award.Id,award.SupplierId,award.SupplierName,null,DateTimeOffset.UtcNow.AddDays(30),"LSL",award.AwardAmount,PurchaseOrderStatus.Draft,"user",DateTimeOffset.UtcNow);var item=1;foreach(var i in award.Items)po.Lines.Add(new(po.Id,item++,i.Description,i.Quantity,i.UnitPrice,i.TotalAmount,0,i.Quantity));return(award,po);}    
}
