import { useEffect, useMemo, useState } from "react";
import { navigate } from "../../app/routes";
import { Button } from "../../components/ui/Button";
import { getPublicAwardNotices, getPublicTenderCalendar, getPublicTenders, type PublicAwardNotice, type PublicTenderCalendarItem, type PublicTenderSummary } from "../../services/publicTendersApi";
import { categoryOf, formatDate, isClosingSoon, referenceOf } from "./PublicOpportunitiesPage";

function Stat({ value, label }: { value: string | number; label: string }) { return <div className="portal-stat"><strong>{value}</strong><span>{label}</span></div>; }
function OpportunityMini({ tender }: { tender: PublicTenderSummary }) { return <article className="portal-mini-card"><p className="opportunity-reference">{referenceOf(tender)}</p><h3>{tender.title}</h3><p>{categoryOf(tender)} · Closes {formatDate(tender.closingDate)}</p><Button variant="secondary" onClick={() => navigate(`/public/opportunities/${encodeURIComponent(referenceOf(tender))}`)}>View notice</Button></article>; }

export function PublicPortalHomePage() {
  const [tenders, setTenders] = useState<PublicTenderSummary[]>([]);
  const [awards, setAwards] = useState<PublicAwardNotice[]>([]);
  const [calendar, setCalendar] = useState<PublicTenderCalendarItem[]>([]);
  useEffect(() => { Promise.all([getPublicTenders(), getPublicAwardNotices(), getPublicTenderCalendar()]).then(([t, a, c]) => { setTenders(t.data); setAwards(a.data); setCalendar(c.data); }); }, []);
  const latest = [...tenders].sort((a,b) => new Date(b.publishedAt || b.publishedDate || b.publicationDate || 0).getTime() - new Date(a.publishedAt || a.publishedDate || a.publicationDate || 0).getTime()).slice(0,3);
  const closing = tenders.filter(t => isClosingSoon(t.closingDate)).slice(0,3);
  return <div className="public-portal"><section className="public-hero"><p className="landing-kicker">Public Procurement Portal</p><h1>Open, fair, and transparent LCA procurement.</h1><p>Find published procurement opportunities, download public documents, review award notices, and register as a supplier through ProcuraFlow.</p><div className="landing-actions"><Button onClick={() => navigate("/public/opportunities")}>View opportunities</Button><Button variant="secondary" onClick={() => navigate("/public/register")}>Register as supplier</Button></div></section><section className="portal-section"><h2>Latest Opportunities</h2><div className="portal-card-grid">{latest.length ? latest.map(t => <OpportunityMini key={referenceOf(t)} tender={t} />) : <p className="public-empty inline">No published opportunities are currently available.</p>}</div></section><section className="portal-section two-col"><div><h2>Closing Soon</h2>{closing.length ? closing.map(t => <OpportunityMini key={referenceOf(t)} tender={t} />) : <p>No opportunities are closing within the next seven days.</p>}</div><div><h2>Award Notices</h2>{awards.slice(0,3).map(a => <article className="portal-mini-card" key={a.awardNumber}><p className="opportunity-reference">{a.awardNumber}</p><h3>{a.tenderTitle}</h3><p>Awarded to {a.supplierName} on {formatDate(a.publishedAt || a.createdAt)}</p></article>)}{!awards.length && <p>No award notices have been published.</p>}</div></section><section className="portal-section cta"><h2>Become an LCA supplier</h2><p>Register your organisation to receive procurement updates and prepare online bid submissions.</p><Button onClick={() => navigate("/public/register")}>Start supplier registration</Button></section><section className="portal-section two-col"><div><h2>Procurement Calendar</h2>{calendar.slice(0,4).map(i => <p key={i.reference}><strong>{i.title}</strong><br />{formatDate(i.publishedAt)} – closes {formatDate(i.closingDate)}</p>)}{!calendar.length && <p>No calendar events are currently published.</p>}</div><div><h2>Statistics</h2><div className="portal-stats"><Stat value={tenders.length} label="Published opportunities" /><Stat value={closing.length} label="Closing soon" /><Stat value={awards.length} label="Award notices" /></div><h2>Contact Information</h2><p>Procurement Unit, Lesotho Communications Authority<br />procurement@lca.org.ls · +266 2222 4300</p></div></section></div>;
}

export function PublicCalendarPage() { const [items, setItems] = useState<PublicTenderCalendarItem[]>([]); useEffect(() => { getPublicTenderCalendar().then(r => setItems(r.data)); }, []); return <div className="public-portal"><section className="public-hero compact"><p className="landing-kicker">Calendar</p><h1>Procurement calendar</h1><p>Track published tender dates and closing deadlines.</p></section><section className="opportunity-list">{items.map(i => <article className="opportunity-card" key={i.reference}><div><p className="opportunity-reference">{i.reference}</p><h2>{i.title}</h2><p>{i.category}</p></div><div className="opportunity-meta"><span>Published {formatDate(i.publishedAt)}</span><span>Closes {formatDate(i.closingDate)}</span></div><Button variant="secondary" onClick={() => navigate(`/public/opportunities/${encodeURIComponent(i.reference)}`)}>View</Button></article>)}{!items.length && <p className="public-empty">No calendar items are currently published.</p>}</section></div>; }
export function PublicAwardsPage() { const [items, setItems] = useState<PublicAwardNotice[]>([]); useEffect(() => { getPublicAwardNotices().then(r => setItems(r.data)); }, []); return <div className="public-portal"><section className="public-hero compact"><p className="landing-kicker">Award Notices</p><h1>Published award notices</h1><p>Review public award outcomes after official publication.</p></section><section className="opportunity-list">{items.map(a => <article className="opportunity-card" key={a.awardNumber}><div><p className="opportunity-reference">{a.awardNumber}</p><h2>{a.tenderTitle}</h2><p>Tender {a.tenderNumber} · Awarded supplier: {a.supplierName}</p></div><div className="opportunity-meta"><span>{a.currency || "LSL"} {Number(a.awardAmount || 0).toLocaleString()}</span><span>{formatDate(a.publishedAt || a.createdAt)}</span></div></article>)}{!items.length && <p className="public-empty">No award notices have been published.</p>}</section></div>; }
export function PublicRegisterPage() { return <div className="public-portal"><section className="public-hero compact"><p className="landing-kicker">Supplier Registration</p><h1>Register as an LCA supplier.</h1><p>Create or update your supplier profile before bidding for published procurement opportunities.</p><Button onClick={() => navigate("/login")}>Continue to secure registration</Button></section><section className="portal-section"><h2>Before you begin</h2><div className="portal-card-grid"><article className="portal-mini-card"><h3>Company information</h3><p>Prepare legal name, registration number, tax details, and contact persons.</p></article><article className="portal-mini-card"><h3>Compliance documents</h3><p>Upload public-facing compliance certificates in the secure supplier workspace.</p></article><article className="portal-mini-card"><h3>Procurement categories</h3><p>Select categories relevant to your goods, works, or services.</p></article></div></section></div>; }
export function PublicHelpPage() { return <div className="public-portal"><section className="public-hero compact"><p className="landing-kicker">Help</p><h1>Supplier help and FAQ</h1><p>Guidance for finding opportunities, registering, and submitting bids.</p></section><section className="portal-section faq"><h2>Frequently asked questions</h2>{["Do I need to log in to view tenders? No. Public notices and documents are available anonymously.","How do I submit a bid? Open a tender detail page and select Submit Bid. Anonymous users are redirected to login.","Where are internal evaluations shown? They are not shown on the public portal.","Who can I contact? Email procurement@lca.org.ls for public procurement support."].map(q => { const [question, answer] = q.split("? "); return <details key={q}><summary>{question}?</summary><p>{answer}</p></details>; })}</section></div>; }
