import { useEffect, useState } from "react";
import { PageHeader } from "../../components/ui/PageHeader";
import { MetricCard } from "../../components/ui/MetricCard";
import { getExternalReferences, getIntegrationDashboard, getIntegrationEndpoints, getIntegrationLogs, getIntegrationMessages, testIntegrationEndpoint, type IntegrationEndpoint } from "../../services/integrationsApi";

function EndpointList({ filter }: { filter?: string }) { const [rows,setRows]=useState<IntegrationEndpoint[]>([]); useEffect(()=>{getIntegrationEndpoints().then(r=>setRows(r.data));},[]); const list=filter?rows.filter(x=>x.systemType===filter):rows; return <div className="card"><div className="card-body table-responsive"><table className="table"><thead><tr><th>Code</th><th>Name</th><th>System</th><th>Auth</th><th>Status</th><th>Base URL</th><th></th></tr></thead><tbody>{list.map(e=><tr key={e.id}><td>{e.code}</td><td>{e.name}</td><td>{e.systemType}</td><td>{e.authType}</td><td>{e.isEnabled?"Enabled":"Disabled"}</td><td>{e.baseUrl || "Not configured"}</td><td><button className="btn btn-sm btn-outline-primary" onClick={()=>testIntegrationEndpoint(e.id)}>Test connection</button></td></tr>)}</tbody></table></div></div> }
export function IntegrationDashboardPage(){const [d,setD]=useState<any>({}); useEffect(()=>{getIntegrationDashboard().then(r=>setD(r.data));},[]); return <><PageHeader title="Integration Management" description="Configure LCA contract, document and future system connectors without replacing procurement modules."/><div className="row g-3"><MetricCard label="Configured endpoints" value={d.configuredEndpoints ?? 0}/><MetricCard label="Enabled endpoints" value={d.enabledEndpoints ?? 0}/><MetricCard label="Failed messages" value={d.failedMessages ?? 0}/><MetricCard label="Pending messages" value={d.pendingMessages ?? 0}/></div><p className="text-muted mt-3">Last sync: {d.lastSyncDate || "No sync yet"}</p><EndpointList /></>}
export function ContractIntegrationPage(){const [messages,setMessages]=useState<any[]>([]); const [refs,setRefs]=useState<any[]>([]); useEffect(()=>{getIntegrationMessages().then(r=>setMessages(r.data.filter((x:any)=>x.entityType==="Contract"))); getExternalReferences().then(r=>setRefs(r.data.filter((x:any)=>x.entityType==="Contract")));},[]); return <><PageHeader title="Contract Management Connector" description="Handover approved contract metadata to LCA's existing contract management system."/><EndpointList filter="ContractManagement"/><h3>Recent handovers</h3><ul>{messages.map(m=><li key={m.id}>{m.status} · {m.createdAt} {m.errorMessage}</li>)}</ul><h3>External references</h3><ul>{refs.map(r=><li key={r.id}>{r.externalSystemCode}: {r.externalReference} ({r.status})</li>)}</ul></>}
export function DocumentIntegrationPage(){return <><PageHeader title="Document Management Connector" description="Placeholder for metadata sync, storage references, external document IDs and sync status."/><EndpointList filter="DocumentManagement"/><div className="card"><div className="card-body"><strong>Storage mode:</strong> Metadata-only sync. Actual file transfer is disabled until DMS file APIs are available.</div></div></>}
export function IntegrationLogsPage(){const [logs,setLogs]=useState<any[]>([]); useEffect(()=>{getIntegrationLogs().then(r=>setLogs(r.data));},[]); return <><PageHeader title="Integration Logs" description="Connector event trail for permitted users."/><div className="card"><div className="card-body table-responsive"><table className="table"><thead><tr><th>Entity</th><th>System</th><th>Direction</th><th>Status</th><th>Error</th><th>Timestamp</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{l.entityType}</td><td>{l.externalSystemCode}</td><td>{l.direction}</td><td>{l.status}</td><td>{l.error}</td><td>{l.timestamp}</td></tr>)}</tbody></table></div></div></>}
