import { useEffect, useState } from "react";
import { Button } from "../../components/ui/Button";
import { PageHeader } from "../../components/ui/PageHeader";
import { Badge } from "../../components/ui/Badge";
import { navigate } from "../../app/routes";
import { requisitionsApi, type Requisition, type BudgetValidation } from "../../services/requisitionsApi";
import { planningApi, type CostCentre, type ProcurementCategory } from "../../services/planningApi";

export function RequisitionListPage() { const [items,setItems]=useState<Requisition[]>([]); useEffect(()=>{ requisitionsApi.list().then(r=>setItems(r.data)); },[]); return <><PageHeader title="Requisitions" description="Create and approve internal requisitions with budget validation." actions={<Button onClick={()=>navigate('/app/requisitions/new')}>New requisition</Button>} /><div className="card"><div className="card-body table-responsive"><table className="table"><thead><tr><th>Number</th><th>Title</th><th>Department</th><th>Total</th><th>Status</th></tr></thead><tbody>{items.map(r=><tr key={r.id} onClick={()=>navigate(`/app/requisitions/${r.id}`)} role="button"><td>{r.requisitionNumber}</td><td>{r.title}</td><td>{r.department}</td><td>M {r.estimatedTotal.toLocaleString()}</td><td><Badge>{r.status}</Badge></td></tr>)}</tbody></table></div></div></>; }
export function NewRequisitionPage() { const [costCentres,setCostCentres]=useState<CostCentre[]>([]); const [categories,setCategories]=useState<ProcurementCategory[]>([]); const [form,setForm]=useState({ requisitionNumber:`REQ-${new Date().getFullYear()}-${Math.floor(Math.random()*9000+1000)}`, title:"", description:"", department:"", costCentreId:"", financialYearId:"00000000-0000-0000-0000-000000000000", requestedBy:"requester@lca.org.ls", requiredDate:new Date().toISOString().slice(0,10), priority:"Normal", itemDescription:"", quantity:1, unitOfMeasure:"Each", estimatedUnitPrice:0, procurementCategoryId:"" }); useEffect(()=>{ planningApi.costCentres().then(r=>{const x=r.data; setCostCentres(x); if(x[0]) setForm(f=>({...f,costCentreId:x[0].id,department:x[0].department}));}); planningApi.categories().then(r=>{const x=r.data; setCategories(x); if(x[0]) setForm(f=>({...f,procurementCategoryId:x[0].id}));});},[]); async function save(){ const r=await requisitionsApi.create({...form, requiredDate:new Date(form.requiredDate).toISOString(), items:[{description:form.itemDescription, quantity:Number(form.quantity), unitOfMeasure:form.unitOfMeasure, estimatedUnitPrice:Number(form.estimatedUnitPrice), procurementCategoryId:form.procurementCategoryId}]}); navigate(`/app/requisitions/${r.data.id}`); } return <><PageHeader title="New requisition" description="Use real planning and budget reference data." /><div className="card"><div className="card-body row g-3"><input className="form-control" placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className="form-control" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select className="form-select" value={form.costCentreId} onChange={e=>{const cc=costCentres.find(x=>x.id===e.target.value); setForm({...form,costCentreId:e.target.value,department:cc?.department||form.department});}}>{costCentres.map(c=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select><input className="form-control" placeholder="Item description" value={form.itemDescription} onChange={e=>setForm({...form,itemDescription:e.target.value})}/><input className="form-control" type="number" placeholder="Estimated unit price" value={form.estimatedUnitPrice} onChange={e=>setForm({...form,estimatedUnitPrice:Number(e.target.value)})}/><select className="form-select" value={form.procurementCategoryId} onChange={e=>setForm({...form,procurementCategoryId:e.target.value})}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Button onClick={save}>Create requisition</Button></div></div></>; }
function BudgetPanel({id}:{id:string}){ const [v,setV]=useState<BudgetValidation>(); useEffect(()=>{ requisitionsApi.budgetValidation(id).then(r=>setV(r.data)); },[id]); if(!v) return null; return <div className="alert alert-info"><strong>Budget validation</strong><div>Required: M {v.requiredAmount.toLocaleString()} | Available: M {v.availableAmount.toLocaleString()}</div><div>{v.budgetAvailable ? 'Budget available' : v.messages.join(' ')}</div></div> }
export function RequisitionDetailPage({id}:{id:string}) { const [r,setR]=useState<Requisition|null>(); const load=()=>{ requisitionsApi.get(id).then(r=>setR(r.data)); }; useEffect(load,[id]); if(!r) return <p>Loading...</p>; return <><PageHeader title={r.requisitionNumber} description={r.title} actions={<><Button onClick={async()=>{await requisitionsApi.submit(id); load();}}>Submit</Button><Button onClick={async()=>{await requisitionsApi.approve(id); load();}}>Approve</Button><Button variant="secondary" onClick={async()=>{await requisitionsApi.reject(id); load();}}>Reject</Button></>} /><BudgetPanel id={id}/><div className="card"><div className="card-body"><Badge>{r.status}</Badge><p>{r.description}</p><h5>Items</h5>{r.items.map(i=><div key={i.id}>{i.description}: {i.quantity} {i.unitOfMeasure} × M {i.estimatedUnitPrice} = M {i.estimatedTotal}</div>)}</div></div></>; }
export function RequisitionApprovalWorkspacePage(){ return <RequisitionListPage/>; }
