import { FormEvent, useEffect, useMemo, useState } from "react";
import { navigate } from "../../app/routes";
import { Badge, StatusBadge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { DataTable } from "../../components/ui/DataTable";
import { EmptyState } from "../../components/ui/EmptyState";
import { LoadingState } from "../../components/ui/LoadingState";
import { PageHeader } from "../../components/ui/PageHeader";
import { createBid, getBid, getBids, submitBid, uploadBidDocument, withdrawBid, BidSubmission } from "../../services/bidsApi";

export function BidSubmissionListPage() {
  const [items, setItems] = useState<BidSubmission[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  useEffect(() => { getBids().then(r => { setItems(r.data); setError(r.error); setLoading(false); }); }, []);
  if (loading) return <LoadingState />;
  return <><PageHeader title="Bid Submissions" description="Electronic supplier bids driven by platform workflow, rules, documents, audit and UI composition metadata." actions={<Button onClick={() => navigate("/app/bids/new")}>New bid submission</Button>} />{error && <div className="alert alert-warning">{error}</div>}{items.length === 0 ? <EmptyState title="No bid submissions" message="Create the first draft bid against a published tender." /> : <DataTable searchable rows={items} columns={[{ header: "Submission", sortable: true, cell: b => <button className="btn btn-link p-0" onClick={() => navigate(`/app/bids/${b.id}`)}>{b.submissionNumber}</button> }, { header: "Status", sortable: true, cell: b => <StatusBadge status={b.status} /> }, { header: "Version", cell: b => `v${b.currentVersion}` }, { header: "Progress", cell: b => <Progress bid={b} /> }, { header: "Documents", cell: b => `${b.documents?.length ?? 0} uploaded` }, { header: "Submitted by", cell: b => b.submittedBy }]} pageSize={10} />}</>;
}

export function NewBidSubmissionPage() {
  const [error, setError] = useState<string>();
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await createBid({ submissionNumber: String(f.get("submissionNumber")), tenderId: String(f.get("tenderId")), supplierId: String(f.get("supplierId")), submittedBy: "supplier@demo.ls", items: [{ description: String(f.get("description")), quantity: Number(f.get("quantity")), unitPrice: Number(f.get("unitPrice")), notes: String(f.get("notes")) }], declarations: [{ declarationType: "Confidentiality Declaration", accepted: true, acceptedBy: "supplier@demo.ls" }] }); if (r.error) setError(r.error); else navigate(`/app/bids/${r.data.id}`); }
  return <><PageHeader title="New Bid Submission" description="Creates a draft bid that consumes the configured Bid Submission process, dynamic form and document requirements." /><div className="card"><form className="card-body" onSubmit={submit}>{error && <div className="alert alert-danger">{error}</div>}<div className="row g-3"><div className="col-md-4"><label className="form-label">Submission number</label><input name="submissionNumber" className="form-control" defaultValue={`BID-SUB-${Date.now()}`} required /></div><div className="col-md-4"><label className="form-label">Tender Id</label><input name="tenderId" className="form-control" required /></div><div className="col-md-4"><label className="form-label">Supplier Id</label><input name="supplierId" className="form-control" required /></div><div className="col-md-6"><label className="form-label">Line description</label><input name="description" className="form-control" required /></div><div className="col-md-3"><label className="form-label">Quantity</label><input name="quantity" type="number" className="form-control" defaultValue="1" required /></div><div className="col-md-3"><label className="form-label">Unit price</label><input name="unitPrice" type="number" className="form-control" defaultValue="0" required /></div><div className="col-12"><label className="form-label">Notes</label><textarea name="notes" className="form-control" /></div></div><div className="mt-3"><Button>Create draft bid</Button></div></form></div></>;
}

export function BidSubmissionDetailPage({ id }: { id: string }) {
  const [bid, setBid] = useState<BidSubmission | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  const load = () => getBid(id).then(r => { setBid(r.data); setError(r.error); setLoading(false); }); useEffect(() => { load(); }, [id]);
  const total = useMemo(() => bid?.items?.reduce((sum, i) => sum + i.total, 0) ?? 0, [bid]);
  if (loading) return <LoadingState />; if (!bid) return <EmptyState title="Bid not found" message="The bid submission could not be loaded." />;
  const locked = ["Locked", "Submitted", "Opened", "Evaluated", "Awarded", "Rejected"].includes(bid.status);
  return <><PageHeader title={bid.submissionNumber} description="Workflow-driven bid submission detail with documents, declarations, timeline, history and validation." actions={<><Button variant="secondary" onClick={() => navigate("/app/bids")}>Back</Button>{!locked && <Button onClick={async () => { const r = await submitBid(id); if (r.error) setError(r.error); load(); }}>Submit</Button>}<Button variant="secondary" onClick={async () => { await withdrawBid(id); load(); }}>Withdraw</Button></>} />{error && <div className="alert alert-warning">{error}</div>}<div className="row g-3"><div className="col-lg-8"><div className="card"><div className="card-body"><StatusBadge status={bid.status} /><Progress bid={bid} /><h5 className="mt-3">Pricing summary</h5><DataTable compact rows={bid.items ?? []} columns={[{ header: "Description", cell: i => i.description }, { header: "Qty", cell: i => i.quantity }, { header: "Unit price", cell: i => i.unitPrice.toLocaleString() }, { header: "Total", cell: i => i.total.toLocaleString() }]} /><div className="text-end fs-5 mt-2">Total: <strong>{total.toLocaleString()}</strong></div></div></div><Timeline bid={bid} /></div><div className="col-lg-4"><DocumentPanel bid={bid} reload={load} /><div className="card mt-3"><div className="card-header">Declarations</div><div className="list-group list-group-flush">{bid.declarations?.map(d => <div className="list-group-item" key={d.id}>{d.declarationType}<br/><Badge tone={d.accepted ? "success" : "danger"}>{d.accepted ? "Accepted" : "Not accepted"}</Badge></div>)}</div></div><div className="card mt-3"><div className="card-header">Validation summary</div><div className="card-body"><ul><li>Dynamic Form: configured via BID-SUBMISSION-FORM</li><li>Documents: {bid.documents?.length ?? 0} uploaded</li><li>Business Rules: executed on submit</li><li>Workflow Status: {bid.status}</li></ul></div></div></div></div></>;
}
function Progress({ bid }: { bid: BidSubmission }) { const order = ["Draft", "Submitted", "Locked", "Opened", "Evaluated", "Awarded"]; const i = Math.max(0, order.indexOf(bid.status)); return <div className="progress mt-2" role="progressbar"><div className="progress-bar" style={{ width: `${((i + 1) / order.length) * 100}%` }}>{order[i] ?? bid.status}</div></div>; }
function Timeline({ bid }: { bid: BidSubmission }) { return <div className="card mt-3"><div className="card-header">Timeline and history</div><div className="card-body">{[...(bid.history ?? [])].sort((a,b) => a.occurredAt.localeCompare(b.occurredAt)).map(h => <p key={h.id}><strong>{h.eventType}</strong><br/><span>{h.details}</span><br/><small>{h.actor} · {new Date(h.occurredAt).toLocaleString()}</small></p>)}</div></div>; }
function DocumentPanel({ bid, reload }: { bid: BidSubmission; reload: () => void }) { return <div className="card"><div className="card-header">Document upload panel</div><div className="card-body"><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await uploadBidDocument(bid.id, { documentType: String(f.get("documentType")), filename: String(f.get("filename")), storageReference: `vault://future/${f.get("filename")}`, uploadedBy: "supplier@demo.ls" }); e.currentTarget.reset(); reload(); }}><select name="documentType" className="form-select mb-2"><option>Technical Proposal</option><option>Financial Proposal</option><option>Company Registration</option><option>Tax Clearance</option><option>Bid Security</option><option>Confidentiality Declaration</option></select><input name="filename" className="form-control mb-2" placeholder="proposal.pdf" required /><Button>Upload metadata</Button></form></div><div className="list-group list-group-flush">{bid.documents?.map(d => <div className="list-group-item" key={d.id}><strong>{d.documentType}</strong><br/>{d.filename}<br/><small>v{d.version} · future secure vault ready</small></div>)}</div></div>; }
