import { useEffect, useState } from "react";
import { navigate } from "../../app/routes";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { MetricCard } from "../../components/ui/MetricCard";
import { PageHeader } from "../../components/ui/PageHeader";
import * as api from "../../services/supplierPortalApi";

function useLoad<T>(loader: () => Promise<{ data: T }>, initial: T) { const [data, setData] = useState(initial); useEffect(() => { loader().then(r => setData(r.data)); }, []); return data; }
export function SupplierDashboardPage() { const d = useLoad(api.supplierDashboard, { profileStatus: "", missingDocuments: [], openOpportunities: 0, draftBids: 0, submittedBids: 0, clarificationsAwaitingResponse: 0, unreadNotifications: 0 }); return <><PageHeader title="Supplier Dashboard" description="Your secure supplier workspace."/><div className="metric-grid"><MetricCard label="Profile status" value={d.profileStatus || "Loading"}/><MetricCard label="Missing documents" value={d.missingDocuments.length}/><MetricCard label="Open opportunities" value={d.openOpportunities}/><MetricCard label="Draft bids" value={d.draftBids}/><MetricCard label="Submitted bids" value={d.submittedBids}/><MetricCard label="Clarifications awaiting response" value={d.clarificationsAwaitingResponse}/><MetricCard label="Unread notifications" value={d.unreadNotifications}/></div>{d.missingDocuments.length > 0 && <Card><h3>Missing documents</h3><ul>{d.missingDocuments.map(x => <li key={x}>{x}</li>)}</ul></Card>}</>; }
export function SupplierProfilePage() { const p = useLoad(api.supplierProfile, {} as api.SupplierProfile); const [form,setForm]=useState<Partial<api.SupplierProfile>>({}); useEffect(()=>setForm(p),[p.id]); const save=()=>api.updateSupplierProfile({...form, categories: typeof form.categories === "string" ? String(form.categories).split(",").map(x=>x.trim()) : form.categories} as Partial<api.SupplierProfile>).then(r=>setForm(r.data)); return <><PageHeader title="My Profile" description="Maintain your supplier information."/><Card><div className="form-grid">{["legalName","tradingName","registrationNumber","taxNumber","contactPerson","email","phone","address"].map(k=><label key={k}>{k}<input className="form-control" value={String((form as Record<string,unknown>)[k] ?? "")} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Categories<input className="form-control" value={(form.categories ?? []).join(", ")} onChange={e=>setForm({...form,categories:e.target.value.split(",")})}/></label></div><Button onClick={save}>Save profile</Button></Card></>; }
export function SupplierDocumentsPage() { const docs = useLoad(api.supplierDocuments, []); return <><PageHeader title="My Documents"/><Card><table className="table"><tbody>{docs.map(d=><tr key={d.id}><td>{d.documentType}</td><td>{d.fileName}</td><td>{new Date(d.uploadedAt).toLocaleDateString()}</td></tr>)}</tbody></table></Card></>; }
export function SupplierOpportunitiesPage() { const rows = useLoad(api.supplierOpportunities, []); return <><PageHeader title="Opportunities" description="Published tenders available to suppliers."/><Card><table className="table"><tbody>{rows.map(o=><tr key={o.reference}><td><strong>{o.reference}</strong><br/>{o.title}</td><td>{o.category}</td><td>{new Date(o.closingDate).toLocaleString()}</td><td><Button onClick={()=>navigate(`/app/supplier/opportunities?ref=${encodeURIComponent(o.reference)}`)}>View</Button></td></tr>)}</tbody></table></Card></>; }
export function SupplierBidsPage() { const bids = useLoad(api.supplierBids, []); return <><PageHeader title="My Bids"/><Card><table className="table"><tbody>{bids.map(b=><tr key={b.id}><td>{b.submissionNumber}</td><td>{b.status}</td><td>{b.submittedAt ? new Date(b.submittedAt).toLocaleString() : "Draft"}</td><td><Button onClick={()=>navigate(`/app/supplier/bids/${b.id}`)}>Open</Button></td></tr>)}</tbody></table></Card></>; }
export function SupplierBidDetailPage({id}:{id:string}) { const b = useLoad(()=>api.supplierBid(id), {} as api.Bid); return <><PageHeader title={b.submissionNumber || "Bid"} description={b.status}/><Card><h3>Items</h3><ul>{(b.items||[]).map((i,idx)=><li key={idx}>{i.description}: {i.total}</li>)}</ul><h3>Documents</h3><ul>{(b.documents||[]).map((d,idx)=><li key={idx}>{d.documentType}: {d.filename}</li>)}</ul></Card></>; }
export function SupplierClarificationsPage() { const rows = useLoad(api.supplierClarifications, []); return <><PageHeader title="Clarifications"/><Card>{rows.map(c=><article key={c.id}><strong>{c.tenderNumber}</strong><p>{c.question}</p><p className="muted">{c.responses.length ? c.responses[0].response : "Awaiting response"}</p></article>)}</Card></>; }
export function SupplierNotificationsPage() { const rows = useLoad(api.supplierNotifications, []); return <><PageHeader title="Notifications"/><Card>{rows.map(n=><article key={n.id}><strong>{n.subject}</strong><p>{n.body}</p><span className="badge text-bg-light">{n.status}</span></article>)}</Card></>; }
