import { apiDelete, apiGet, apiPost, apiPut } from "./apiClient";

export type NotificationMessage = { id: string; eventCode: string; channel: string; subject: string; body: string; priority: string; status: string; createdAt: string; relatedUrl?: string | null; recipients?: { status: string; readAt?: string | null }[] };
export type NotificationTemplate = { id?: string; code: string; name: string; description: string; eventCode: string; channel: string; subjectTemplate: string; bodyTemplate: string; isActive: boolean };
export type NotificationPreference = { eventCode: string; inAppEnabled: boolean; emailEnabled: boolean; smsEnabled: boolean };
export type Setting = { key: string; value: string; isSecret: boolean; category: string; isOverridden: boolean };
export type DeliveryLog = { id: string; notificationMessageId: string; channel: string; status: string; sentAt: string; error?: string | null; requestPayload: string; responsePayload: string };

export const getMyNotifications = () => apiGet<NotificationMessage[]>("/api/notifications/my", []);
export const getUnreadCount = () => apiGet<{ count: number }>("/api/notifications/my/unread-count", { count: 0 });
export const markNotificationRead = (id: string) => apiPost(`/api/notifications/${id}/mark-read`, {}, { success: true });
export const markAllNotificationsRead = () => apiPost("/api/notifications/mark-all-read", {}, { success: true });
export const getTemplates = () => apiGet<NotificationTemplate[]>("/api/notification-templates", []);
export const saveTemplate = (t: NotificationTemplate) => t.id ? apiPut(`/api/notification-templates/${t.id}`, t, t) : apiPost("/api/notification-templates", t, t);
export const testTemplate = (id: string, model: Record<string, string>) => apiPost<string>(`/api/notification-templates/${id}/test`, model, "");
export const getDeliveryLogs = () => apiGet<DeliveryLog[]>("/api/notification-delivery-logs", []);
export const getPreferences = () => apiGet<NotificationPreference[]>("/api/notification-preferences/my", []);
export const savePreferences = (p: NotificationPreference[]) => apiPut("/api/notification-preferences/my", p, p);
export const getSettings = () => apiGet<Setting[]>("/api/settings", []);
export const saveSetting = (s: Setting) => apiPut(`/api/settings/${encodeURIComponent(s.key)}`, s, s);
export const deleteSetting = (key: string) => apiDelete(`/api/settings/${encodeURIComponent(key)}`);
export type SendResult = { success: boolean; response: string; error?: string | null; rawJson?: unknown | null };
export const testEmailSettings = (to: string) => apiPost<SendResult>("/api/settings/test-email", { to }, { success: false, response: "", rawJson: null });
export const testSmsSettings = (destinationAddress: string) => apiPost<SendResult>("/api/settings/test-sms", { destinationAddress }, { success: false, response: "", rawJson: null });
export type NotificationEventMapping = { id?: string; eventCode: string; templateCode: string; channel: string; entityType: string; recipientRoleCode?: string | null; isActive: boolean };
export type CommunicationMessage = { id: string; senderName: string; senderType: string; body: string; isInternal: boolean; isPublic: boolean; createdAt: string };
export type CommunicationThread = { id: string; threadNumber: string; entityType: string; entityReference: string; subject: string; visibility: string; status: string; messages: CommunicationMessage[] };
export const retryDeliveryLog = (id: string) => apiPost<DeliveryLog>(`/api/notification-delivery-logs/${id}/retry`, {}, {} as DeliveryLog);
export const getEventMappings = () => apiGet<NotificationEventMapping[]>('/api/notification-event-mappings', []);
export const saveEventMapping = (m: NotificationEventMapping) => m.id ? apiPut(`/api/notification-event-mappings/${m.id}`, m, m) : apiPost('/api/notification-event-mappings', m, m);
export const runDeadlineReminders = () => apiPost('/api/notifications/reminders/run', {}, []);
export const getCommunicationThreads = () => apiGet<CommunicationThread[]>('/api/communications/threads', []);
export const getCommunicationThread = (id: string) => apiGet<CommunicationThread | null>(`/api/communications/threads/${id}`, null);
export const createCommunicationThread = (dto: unknown) => apiPost<CommunicationThread>('/api/communications/threads', dto, {} as CommunicationThread);
export const addCommunicationMessage = (id: string, dto: unknown) => apiPost<CommunicationMessage>(`/api/communications/threads/${id}/messages`, dto, {} as CommunicationMessage);
export const closeCommunicationThread = (id: string) => apiPost(`/api/communications/threads/${id}/close`, {}, { success: true });
export const getSupplierCommunicationThreads = () => apiGet<CommunicationThread[]>('/api/supplier/communications', []);
export const getSupplierCommunicationThread = (id: string) => apiGet<CommunicationThread | null>(`/api/supplier/communications/${id}`, null);
export const addSupplierCommunicationMessage = (id: string, dto: unknown) => apiPost<CommunicationMessage>(`/api/supplier/communications/${id}/messages`, dto, {} as CommunicationMessage);
