import { useEffect, useState } from "react";
import { DataTable } from "../../components/ui/DataTable";
import { EmptyState } from "../../components/ui/EmptyState";
import { LoadingState } from "../../components/ui/LoadingState";
import { MetricCard } from "../../components/ui/MetricCard";
import { PageHeader } from "../../components/ui/PageHeader";
import { StatusBadge } from "../../components/ui/Badge";
import { navigate } from "../../app/routes";
import { planningApi, type Plan, type Budget, type CostCentre, type ProcurementCategory, type PlanningDashboard } from "../../services/planningApi";
const money = (n:number) => new Intl.NumberFormat("en-LS", { style:"currency", currency:"LSL" }).format(n || 0);
function useLoad<T>(loader:()=>Promise<{data:T;error?:string}>, fallback:T){ const [data,setData]=useState(fallback); const [loading,setLoading]=useState(true); const [error,setError]=useState<string>(); useEffect(()=>{loader().then(r=>{setData(r.data); setError(r.error);}).finally(()=>setLoading(false));},[]); return {data,loading,error,setData}; }
export function PlanningPage(){ const d=useLoad<PlanningDashboard>(planningApi.dashboard,{plans:0,draftPlans:0,submittedPlans:0,approvedPlans:0,totalPlannedValue:0,totalBudgetValue:0,availableBudget:0}); const p=useLoad<Plan[]>(planningApi.plans,[]); if(d.loading||p.loading) return <LoadingState />; return <><PageHeader title="Annual Procurement Planning" description="Configuration-driven annual plans with workflow, budget and audit governance." actions={<button className="btn btn-primary" onClick={()=>navigate('/app/planning/new')}>New plan</button>}/><div className="metric-grid"><MetricCard label="Plans" value={d.data.plans}/><MetricCard label="Draft" value={d.data.draftPlans}/><MetricCard label="Submitted" value={d.data.submittedPlans}/><MetricCard label="Approved" value={d.data.approvedPlans}/><MetricCard label="Planned value" value={money(d.data.totalPlannedValue)}/><MetricCard label="Budget value" value={money(d.data.totalBudgetValue)}/><MetricCard label="Available budget" value={money(d.data.availableBudget)}/></div>{p.error&&<p className="text-danger">{p.error}</p>}<DataTable rows={p.data} searchable columns={[{header:'Plan number',cell:r=><a href="#" onClick={e=>{e.preventDefault();navigate(`/app/planning/${r.id}`)}}>{r.planNumber}</a>,sortable:true},{header:'Title',cell:r=>r.title},{header:'Department',cell:r=>r.department},{header:'Status',cell:r=><StatusBadge status={r.status}/>},{header:'Value',cell:r=>money((r.items||[]).reduce((s,i)=>s+i.estimatedAmount,0))}]}/>{!p.data.length&&<EmptyState title="No plans" message="Create or upload annual procurement plans to start governance."/>}</> }
export function NewPlanningPage(){ const [saving,setSaving]=useState(false); async function submit(e:React.FormEvent<HTMLFormElement>){ e.preventDefault(); setSaving(true); const f=new FormData(e.currentTarget); const r=await planningApi.createPlan({planNumber:f.get('planNumber'),title:f.get('title'),department:f.get('department'),createdBy:'procurement@lca.org.ls',financialYearId:f.get('financialYearId')||'00000000-0000-0000-0000-000000000000',items:[]}); setSaving(false); if(r.data?.id) navigate(`/app/planning/${r.data.id}`);} return <><PageHeader title="New Annual Procurement Plan" description="Creates the plan record; workflow remains configured in the platform."/><form className="card card-body" onSubmit={submit}><input className="form-control mb-2" name="planNumber" placeholder="Plan number" required/><input className="form-control mb-2" name="title" placeholder="Title" required/><input className="form-control mb-2" name="department" placeholder="Department" required/><input className="form-control mb-2" name="financialYearId" placeholder="Financial year id"/><button className="btn btn-primary" disabled={saving}>{saving?'Saving...':'Create plan'}</button></form></> }
export function PlanningDetailPage({id}:{id:string}){ const p=useLoad<Plan|null>(()=>planningApi.plan(id),null); if(p.loading) return <LoadingState />; if(!p.data) return <EmptyState title="Plan not found" message="The requested annual procurement plan does not exist."/>; return <><PageHeader title={p.data.title} description={p.data.planNumber} actions={<><button className="btn btn-outline-primary me-2" onClick={()=>planningApi.submitPlan(id).then(()=>location.reload())}>Submit</button><button className="btn btn-primary" onClick={()=>planningApi.approvePlan(id).then(()=>location.reload())}>Approve</button></>}/><p><StatusBadge status={p.data.status}/></p><DataTable rows={p.data.items||[]} columns={[{header:'Code',cell:r=>r.itemCode},{header:'Description',cell:r=>r.description},{header:'Quarter',cell:r=>r.plannedQuarter},{header:'Method',cell:r=>r.procurementMethod},{header:'Amount',cell:r=>money(r.estimatedAmount)}]}/></> }
export function BudgetsPage(){ const b=useLoad<Budget[]>(planningApi.budgets,[]); if(b.loading) return <LoadingState />; return <><PageHeader title="Budgets" description="Budget foundation for requisition validation."/><DataTable rows={b.data} searchable columns={[{header:'Department',cell:r=>r.department},{header:'Total',cell:r=>money(r.totalAmount)},{header:'Committed',cell:r=>money(r.committedAmount)},{header:'Available',cell:r=>money(r.availableAmount)}]}/></> }
export function CostCentresPage(){ const c=useLoad<CostCentre[]>(planningApi.costCentres,[]); if(c.loading) return <LoadingState />; return <><PageHeader title="Cost Centres" description="Reference data from the planning API."/><DataTable rows={c.data} searchable columns={[{header:'Code',cell:r=>r.code},{header:'Name',cell:r=>r.name},{header:'Department',cell:r=>r.department},{header:'Status',cell:r=><StatusBadge status={r.isActive?'Active':'Inactive'}/>}]}/></> }
export function ProcurementCategoriesPage(){ const c=useLoad<ProcurementCategory[]>(planningApi.categories,[]); if(c.loading) return <LoadingState />; return <><PageHeader title="Procurement Categories" description="Procurement classification reference data."/><DataTable rows={c.data} searchable columns={[{header:'Code',cell:r=>r.code},{header:'Name',cell:r=>r.name},{header:'Status',cell:r=><StatusBadge status={r.isActive?'Active':'Inactive'}/>}]}/></> }
