using Lca.EProcurement.Application;
using Lca.EProcurement.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lca.EProcurement.Api.Controllers;

[ApiController, Route("api/data-governance"), Authorize(Policy="DataGovernance.View")]
public class DataGovernanceController(IDataGovernanceApplicationService svc):ControllerBase{
 [HttpGet] public Task<GovernanceDashboardDto> Dashboard(CancellationToken ct)=>svc.GetDashboardAsync(ct);
 [HttpGet("policies")] public Task<List<DataGovernancePolicy>> Policies(CancellationToken ct)=>svc.GetPoliciesAsync(ct);
 [HttpPost("policies"),Authorize(Policy="DataGovernance.Manage")] public Task<DataGovernancePolicy> CreatePolicy(CreatePolicyDto d,CancellationToken ct)=>svc.CreatePolicyAsync(d,User.Identity?.Name??"api",ct);
 [HttpPut("policies/{id:guid}"),Authorize(Policy="DataGovernance.Manage")] public Task<DataGovernancePolicy?> UpdatePolicy(Guid id,CreatePolicyDto d,CancellationToken ct)=>svc.UpdatePolicyAsync(id,d,User.Identity?.Name??"api",ct);
 [HttpGet("retention-rules"),Authorize(Policy="DataRetention.View")] public Task<List<DataRetentionRule>> Rules(CancellationToken ct)=>svc.GetRetentionRulesAsync(ct);
 [HttpPost("retention-rules"),Authorize(Policy="DataRetention.Manage")] public Task<DataRetentionRule> CreateRule(CreateRetentionRuleDto d,CancellationToken ct)=>svc.CreateRetentionRuleAsync(d,User.Identity?.Name??"api",ct);
 [HttpPut("retention-rules/{id:guid}"),Authorize(Policy="DataRetention.Manage")] public Task<DataRetentionRule?> UpdateRule(Guid id,CreateRetentionRuleDto d,CancellationToken ct)=>svc.UpdateRetentionRuleAsync(id,d,User.Identity?.Name??"api",ct);
 [HttpGet("privacy-classifications"),Authorize(Policy="PrivacyClassification.View")] public Task<List<DataPrivacyClassification>> Privacy(CancellationToken ct)=>svc.GetPrivacyClassificationsAsync(ct);
 [HttpPost("privacy-classifications"),Authorize(Policy="PrivacyClassification.Manage")] public Task<DataPrivacyClassification> CreatePrivacy(CreatePrivacyClassificationDto d,CancellationToken ct)=>svc.CreatePrivacyClassificationAsync(d,User.Identity?.Name??"api",ct);
 [HttpPut("privacy-classifications/{id:guid}"),Authorize(Policy="PrivacyClassification.Manage")] public Task<DataPrivacyClassification?> UpdatePrivacy(Guid id,CreatePrivacyClassificationDto d,CancellationToken ct)=>svc.UpdatePrivacyClassificationAsync(id,d,User.Identity?.Name??"api",ct);
 [HttpGet("processing-logs")] public Task<List<DataProcessingLog>> Logs(CancellationToken ct)=>svc.GetProcessingLogsAsync(ct);
}
[ApiController,Route("api/migration"),Authorize(Policy="Migration.View")]
public class MigrationController(IMigrationApplicationService svc):ControllerBase{
 [HttpGet("templates")] public Task<List<MigrationTemplate>> Templates(CancellationToken ct)=>svc.GetTemplatesAsync(ct); [HttpGet("templates/{id:guid}")] public Task<MigrationTemplate?> Template(Guid id,CancellationToken ct)=>svc.GetTemplateAsync(id,ct); [HttpPost("templates"),Authorize(Policy="Migration.Upload")] public Task<MigrationTemplate> Create(MigrationTemplateDto d,CancellationToken ct)=>svc.CreateTemplateAsync(d,User.Identity?.Name??"api",ct); [HttpPut("templates/{id:guid}"),Authorize(Policy="Migration.Upload")] public Task<MigrationTemplate?> Update(Guid id,MigrationTemplateDto d,CancellationToken ct)=>svc.UpdateTemplateAsync(id,d,User.Identity?.Name??"api",ct); [HttpGet("templates/{id:guid}/sample.csv")] public async Task<FileContentResult> Sample(Guid id,CancellationToken ct)=>File(System.Text.Encoding.UTF8.GetBytes(await svc.GenerateSampleCsvAsync(id,ct)),"text/csv","sample.csv");
 [HttpGet("batches")] public Task<List<MigrationBatch>> Batches(CancellationToken ct)=>svc.GetBatchesAsync(ct); [HttpGet("batches/{id:guid}")] public Task<MigrationBatch?> Batch(Guid id,CancellationToken ct)=>svc.GetBatchAsync(id,ct); [HttpPost("batches/upload"),Authorize(Policy="Migration.Upload")] public Task<MigrationBatch> Upload(UploadMigrationBatchDto d,CancellationToken ct)=>svc.UploadBatchAsync(d,ct); [HttpPost("batches/{id:guid}/validate"),Authorize(Policy="Migration.Validate")] public Task<MigrationBatch?> Validate(Guid id,CancellationToken ct)=>svc.ValidateBatchAsync(id,ct); [HttpPost("batches/{id:guid}/import"),Authorize(Policy="Migration.Import")] public Task<MigrationBatch?> Import(Guid id,CancellationToken ct)=>svc.ImportBatchAsync(id,User.Identity?.Name??"api",ct); [HttpPost("batches/{id:guid}/cancel"),Authorize(Policy="Migration.Cancel")] public Task<MigrationBatch?> Cancel(Guid id,CancellationToken ct)=>svc.CancelBatchAsync(id,ct); [HttpGet("batches/{id:guid}/issues")] public Task<List<MigrationValidationIssue>> Issues(Guid id,CancellationToken ct)=>svc.GetIssuesAsync(id,ct); [HttpGet("batches/{id:guid}/items")] public Task<List<MigrationImportItem>> Items(Guid id,CancellationToken ct)=>svc.GetItemsAsync(id,ct);
}
[ApiController,Route("api/data-archive"),Authorize(Policy="DataArchive.View")]
public class DataArchivalController(IDataArchivalService svc):ControllerBase{[HttpGet("batches")] public Task<List<DataArchiveBatch>> B(CancellationToken ct)=>svc.GetArchiveBatchesAsync(ct); [HttpGet("batches/{id:guid}")] public Task<DataArchiveBatch?> One(Guid id,CancellationToken ct)=>svc.GetArchiveBatchAsync(id,ct); [HttpPost("preview")] public Task<ArchivePreviewDto> P(ArchiveBatchRequestDto d,CancellationToken ct)=>svc.PreviewArchiveAsync(d.EntityType,d.CutoffDate,ct); [HttpPost("batches"),Authorize(Policy="DataArchive.Manage")] public Task<DataArchiveBatch> C(ArchiveBatchRequestDto d,CancellationToken ct)=>svc.CreateArchiveBatchAsync(d.EntityType,d.CutoffDate,d.Reason,User.Identity?.Name??d.Actor,ct); [HttpPost("batches/{id:guid}/run"),Authorize(Policy="DataArchive.Manage")] public Task<DataArchiveBatch?> R(Guid id,CancellationToken ct)=>svc.RunArchiveBatchAsync(id,ct); [HttpPost("batches/{id:guid}/cancel"),Authorize(Policy="DataArchive.Manage")] public Task<IActionResult> Cancel(Guid id)=>Task.FromResult<IActionResult>(Ok(new{id,status="Cancelled"}));}
[ApiController,Route("api/data-quality"),Authorize(Policy="DataQuality.View")]
public class DataQualityController(IDataQualityApplicationService svc):ControllerBase{[HttpGet("checks")] public Task<List<DataQualityCheck>> Checks(CancellationToken ct)=>svc.GetChecksAsync(ct); [HttpPost("checks"),Authorize(Policy="DataQuality.Manage")] public Task<DataQualityCheck> Create(DataQualityCheck c,CancellationToken ct)=>svc.CreateCheckAsync(c,ct); [HttpPut("checks/{id:guid}"),Authorize(Policy="DataQuality.Manage")] public Task<DataQualityCheck?> Update(Guid id,DataQualityCheck c,CancellationToken ct)=>svc.UpdateCheckAsync(id,c,ct); [HttpPost("run"),Authorize(Policy="DataQuality.Run")] public Task<List<DataQualityResultDto>> Run(CancellationToken ct)=>svc.RunAsync(ct); [HttpGet("results")] public Task<List<DataQualityResultDto>> Results(CancellationToken ct)=>svc.GetResultsAsync(ct);}
[ApiController,Route("api/data-exports"),Authorize(Policy="DataExport.View")]
public class DataExportsController(IDataExportApplicationService svc):ControllerBase{[HttpPost,Authorize(Policy="DataExport.Request")] public Task<DataExportRequest> Req(DataExportRequestDto d,CancellationToken ct)=>svc.RequestExportAsync(d with { HasSensitivePermission = User.HasClaim("permission","DataExportSensitive") || User.IsInRole("Administrator") },ct); [HttpGet] public Task<List<DataExportRequest>> All(CancellationToken ct)=>svc.GetExportsAsync(ct); [HttpGet("{id:guid}")] public Task<DataExportRequest?> One(Guid id,CancellationToken ct)=>svc.GetExportAsync(id,ct); [HttpGet("{id:guid}/download"),Authorize(Policy="DataExport.Download")] public async Task<FileContentResult> Down(Guid id,CancellationToken ct)=>File(System.Text.Encoding.UTF8.GetBytes(await svc.DownloadAsync(id,User.Identity?.Name??"api",ct)),"text/csv","export.csv");}
