using System.Text;
using Lca.EProcurement.Application;
using Lca.EProcurement.Domain;
using Microsoft.AspNetCore.Mvc;

namespace Lca.EProcurement.Api.Controllers;

[ApiController]
[Route("api/reporting")]
public sealed class ReportingController(IReportingApplicationService reporting) : ControllerBase
{
    [HttpGet("executive-dashboard")] public Task<ReportingDashboardDto> Executive([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetExecutiveDashboardAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("procurement-activity")] public Task<ReportingDashboardDto> Activity([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetProcurementActivityAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("procurement-planning")] public Task<ReportingDashboardDto> Planning([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetProcurementPlanningAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("requisitions")] public Task<ReportingDashboardDto> Requisitions([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetRequisitionsAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("tenders")] public Task<ReportingDashboardDto> Tenders([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetTendersAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("supplier-performance")] public Task<ReportingDashboardDto> Suppliers([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetSupplierPerformanceAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("purchase-orders")] public Task<ReportingDashboardDto> PurchaseOrders([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetPurchaseOrdersAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("invoices")] public Task<ReportingDashboardDto> Invoices([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetInvoicesAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("po-invoice-analysis")] public Task<ReportingDashboardDto> PoInvoiceAnalysis([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetPoInvoiceAnalysisAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("compliance")] public Task<ReportingDashboardDto> Compliance([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetComplianceAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("audit")] public Task<ReportingDashboardDto> Audit([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetAuditAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("spend-analysis")] public Task<ReportingDashboardDto> Spend([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetSpendAnalysisAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("workflow-bottlenecks")] public Task<ReportingDashboardDto> Workflow([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetWorkflowBottlenecksAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("management-kpis")] public Task<ReportingDashboardDto> Kpis([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetManagementKpisAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("rfp-evidence")] public Task<ReportingDashboardDto> Evidence([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetRfpEvidenceAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("data-quality")] public Task<List<DataQualityIssueDto>> DataQuality([FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct) => reporting.GetDataQualityAsync(F(financialYearId, department, category, supplierId, from, to, status), ct);
    [HttpGet("subscriptions")] public Task<List<ReportSubscription>> Subscriptions(CancellationToken ct) => reporting.GetSubscriptionsAsync(ct);
    [HttpPost("subscriptions")] public Task<ReportSubscription> CreateSubscription([FromBody] ReportSubscriptionDto dto, CancellationToken ct) => reporting.CreateSubscriptionAsync(dto, ct);
    [HttpPut("subscriptions/{id:guid}")] public Task<ReportSubscription?> UpdateSubscription(Guid id, [FromBody] ReportSubscriptionDto dto, CancellationToken ct) => reporting.UpdateSubscriptionAsync(id, dto, ct);
    [HttpPost("subscriptions/{id:guid}/run-now")] public Task<ReportRunHistory?> RunSubscription(Guid id, CancellationToken ct) => reporting.RunSubscriptionNowAsync(id, ct);
    [HttpGet("{reportCode}/export.csv")]
    public async Task<IActionResult> Export(string reportCode, [FromQuery] Guid? financialYearId, [FromQuery] string? department, [FromQuery] string? category, [FromQuery] Guid? supplierId, [FromQuery] DateTimeOffset? from, [FromQuery] DateTimeOffset? to, [FromQuery] string? status, CancellationToken ct)
    {
        var csv = await reporting.ExportCsvAsync(reportCode, F(financialYearId, department, category, supplierId, from, to, status), ct);
        return csv is null ? NotFound() : File(Encoding.UTF8.GetBytes(csv), "text/csv", $"{reportCode}.csv");
    }
    static ReportingFilters F(Guid? financialYearId, string? department, string? category, Guid? supplierId, DateTimeOffset? from, DateTimeOffset? to, string? status) => new(financialYearId, department, category, supplierId, from, to, status);
}
