import { useEffect, useState } from "react";
import { PageHeader } from "../../components/ui/PageHeader";
import { DataTable } from "../../components/ui/DataTable";
import { MetricCard } from "../../components/ui/MetricCard";
import { Panel } from "../../components/ui/Panel";
import { EmptyState } from "../../components/ui/EmptyState";
import { LoadingState } from "../../components/ui/LoadingState";
import { invoicesApi, invoiceMatchingApi, returnsApi, type SupplierInvoice, type PurchaseOrderReturn, type ThreeWayMatch } from "../../services/invoicesApi";
import { navigate } from "../../app/routes";
function money(n = 0) { return new Intl.NumberFormat("en-LS", { style: "currency", currency: "LSL" }).format(n); }
function StatusBadge({ value }: { value: string }) { return <span className={`badge text-bg-${value.includes("Mismatch") || value.includes("Exception") || value.includes("Rejected") ? "danger" : value.includes("Approved") || value.includes("Matched") ? "success" : "secondary"}`}>{value}</span>; }
export function InvoiceListPage() { const [items,setItems]=useState<SupplierInvoice[]>(); useEffect(()=>{invoicesApi.list().then(r=>setItems(r.data));},[]); if(!items)return <LoadingState/>; return <><PageHeader title="Supplier invoices" description="Capture invoices, run three way matching, and manage finance review." actions={<button className="btn btn-primary" onClick={()=>navigate('/app/invoices/new')}>New invoice</button>}/><div className="row"><MetricCard label="Pending review" value={items.filter(x=>["Submitted","UnderReview"].includes(x.status)).length}/><MetricCard label="Matching exceptions" value={items.filter(x=>x.status==="Mismatch").length}/><MetricCard label="Approved for payment" value={items.filter(x=>x.status==="ApprovedForPayment").length}/></div><DataTable rows={items} columns={[{header:'Invoice number',cell:(x:any)=><a onClick={()=>navigate(`/app/invoices/${x.id}`)}>{x.invoiceNumber}</a>},{header:'Supplier invoice #',cell:(x:any)=>x.supplierInvoiceNumber}, {header:'Supplier',cell:(x:any)=>x.supplierName}, {header:'Invoice date',cell:(x:any)=>new Date(x.invoiceDate).toLocaleDateString()}, {header:'Total',cell:(x:any)=>money(x.totalAmount)}, {header:'Status',cell:(x:any)=><StatusBadge value={x.status}/>}]} /></>; }
export function InvoiceDetailPage({ id }: { id: string }) { const [inv,setInv]=useState<SupplierInvoice|null>(); const [match,setMatch]=useState<ThreeWayMatch|null>(); const load=()=>{invoicesApi.get(id).then(r=>setInv(r.data)); invoiceMatchingApi.get(id).then(r=>setMatch(r.data));}; useEffect(()=>{load();},[id]); if(inv===undefined)return <LoadingState/>; if(!inv)return <EmptyState title="Invoice not found" message="The requested invoice does not exist."/>; return <><PageHeader title={inv.invoiceNumber} description={`${inv.supplierName} · ${money(inv.totalAmount)}`} actions={<div className="btn-group"><button className="btn btn-outline-primary" onClick={()=>invoicesApi.submit(id).then(load)}>Submit</button><button className="btn btn-outline-warning" onClick={()=>invoicesApi.runMatch(id).then(load)}>Run match</button><button className="btn btn-outline-success" onClick={()=>invoicesApi.approve(id).then(load)}>Approve for payment</button><button className="btn btn-outline-danger" onClick={()=>invoicesApi.reject(id,'Rejected from finance review').then(load)}>Reject</button></div>}/><div className="row"><MetricCard label="Invoice total" value={money(inv.totalAmount)}/><MetricCard label="Status" value={inv.status}/><MetricCard label="Match status" value={match?.matchStatus || 'NotMatched'}/></div><Panel title="Invoice lines"><DataTable rows={inv.lines || []} columns={[{header:'#',cell:(x:any)=>x.itemNumber}, {header:'Description',cell:(x:any)=>x.description}, {header:'Qty',cell:(x:any)=>x.quantity}, {header:'Unit price',cell:(x:any)=>money(x.unitPrice)}, {header:'Total',cell:(x:any)=>money(x.totalAmount)}]} /></Panel><Panel title="Three way match result"><InvoiceMatchPanel match={match}/></Panel><Panel title="Attachments">{inv.attachments?.length ? inv.attachments.map(a=><div key={a.id}>{a.documentType}: {a.fileName}</div>) : <EmptyState title="No attachments" message="Upload supplier invoice documents through the invoice attachment API."/>}</Panel></>; }
function InvoiceMatchPanel({ match }: { match: ThreeWayMatch | null | undefined }) { if(!match)return <EmptyState title="No match run" message="Run matching to compare PO, goods receipt, returns, and invoice values."/>; return <><div className="row"><MetricCard label="PO amount" value={money(match.poAmount)}/><MetricCard label="Receipt amount" value={money(match.receiptAmount)}/><MetricCard label="Invoice amount" value={money(match.invoiceAmount)}/><MetricCard label="Variance" value={money(match.varianceAmount)}/></div><DataTable rows={match.results || []} columns={[{header:'Status',cell:(x:any)=><StatusBadge value={x.matchStatus}/>},{header:'PO qty',cell:(x:any)=>x.expectedQuantity}, {header:'Received qty',cell:(x:any)=>x.receivedQuantity}, {header:'Invoice qty',cell:(x:any)=>x.invoicedQuantity}, {header:'PO price',cell:(x:any)=>money(x.expectedUnitPrice)}, {header:'Invoice price',cell:(x:any)=>money(x.invoicedUnitPrice)}, {header:'Message',cell:(x:any)=>x.message}]} /></>; }
export function NewInvoicePage(){return <><PageHeader title="New supplier invoice" description="Create invoices from an issued purchase order using the API-backed PO action."/><EmptyState title="Select a purchase order" message="Open a purchase order and use Create invoice from PO. No fake data is displayed on this page."/></>}
export function InvoiceMatchingListPage(){const [items,setItems]=useState<ThreeWayMatch[]>(); useEffect(()=>{invoiceMatchingApi.list().then(r=>setItems(r.data));},[]); if(!items)return <LoadingState/>; return <><PageHeader title="Invoice matching" description="Three way matching across purchase orders, goods receipts and supplier invoices."/><DataTable rows={items} columns={[{header:'Invoice',cell:(x:any)=><a onClick={()=>navigate(`/app/invoice-matching/${x.supplierInvoiceId}`)}>{x.supplierInvoiceId}</a>},{header:'Status',cell:(x:any)=><StatusBadge value={x.matchStatus}/>},{header:'PO',cell:(x:any)=>money(x.poAmount)},{header:'Receipt',cell:(x:any)=>money(x.receiptAmount)},{header:'Invoice',cell:(x:any)=>money(x.invoiceAmount)},{header:'Variance',cell:(x:any)=>money(x.varianceAmount)}]}/></>}
export function InvoiceMatchingDetailPage({ invoiceId }: { invoiceId: string }){const [match,setMatch]=useState<ThreeWayMatch|null>(); useEffect(()=>{invoiceMatchingApi.get(invoiceId).then(r=>setMatch(r.data));},[invoiceId]); return <><PageHeader title="Invoice matching detail" description="PO versus receipt versus invoice comparison including returned quantity impact."/><InvoiceMatchPanel match={match}/></>}
export function PurchaseOrderReturnListPage(){const [items,setItems]=useState<PurchaseOrderReturn[]>(); useEffect(()=>{returnsApi.list().then(r=>setItems(r.data));},[]); if(!items)return <LoadingState/>; return <><PageHeader title="Purchase order returns" description="Manage returned goods and their impact on invoice matching." actions={<button className="btn btn-primary" onClick={()=>navigate('/app/purchase-order-returns/new')}>New return</button>}/><DataTable rows={items} columns={[{header:'Return number',cell:(x:any)=><a onClick={()=>navigate(`/app/purchase-order-returns/${x.id}`)}>{x.returnNumber}</a>},{header:'Supplier',cell:(x:any)=>x.supplierName},{header:'Reason',cell:(x:any)=>x.reason},{header:'Status',cell:(x:any)=><StatusBadge value={x.status}/>},{header:'Created',cell:(x:any)=>new Date(x.createdAt).toLocaleDateString()},{header:'Total returned',cell:(x:any)=>money((x.lines||[]).reduce((s:number,l:any)=>s+l.totalAmount,0))}]} /></>}
export function PurchaseOrderReturnDetailPage({ id }: { id: string }){const [ret,setRet]=useState<PurchaseOrderReturn|null>(); const load=()=>returnsApi.get(id).then(r=>setRet(r.data)); useEffect(()=>{load();},[id]); if(ret===undefined)return <LoadingState/>; if(!ret)return <EmptyState title="Return not found" message="The requested PO return does not exist."/>; return <><PageHeader title={ret.returnNumber} description={`${ret.supplierName} · ${ret.reason}`} actions={<div className="btn-group"><button className="btn btn-outline-primary" onClick={()=>returnsApi.submit(id).then(load)}>Submit</button><button className="btn btn-outline-success" onClick={()=>returnsApi.approve(id).then(load)}>Approve</button><button className="btn btn-outline-danger" onClick={()=>returnsApi.reject(id).then(load)}>Reject</button><button className="btn btn-outline-secondary" onClick={()=>returnsApi.complete(id).then(load)}>Complete</button></div>}/><Panel title="Return lines"><DataTable rows={ret.lines||[]} columns={[{header:'Description',cell:(x:any)=>x.description},{header:'Qty returned',cell:(x:any)=>x.returnedQuantity},{header:'Amount',cell:(x:any)=>money(x.totalAmount)}]} /></Panel></>}
export function NewPurchaseOrderReturnPage(){return <><PageHeader title="New purchase order return" description="Create a return linked to a purchase order using the returns API."/><EmptyState title="Select delivered PO lines" message="No fake data is used; create returns from delivered purchase order records."/></>}
