import { useEffect, useState } from "react";
import { PageHeader } from "../../components/ui/PageHeader";
import { Card } from "../../components/ui/Card";
function TitledCard({ title, children }: { title: string; children: React.ReactNode }) { return <Card><div className="card-header"><h3 className="card-title">{title}</h3></div><div className="card-body">{children}</div></Card>; }
import { EmptyState } from "../../components/ui/EmptyState";
import { LoadingState } from "../../components/ui/LoadingState";
import { getBackupPlans, getBackupRuns, getConfigurationValidation, getHealth, getPerformanceSummary, type BackupPlan, type BackupRun, type HealthResponse, type PerformanceSummary } from "../../services/operationsApi";
function Status({ value }: { value?: string }) { return <span className={`badge ${value === "Healthy" || value === "Completed" ? "text-bg-success" : value === "Failed" ? "text-bg-danger" : "text-bg-warning"}`}>{value || "Unknown"}</span>; }
export function OperationsDashboardPage() { const [health,setHealth]=useState<HealthResponse>(); const [perf,setPerf]=useState<PerformanceSummary>(); const [runs,setRuns]=useState<BackupRun[]>([]); const [error,setError]=useState(""); const load=()=>{getHealth("ready").then(r=>{setHealth(r.data); setError(r.error||"")}); getPerformanceSummary().then(r=>setPerf(r.data)); getBackupRuns().then(r=>setRuns(r.data));}; useEffect(load,[]); return <><PageHeader title="Operations" description="Production readiness, performance and support overview." actions={<button className="btn btn-outline-primary" onClick={load}>Retry</button>} />{!health?<LoadingState/>:<div className="row g-3"><div className="col-md-4"><TitledCard title="System status"><Status value={health.status}/><p className="text-muted mt-2">{health.environment}</p>{error&&<small className="text-danger">{error}</small>}</TitledCard></div><div className="col-md-4"><TitledCard title="Performance"><div>{perf?.slowRequestCount ?? 0} slow requests</div><div>{perf?.errorCount ?? 0} recent errors</div><div>P95 {perf?.p95DurationMs ?? 0} ms</div></TitledCard></div><div className="col-md-4"><TitledCard title="Last backup"><Status value={runs[0]?.status}/><div className="text-muted">{runs[0]?.backupReference || "No backup evidence yet"}</div></TitledCard></div></div>}</>; }
export function OperationsHealthPage() { const [items,setItems]=useState<HealthResponse[]>([]); const load=()=>Promise.all(["live","ready","database","storage","integrations"].map(getHealth)).then(r=>setItems(r.map(x=>x.data))); useEffect(()=>{load()},[]); return <><PageHeader title="Health checks" description="Readiness and liveness endpoints." actions={<button className="btn btn-outline-primary" onClick={load}>Retry</button>}/>{items.length===0?<LoadingState/>:<div className="row g-3">{items.map((h,i)=><div className="col-md-6" key={i}><TitledCard title={`${h.environment || "Environment"} ${i+1}`}><Status value={h.status}/><ul className="mt-2">{h.checks.map(c=><li key={c.name}>{c.name}: <Status value={c.status}/></li>)}</ul></TitledCard></div>)}</div>}</>; }
export function OperationsPerformancePage(){ const [summary,setSummary]=useState<PerformanceSummary>(); useEffect(()=>{getPerformanceSummary().then(r=>setSummary(r.data))},[]); return <><PageHeader title="Performance baseline" description="API response-time monitoring." />{!summary?<LoadingState/>:<TitledCard title="Summary"><pre>{JSON.stringify(summary,null,2)}</pre></TitledCard>}</> }
export function OperationsBackupsPage(){ const [plans,setPlans]=useState<BackupPlan[]>([]); const [runs,setRuns]=useState<BackupRun[]>([]); useEffect(()=>{getBackupPlans().then(r=>setPlans(r.data)); getBackupRuns().then(r=>setRuns(r.data));},[]); return <><PageHeader title="Backup readiness" description="Simulated backup and restore evidence; configure real backups in SQL Server/infrastructure."/><div className="row g-3"><div className="col-md-6"><TitledCard title="Plans">{plans.length?plans.map(p=><div key={p.id}>{p.code} - {p.name} <Status value={p.isEnabled?"Healthy":"NotConfigured"}/></div>):<EmptyState title="No plans" message="Create a backup plan through the API."/>}</TitledCard></div><div className="col-md-6"><TitledCard title="Runs">{runs.length?runs.map(r=><div key={r.id}>{r.backupReference} <Status value={r.status}/></div>):<EmptyState title="No runs" message="Run a simulation to record backup evidence."/>}</TitledCard></div></div></> }
export function OperationsLogsPage(){ return <><PageHeader title="Operations logs" description="Recent API failures and operational audit events are available through performance and audit APIs."/><EmptyState title="Use Audit Explorer" message="Structured request logs are emitted by the backend logger with correlation IDs."/></> }
export function OperationsChecklistPage(){ const [cfg,setCfg]=useState<{status:string;warnings:string[];errors:string[];recommendations:string[]}>(); useEffect(()=>{getConfigurationValidation().then(r=>setCfg(r.data))},[]); return <><PageHeader title="Production readiness checklist" description="Configuration validation and recommendations."/>{cfg&&<TitledCard title="Configuration"><Status value={cfg.status}/><h6>Errors</h6><ul>{cfg.errors.map(x=><li key={x}>{x}</li>)}</ul><h6>Warnings</h6><ul>{cfg.warnings.map(x=><li key={x}>{x}</li>)}</ul><h6>Recommendations</h6><ul>{cfg.recommendations.map(x=><li key={x}>{x}</li>)}</ul></TitledCard>}</> }
