import { useEffect, useState } from "react";
import { Button } from "../../components/ui/Button";
import { DataTable } from "../../components/ui/DataTable";
import { EmptyState } from "../../components/ui/EmptyState";
import { LoadingState } from "../../components/ui/LoadingState";
import { MetricCard } from "../../components/ui/MetricCard";
import { PageHeader } from "../../components/ui/PageHeader";
import { Panel } from "../../components/ui/Panel";
import { StatusBadge } from "../../components/ui/Badge";
import { Timeline } from "../../components/ui/Timeline";
import { getAwards } from "../../services/awardsApi";
import { acknowledgePurchaseOrder, cancelPurchaseOrder, closePurchaseOrder, createPurchaseOrderFromAward, getPurchaseOrder, getPurchaseOrders, issuePurchaseOrder, recordPurchaseOrderDelivery } from "../../services/purchaseOrdersApi";
import { navigate } from "../../app/routes";

export function PurchaseOrderListPage(){const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string>();useEffect(()=>{getPurchaseOrders().then(r=>{setItems(r.data);setError(r.error);setLoading(false);});},[]);if(loading)return <LoadingState/>;return <><PageHeader title="Purchase Orders" description="Generate purchase orders from approved awards and track issue, acknowledgement, delivery, goods receipt, closure and cancellation." actions={<Button onClick={()=>navigate('/app/purchase-orders/new')}>New PO</Button>}/>{error&&<div className="alert alert-warning">{error}</div>}<div className="row g-3 mb-3"><div className="col-md-2"><MetricCard label="Open Purchase Orders" value={items.filter(x=>!['Closed','Cancelled'].includes(x.status)).length}/></div><div className="col-md-2"><MetricCard label="Issued Today" value={items.filter(x=>x.issueDate&&new Date(x.issueDate).toDateString()===new Date().toDateString()).length}/></div><div className="col-md-2"><MetricCard label="Awaiting Delivery" value={items.filter(x=>['Issued','Acknowledged'].includes(x.status)).length}/></div><div className="col-md-2"><MetricCard label="Partially Delivered" value={items.filter(x=>x.status==='PartiallyDelivered').length}/></div><div className="col-md-2"><MetricCard label="Completed" value={items.filter(x=>x.status==='Closed').length}/></div><div className="col-md-2"><MetricCard label="Cancelled" value={items.filter(x=>x.status==='Cancelled').length}/></div></div>{items.length===0?<EmptyState title="No purchase orders" message="Generate a purchase order from an approved award."/>:<DataTable searchable rows={items} columns={[{header:'PO number',cell:x=><button className="btn btn-link p-0" onClick={()=>navigate(`/app/purchase-orders/${x.id}`)}>{x.purchaseOrderNumber}</button>},{header:'Supplier',cell:x=>x.supplierName},{header:'Total',cell:x=>Number(x.totalAmount).toLocaleString()},{header:'Status',cell:x=><StatusBadge status={x.status}/>},{header:'Expected delivery',cell:x=>new Date(x.expectedDeliveryDate).toLocaleDateString()}]}/>}</>}
export function NewPurchaseOrderPage(){const[awards,setAwards]=useState<any[]>([]);const[selected,setSelected]=useState('');const[error,setError]=useState<string>();useEffect(()=>{getAwards().then(r=>{const approved=(r.data??[]).filter((x:any)=>['Approved','Published','ConvertedToPurchaseOrder'].includes(x.status));setAwards(approved);setSelected(approved[0]?.id??'');});},[]);async function create(){const r=await createPurchaseOrderFromAward(selected); if(r.error)setError(r.error); else navigate(`/app/purchase-orders/${r.data.purchaseOrder.id}`);}return <><PageHeader title="New Purchase Order" description="Select an approved award to copy supplier, award total, and award line items into a governed PO."/><Panel title="Approved award">{error&&<div className="alert alert-danger">{error}</div>}{awards.length===0?<EmptyState title="No approved awards" message="Approve or publish an award before generating a purchase order."/>:<><select className="form-select" value={selected} onChange={e=>setSelected(e.target.value)}>{awards.map((a:any)=><option key={a.id} value={a.id}>{a.awardNumber} — {a.supplierName} ({Number(a.awardAmount).toLocaleString()})</option>)}</select><Button className="mt-3" onClick={create}>Generate PO</Button></>}</Panel></>}
export function PurchaseOrderDetailPage({id}:{id:string}){const[d,setD]=useState<any>();const[error,setError]=useState<string>();async function load(){const r=await getPurchaseOrder(id);setD(r.data);setError(r.error);}useEffect(()=>{load();},[id]);if(!d)return <LoadingState/>;const po=d.purchaseOrder;const act=async(fn:any)=>{const r=await fn(id); if(r.error)setError(r.error); await load();};return <><PageHeader title={po.purchaseOrderNumber} description={`${po.supplierName} · award ${d.award.awardNumber}`} actions={<><Button variant="secondary" onClick={()=>navigate('/app/purchase-orders')}>Back</Button><Button onClick={()=>act(issuePurchaseOrder)}>Issue</Button><Button onClick={()=>act(acknowledgePurchaseOrder)}>Acknowledge</Button><Button onClick={()=>act((x:string)=>recordPurchaseOrderDelivery(x,d.lines))}>Record Delivery</Button><Button onClick={()=>act(closePurchaseOrder)}>Close</Button><Button variant="secondary" onClick={()=>act(cancelPurchaseOrder)}>Cancel</Button></>}/>{error&&<div className="alert alert-warning">{error}</div>}<div className="row g-3"><div className="col-lg-8"><div className="row g-3"><div className="col-md-4"><MetricCard label="Total" value={Number(po.totalAmount).toLocaleString()} /></div><div className="col-md-4"><MetricCard label="Status" value={po.status}/></div><div className="col-md-4"><MetricCard label="Workflow" value={d.workflowInstance?.currentNodeCode??po.status}/></div></div><Panel title="PO lines"><DataTable compact rows={d.lines as any[]} columns={[{header:'Item',cell:l=>l.itemNumber},{header:'Description',cell:l=>l.description},{header:'Qty',cell:l=>l.quantity},{header:'Delivered',cell:l=>l.deliveredQuantity},{header:'Outstanding',cell:l=>l.outstandingQuantity},{header:'Total',cell:l=>Number(l.total).toLocaleString()}]}/></Panel><Panel title="Goods receipts">{d.goodsReceipts.length===0?<EmptyState title="No goods receipts" message="Recording delivery prepares a goods receipt."/>:<DataTable compact rows={d.goodsReceipts as any[]} columns={[{header:'Receipt',cell:g=>g.receiptNumber},{header:'Received by',cell:g=>g.receivedBy},{header:'Status',cell:g=>g.status},{header:'Received',cell:g=>new Date(g.receivedAt).toLocaleString()}]}/>}</Panel></div><div className="col-lg-4"><Panel title="Delivery history">{d.deliveries.length===0?<EmptyState title="No deliveries" message="Partial and full deliveries appear here."/>:<Timeline items={d.deliveries.map((x:any)=>({title:x.deliveredBy,description:x.notes,date:x.deliveryDate}))}/>}</Panel><Panel title="PO history"><Timeline items={[...d.history.map((x:any)=>({title:x.eventType,description:x.details,date:x.occurredAt})),...d.auditTimeline.map((x:any)=>({title:x.eventType,description:x.details,date:x.occurredAt}))]}/></Panel></div></div></>}
