using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lca.EProcurement.EntityFrameworkCore.Migrations;

public partial class ProcurementPlanningBudget : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "CostCentres", columns: table => new { Id = table.Column<Guid>(nullable: false), Code = table.Column<string>(maxLength: 64, nullable: false), Name = table.Column<string>(maxLength: 256, nullable: false), Department = table.Column<string>(maxLength: 128, nullable: false), IsActive = table.Column<bool>(nullable: false) }, constraints: table => table.PrimaryKey("PK_CostCentres", x => x.Id));
        migrationBuilder.CreateTable(name: "FinancialYears", columns: table => new { Id = table.Column<Guid>(nullable: false), Code = table.Column<string>(maxLength: 32, nullable: false), StartDate = table.Column<DateTimeOffset>(nullable: false), EndDate = table.Column<DateTimeOffset>(nullable: false), IsActive = table.Column<bool>(nullable: false) }, constraints: table => table.PrimaryKey("PK_FinancialYears", x => x.Id));
        migrationBuilder.CreateTable(name: "ProcurementCategories", columns: table => new { Id = table.Column<Guid>(nullable: false), Code = table.Column<string>(maxLength: 64, nullable: false), Name = table.Column<string>(maxLength: 256, nullable: false), IsActive = table.Column<bool>(nullable: false) }, constraints: table => table.PrimaryKey("PK_ProcurementCategories", x => x.Id));
        migrationBuilder.CreateTable(name: "AnnualProcurementPlans", columns: table => new { Id = table.Column<Guid>(nullable: false), PlanNumber = table.Column<string>(maxLength: 64, nullable: false), Title = table.Column<string>(maxLength: 256, nullable: false), FinancialYearId = table.Column<Guid>(nullable: false), Department = table.Column<string>(maxLength: 128, nullable: false), Status = table.Column<string>(maxLength: 64, nullable: false), CreatedBy = table.Column<string>(maxLength: 256, nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false), SubmittedAt = table.Column<DateTimeOffset>(nullable: true), ApprovedAt = table.Column<DateTimeOffset>(nullable: true) }, constraints: table => table.PrimaryKey("PK_AnnualProcurementPlans", x => x.Id));
        migrationBuilder.CreateTable(name: "Budgets", columns: table => new { Id = table.Column<Guid>(nullable: false), FinancialYearId = table.Column<Guid>(nullable: false), Department = table.Column<string>(maxLength: 128, nullable: false), TotalAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false), CommittedAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false), AvailableAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false) }, constraints: table => table.PrimaryKey("PK_Budgets", x => x.Id));
        migrationBuilder.CreateTable(name: "BudgetLines", columns: table => new { Id = table.Column<Guid>(nullable: false), BudgetId = table.Column<Guid>(nullable: false), CostCentreId = table.Column<Guid>(nullable: false), ProcurementCategoryId = table.Column<Guid>(nullable: false), AllocatedAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false), CommittedAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false), AvailableAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false) }, constraints: table => { table.PrimaryKey("PK_BudgetLines", x => x.Id); table.ForeignKey("FK_BudgetLines_Budgets_BudgetId", x => x.BudgetId, "Budgets", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "ProcurementPlanItems", columns: table => new { Id = table.Column<Guid>(nullable: false), AnnualProcurementPlanId = table.Column<Guid>(nullable: false), ItemCode = table.Column<string>(maxLength: 64, nullable: false), Description = table.Column<string>(maxLength: 1000, nullable: false), ProcurementCategoryId = table.Column<Guid>(nullable: false), EstimatedAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false), PlannedQuarter = table.Column<string>(maxLength: 32, nullable: false), ProcurementMethod = table.Column<string>(maxLength: 128, nullable: false), Status = table.Column<string>(maxLength: 64, nullable: false) }, constraints: table => { table.PrimaryKey("PK_ProcurementPlanItems", x => x.Id); table.ForeignKey("FK_ProcurementPlanItems_AnnualProcurementPlans_AnnualProcurementPlanId", x => x.AnnualProcurementPlanId, "AnnualProcurementPlans", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateIndex("IX_CostCentres_Code", "CostCentres", "Code", unique: true); migrationBuilder.CreateIndex("IX_FinancialYears_Code", "FinancialYears", "Code", unique: true); migrationBuilder.CreateIndex("IX_ProcurementCategories_Code", "ProcurementCategories", "Code", unique: true); migrationBuilder.CreateIndex("IX_AnnualProcurementPlans_PlanNumber", "AnnualProcurementPlans", "PlanNumber", unique: true); migrationBuilder.CreateIndex("IX_BudgetLines_BudgetId", "BudgetLines", "BudgetId"); migrationBuilder.CreateIndex("IX_ProcurementPlanItems_AnnualProcurementPlanId", "ProcurementPlanItems", "AnnualProcurementPlanId");
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropTable("BudgetLines"); migrationBuilder.DropTable("ProcurementPlanItems"); migrationBuilder.DropTable("CostCentres"); migrationBuilder.DropTable("FinancialYears"); migrationBuilder.DropTable("ProcurementCategories"); migrationBuilder.DropTable("Budgets"); migrationBuilder.DropTable("AnnualProcurementPlans"); }
}
