using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lca.EProcurement.EntityFrameworkCore.Migrations;

public partial class DataGovernanceTables : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"IF OBJECT_ID(N'[dbo].[DataGovernancePolicies]', N'U') IS NULL CREATE TABLE [dbo].[DataGovernancePolicies]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_DataGovernancePolicies] PRIMARY KEY,[Code] nvarchar(128) NOT NULL,[Name] nvarchar(256) NOT NULL,[Description] nvarchar(2000) NOT NULL,[PolicyType] nvarchar(64) NOT NULL,[EntityType] nvarchar(128) NOT NULL,[IsActive] bit NOT NULL,[EffectiveFrom] datetimeoffset NOT NULL,[EffectiveTo] datetimeoffset NULL,[CreatedBy] nvarchar(256) NOT NULL,[CreatedAt] datetimeoffset NOT NULL,[UpdatedBy] nvarchar(256) NULL,[UpdatedAt] datetimeoffset NULL);
IF OBJECT_ID(N'[dbo].[DataRetentionRules]', N'U') IS NULL CREATE TABLE [dbo].[DataRetentionRules]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_DataRetentionRules] PRIMARY KEY,[Code] nvarchar(128) NOT NULL,[Name] nvarchar(256) NOT NULL,[EntityType] nvarchar(128) NOT NULL,[RetentionPeriodDays] int NOT NULL,[ArchiveAfterDays] int NOT NULL,[DeleteAfterDays] int NULL,[LegalHoldSupported] bit NOT NULL,[RequiresApprovalForDeletion] bit NOT NULL,[IsActive] bit NOT NULL,[CreatedBy] nvarchar(256) NOT NULL,[CreatedAt] datetimeoffset NOT NULL,[UpdatedBy] nvarchar(256) NULL,[UpdatedAt] datetimeoffset NULL);
IF OBJECT_ID(N'[dbo].[DataArchiveBatches]', N'U') IS NULL CREATE TABLE [dbo].[DataArchiveBatches]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_DataArchiveBatches] PRIMARY KEY,[BatchNumber] nvarchar(64) NOT NULL,[EntityType] nvarchar(128) NOT NULL,[Reason] nvarchar(1000) NOT NULL,[Status] nvarchar(64) NOT NULL,[CreatedBy] nvarchar(256) NOT NULL,[CreatedAt] datetimeoffset NOT NULL,[StartedAt] datetimeoffset NULL,[CompletedAt] datetimeoffset NULL,[TotalItems] int NOT NULL,[ArchivedItems] int NOT NULL,[FailedItems] int NOT NULL);
IF OBJECT_ID(N'[dbo].[DataArchiveItems]', N'U') IS NULL CREATE TABLE [dbo].[DataArchiveItems]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_DataArchiveItems] PRIMARY KEY,[BatchId] uniqueidentifier NOT NULL,[EntityType] nvarchar(128) NOT NULL,[EntityId] uniqueidentifier NOT NULL,[EntityReference] nvarchar(256) NOT NULL,[OriginalStatus] nvarchar(64) NOT NULL,[ArchiveStatus] nvarchar(64) NOT NULL,[ArchiveReason] nvarchar(1000) NOT NULL,[ArchivedAt] datetimeoffset NULL,[ErrorMessage] nvarchar(2000) NULL,CONSTRAINT [FK_DataArchiveItems_DataArchiveBatches_BatchId] FOREIGN KEY([BatchId]) REFERENCES [dbo].[DataArchiveBatches]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[MigrationBatches]', N'U') IS NULL CREATE TABLE [dbo].[MigrationBatches]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_MigrationBatches] PRIMARY KEY,[BatchNumber] nvarchar(64) NOT NULL,[SourceName] nvarchar(256) NOT NULL,[EntityType] nvarchar(128) NOT NULL,[FileName] nvarchar(512) NOT NULL,[UploadedBy] nvarchar(256) NOT NULL,[UploadedAt] datetimeoffset NOT NULL,[Status] nvarchar(64) NOT NULL,[StartedAt] datetimeoffset NULL,[CompletedAt] datetimeoffset NULL,[TotalRows] int NOT NULL,[SuccessfulRows] int NOT NULL,[FailedRows] int NOT NULL,[ValidationSummaryJson] nvarchar(max) NOT NULL,[Notes] nvarchar(2000) NULL);
IF OBJECT_ID(N'[dbo].[MigrationTemplates]', N'U') IS NULL CREATE TABLE [dbo].[MigrationTemplates]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_MigrationTemplates] PRIMARY KEY,[Code] nvarchar(128) NOT NULL,[Name] nvarchar(256) NOT NULL,[EntityType] nvarchar(128) NOT NULL,[Description] nvarchar(2000) NOT NULL,[FileFormat] nvarchar(64) NOT NULL,[IsActive] bit NOT NULL,[CreatedBy] nvarchar(256) NOT NULL,[CreatedAt] datetimeoffset NOT NULL);
IF OBJECT_ID(N'[dbo].[MigrationTemplateFields]', N'U') IS NULL CREATE TABLE [dbo].[MigrationTemplateFields]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_MigrationTemplateFields] PRIMARY KEY,[TemplateId] uniqueidentifier NOT NULL,[FieldName] nvarchar(128) NOT NULL,[DisplayName] nvarchar(256) NOT NULL,[DataType] nvarchar(64) NOT NULL,[IsRequired] bit NOT NULL,[MaxLength] int NULL,[LookupType] nvarchar(128) NULL,[ExampleValue] nvarchar(512) NULL,[ValidationRule] nvarchar(512) NULL,[DisplayOrder] int NOT NULL,CONSTRAINT [FK_MigrationTemplateFields_MigrationTemplates_TemplateId] FOREIGN KEY([TemplateId]) REFERENCES [dbo].[MigrationTemplates]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[MigrationImportItems]', N'U') IS NULL CREATE TABLE [dbo].[MigrationImportItems]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_MigrationImportItems] PRIMARY KEY,[BatchId] uniqueidentifier NOT NULL,[RowNumber] int NOT NULL,[ExternalReference] nvarchar(256) NULL,[EntityType] nvarchar(128) NOT NULL,[EntityId] uniqueidentifier NULL,[RawDataJson] nvarchar(max) NOT NULL,[MappedDataJson] nvarchar(max) NOT NULL,[Status] nvarchar(64) NOT NULL,[ErrorMessage] nvarchar(2000) NULL,[ImportedAt] datetimeoffset NULL,CONSTRAINT [FK_MigrationImportItems_MigrationBatches_BatchId] FOREIGN KEY([BatchId]) REFERENCES [dbo].[MigrationBatches]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[MigrationValidationIssues]', N'U') IS NULL CREATE TABLE [dbo].[MigrationValidationIssues]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_MigrationValidationIssues] PRIMARY KEY,[BatchId] uniqueidentifier NOT NULL,[ImportItemId] uniqueidentifier NULL,[RowNumber] int NULL,[FieldName] nvarchar(128) NULL,[Severity] nvarchar(64) NOT NULL,[Message] nvarchar(2000) NOT NULL,[CreatedAt] datetimeoffset NOT NULL,CONSTRAINT [FK_MigrationValidationIssues_MigrationBatches_BatchId] FOREIGN KEY([BatchId]) REFERENCES [dbo].[MigrationBatches]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[DataQualityChecks]', N'U') IS NULL CREATE TABLE [dbo].[DataQualityChecks]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_DataQualityChecks] PRIMARY KEY,[Code] nvarchar(128) NOT NULL,[Name] nvarchar(256) NOT NULL,[EntityType] nvarchar(128) NOT NULL,[Description] nvarchar(2000) NOT NULL,[RuleExpression] nvarchar(1000) NOT NULL,[Severity] nvarchar(64) NOT NULL,[IsActive] bit NOT NULL,[CreatedAt] datetimeoffset NOT NULL);
IF OBJECT_ID(N'[dbo].[DataPrivacyClassifications]', N'U') IS NULL CREATE TABLE [dbo].[DataPrivacyClassifications]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_DataPrivacyClassifications] PRIMARY KEY,[EntityType] nvarchar(128) NOT NULL,[FieldName] nvarchar(128) NOT NULL,[Classification] nvarchar(64) NOT NULL,[Reason] nvarchar(1000) NOT NULL,[IsSensitive] bit NOT NULL,[MaskInUi] bit NOT NULL,[MaskInExports] bit NOT NULL,[CreatedAt] datetimeoffset NOT NULL,[CreatedBy] nvarchar(256) NOT NULL);
IF OBJECT_ID(N'[dbo].[DataExportRequests]', N'U') IS NULL CREATE TABLE [dbo].[DataExportRequests]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_DataExportRequests] PRIMARY KEY,[RequestNumber] nvarchar(64) NOT NULL,[EntityType] nvarchar(128) NOT NULL,[RequestedBy] nvarchar(256) NOT NULL,[RequestedAt] datetimeoffset NOT NULL,[Status] nvarchar(64) NOT NULL,[Format] nvarchar(64) NOT NULL,[IncludeSensitiveData] bit NOT NULL,[Reason] nvarchar(1000) NOT NULL,[CompletedAt] datetimeoffset NULL,[DownloadReference] nvarchar(512) NULL,[ErrorMessage] nvarchar(2000) NULL);
IF OBJECT_ID(N'[dbo].[DataProcessingLogs]', N'U') IS NULL CREATE TABLE [dbo].[DataProcessingLogs]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_DataProcessingLogs] PRIMARY KEY,[OperationType] nvarchar(64) NOT NULL,[EntityType] nvarchar(128) NOT NULL,[EntityId] uniqueidentifier NULL,[Actor] nvarchar(256) NOT NULL,[Purpose] nvarchar(512) NOT NULL,[Details] nvarchar(2000) NOT NULL,[OccurredAt] datetimeoffset NOT NULL);
IF OBJECT_ID(N'[dbo].[DataGovernancePolicies]', N'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DataGovernancePolicies_Code' AND object_id=OBJECT_ID(N'[dbo].[DataGovernancePolicies]')) CREATE UNIQUE INDEX [IX_DataGovernancePolicies_Code] ON [dbo].[DataGovernancePolicies]([Code]);
IF OBJECT_ID(N'[dbo].[DataRetentionRules]', N'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DataRetentionRules_Code' AND object_id=OBJECT_ID(N'[dbo].[DataRetentionRules]')) CREATE UNIQUE INDEX [IX_DataRetentionRules_Code] ON [dbo].[DataRetentionRules]([Code]);
IF OBJECT_ID(N'[dbo].[MigrationTemplates]', N'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_MigrationTemplates_Code' AND object_id=OBJECT_ID(N'[dbo].[MigrationTemplates]')) CREATE UNIQUE INDEX [IX_MigrationTemplates_Code] ON [dbo].[MigrationTemplates]([Code]);
IF OBJECT_ID(N'[dbo].[DataQualityChecks]', N'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DataQualityChecks_Code' AND object_id=OBJECT_ID(N'[dbo].[DataQualityChecks]')) CREATE UNIQUE INDEX [IX_DataQualityChecks_Code] ON [dbo].[DataQualityChecks]([Code]);
IF OBJECT_ID(N'[dbo].[DataPrivacyClassifications]', N'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DataPrivacyClassifications_EntityType_FieldName' AND object_id=OBJECT_ID(N'[dbo].[DataPrivacyClassifications]')) CREATE UNIQUE INDEX [IX_DataPrivacyClassifications_EntityType_FieldName] ON [dbo].[DataPrivacyClassifications]([EntityType],[FieldName]);
IF OBJECT_ID(N'[dbo].[DataExportRequests]', N'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DataExportRequests_RequestNumber' AND object_id=OBJECT_ID(N'[dbo].[DataExportRequests]')) CREATE UNIQUE INDEX [IX_DataExportRequests_RequestNumber] ON [dbo].[DataExportRequests]([RequestNumber]);
");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"DROP TABLE IF EXISTS [dbo].[DataProcessingLogs];DROP TABLE IF EXISTS [dbo].[DataExportRequests];DROP TABLE IF EXISTS [dbo].[DataPrivacyClassifications];DROP TABLE IF EXISTS [dbo].[DataQualityChecks];DROP TABLE IF EXISTS [dbo].[MigrationValidationIssues];DROP TABLE IF EXISTS [dbo].[MigrationImportItems];DROP TABLE IF EXISTS [dbo].[MigrationTemplateFields];DROP TABLE IF EXISTS [dbo].[MigrationTemplates];DROP TABLE IF EXISTS [dbo].[MigrationBatches];DROP TABLE IF EXISTS [dbo].[DataArchiveItems];DROP TABLE IF EXISTS [dbo].[DataArchiveBatches];DROP TABLE IF EXISTS [dbo].[DataRetentionRules];DROP TABLE IF EXISTS [dbo].[DataGovernancePolicies];");
    }
}
