using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lca.EProcurement.EntityFrameworkCore.Migrations
{
    public partial class OperationalReadinessPhase1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(name: "ApiPerformanceSamples", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), CorrelationId = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), Path = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: false), Method = table.Column<string>(type: "nvarchar(16)", maxLength: 16, nullable: false), StatusCode = table.Column<int>(type: "int", nullable: false), DurationMs = table.Column<long>(type: "bigint", nullable: false), UserId = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true), OccurredAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false) }, constraints: table => table.PrimaryKey("PK_ApiPerformanceSamples", x => x.Id));
            migrationBuilder.CreateTable(name: "BackupPlans", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Code = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), Name = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), BackupType = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), ScheduleDescription = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: false), StorageLocation = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: false), IsEnabled = table.Column<bool>(type: "bit", nullable: false), RetentionDays = table.Column<int>(type: "int", nullable: false), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), CreatedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false) }, constraints: table => table.PrimaryKey("PK_BackupPlans", x => x.Id));
            migrationBuilder.CreateTable(name: "BackupRuns", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), BackupPlanId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), StartedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), CompletedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), Status = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), BackupReference = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: false), SizeBytes = table.Column<long>(type: "bigint", nullable: true), ErrorMessage = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true), TriggeredBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false) }, constraints: table => table.PrimaryKey("PK_BackupRuns", x => x.Id));
            migrationBuilder.CreateTable(name: "RestoreRuns", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), BackupRunId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), StartedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), CompletedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), Status = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), RestoreTarget = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: false), ErrorMessage = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true), TriggeredBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false) }, constraints: table => table.PrimaryKey("PK_RestoreRuns", x => x.Id));
            migrationBuilder.CreateTable(name: "SupportCases", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), CaseNumber = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), Title = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), Description = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: false), Severity = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), Status = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), Module = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), ReportedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), AssignedTo = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), ResolvedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), ResolutionNotes = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: true), CorrelationId = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true) }, constraints: table => table.PrimaryKey("PK_SupportCases", x => x.Id));
            migrationBuilder.CreateIndex(name: "IX_ApiPerformanceSamples_OccurredAt", table: "ApiPerformanceSamples", column: "OccurredAt");
            migrationBuilder.CreateIndex(name: "IX_ApiPerformanceSamples_StatusCode", table: "ApiPerformanceSamples", column: "StatusCode");
            migrationBuilder.CreateIndex(name: "IX_BackupPlans_Code", table: "BackupPlans", column: "Code", unique: true);
            migrationBuilder.CreateIndex(name: "IX_BackupRuns_StartedAt", table: "BackupRuns", column: "StartedAt");
            migrationBuilder.CreateIndex(name: "IX_RestoreRuns_StartedAt", table: "RestoreRuns", column: "StartedAt");
            migrationBuilder.CreateIndex(name: "IX_SupportCases_CaseNumber", table: "SupportCases", column: "CaseNumber", unique: true);
            migrationBuilder.CreateIndex(name: "IX_SupportCases_Status", table: "SupportCases", column: "Status");
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "RestoreRuns"); migrationBuilder.DropTable(name: "BackupRuns"); migrationBuilder.DropTable(name: "BackupPlans"); migrationBuilder.DropTable(name: "SupportCases"); migrationBuilder.DropTable(name: "ApiPerformanceSamples");
        }
    }
}
