using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lca.EProcurement.EntityFrameworkCore.Migrations;

public partial class BidSubmission : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "BidSubmissions", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), SubmissionNumber = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), TenderId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), SupplierId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Status = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), SubmissionDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), SubmittedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), SubmittedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), WithdrawnAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), LockedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), OpenedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), CurrentVersion = table.Column<int>(type: "int", nullable: false) }, constraints: table => table.PrimaryKey("PK_BidSubmissions", x => x.Id));
        migrationBuilder.CreateIndex(name: "IX_BidSubmissions_SubmissionNumber", table: "BidSubmissions", column: "SubmissionNumber", unique: true);
        migrationBuilder.CreateTable(name: "BidSubmissionItems", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), BidSubmissionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), TenderLotId = table.Column<Guid>(type: "uniqueidentifier", nullable: true), Description = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false), Quantity = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false), UnitPrice = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false), Total = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false), Notes = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true) }, constraints: table => { table.PrimaryKey("PK_BidSubmissionItems", x => x.Id); table.ForeignKey("FK_BidSubmissionItems_BidSubmissions_BidSubmissionId", x => x.BidSubmissionId, "BidSubmissions", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "BidSubmissionDocuments", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), BidSubmissionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), DocumentType = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), Filename = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), StorageReference = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: false), UploadedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), UploadedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), Version = table.Column<int>(type: "int", nullable: false) }, constraints: table => { table.PrimaryKey("PK_BidSubmissionDocuments", x => x.Id); table.ForeignKey("FK_BidSubmissionDocuments_BidSubmissions_BidSubmissionId", x => x.BidSubmissionId, "BidSubmissions", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "BidSubmissionHistories", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), BidSubmissionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), EventType = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), Actor = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), Details = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: false), OccurredAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false) }, constraints: table => { table.PrimaryKey("PK_BidSubmissionHistories", x => x.Id); table.ForeignKey("FK_BidSubmissionHistories_BidSubmissions_BidSubmissionId", x => x.BidSubmissionId, "BidSubmissions", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "BidSubmissionDeclarations", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), BidSubmissionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), DeclarationType = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), Accepted = table.Column<bool>(type: "bit", nullable: false), AcceptedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), AcceptedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false) }, constraints: table => { table.PrimaryKey("PK_BidSubmissionDeclarations", x => x.Id); table.ForeignKey("FK_BidSubmissionDeclarations_BidSubmissions_BidSubmissionId", x => x.BidSubmissionId, "BidSubmissions", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "BidSubmissionVersions", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), BidSubmissionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), VersionNumber = table.Column<int>(type: "int", nullable: false), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), CreatedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false) }, constraints: table => { table.PrimaryKey("PK_BidSubmissionVersions", x => x.Id); table.ForeignKey("FK_BidSubmissionVersions_BidSubmissions_BidSubmissionId", x => x.BidSubmissionId, "BidSubmissions", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "BidSubmissionStatusHistories", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), BidSubmissionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), FromStatus = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), ToStatus = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), Actor = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), ChangedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), Notes = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false) }, constraints: table => { table.PrimaryKey("PK_BidSubmissionStatusHistories", x => x.Id); table.ForeignKey("FK_BidSubmissionStatusHistories_BidSubmissions_BidSubmissionId", x => x.BidSubmissionId, "BidSubmissions", "Id", onDelete: ReferentialAction.Cascade); });
    }
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable("BidSubmissionDeclarations"); migrationBuilder.DropTable("BidSubmissionDocuments"); migrationBuilder.DropTable("BidSubmissionHistories"); migrationBuilder.DropTable("BidSubmissionItems"); migrationBuilder.DropTable("BidSubmissionStatusHistories"); migrationBuilder.DropTable("BidSubmissionVersions"); migrationBuilder.DropTable("BidSubmissions");
    }
}
