using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lca.EProcurement.EntityFrameworkCore.Migrations;

public partial class RequisitionManagement : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "Requisitions", columns: table => new { Id = table.Column<Guid>(nullable: false), RequisitionNumber = table.Column<string>(maxLength: 64, nullable: false), Title = table.Column<string>(maxLength: 256, nullable: false), Description = table.Column<string>(maxLength: 2000, nullable: false), Department = table.Column<string>(maxLength: 128, nullable: false), CostCentreId = table.Column<Guid>(nullable: false), FinancialYearId = table.Column<Guid>(nullable: false), RequestedBy = table.Column<string>(maxLength: 256, nullable: false), RequiredDate = table.Column<DateTimeOffset>(nullable: false), Priority = table.Column<string>(maxLength: 64, nullable: false), EstimatedTotal = table.Column<decimal>(type: "decimal(18,2)", nullable: false), Status = table.Column<string>(maxLength: 64, nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false), SubmittedAt = table.Column<DateTimeOffset>(nullable: true), ApprovedAt = table.Column<DateTimeOffset>(nullable: true), RejectedAt = table.Column<DateTimeOffset>(nullable: true) }, constraints: table => table.PrimaryKey("PK_Requisitions", x => x.Id));
        migrationBuilder.CreateTable(name: "BudgetCommitments", columns: table => new { Id = table.Column<Guid>(nullable: false), RequisitionId = table.Column<Guid>(nullable: false), BudgetId = table.Column<Guid>(nullable: false), BudgetLineId = table.Column<Guid>(nullable: false), FinancialYearId = table.Column<Guid>(nullable: false), CostCentreId = table.Column<Guid>(nullable: false), ProcurementCategoryId = table.Column<Guid>(nullable: false), Amount = table.Column<decimal>(type: "decimal(18,2)", nullable: false), CommittedBy = table.Column<string>(maxLength: 256, nullable: false), CommittedAt = table.Column<DateTimeOffset>(nullable: false), Reference = table.Column<string>(maxLength: 128, nullable: false) }, constraints: table => table.PrimaryKey("PK_BudgetCommitments", x => x.Id));
        migrationBuilder.CreateTable(name: "RequisitionItems", columns: table => new { Id = table.Column<Guid>(nullable: false), RequisitionId = table.Column<Guid>(nullable: false), Description = table.Column<string>(maxLength: 1000, nullable: false), Quantity = table.Column<decimal>(type: "decimal(18,2)", nullable: false), UnitOfMeasure = table.Column<string>(maxLength: 32, nullable: false), EstimatedUnitPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: false), EstimatedTotal = table.Column<decimal>(type: "decimal(18,2)", nullable: false), ProcurementCategoryId = table.Column<Guid>(nullable: false), ProcurementPlanItemId = table.Column<Guid>(nullable: true) }, constraints: table => { table.PrimaryKey("PK_RequisitionItems", x => x.Id); table.ForeignKey("FK_RequisitionItems_Requisitions_RequisitionId", x => x.RequisitionId, "Requisitions", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "RequisitionAttachments", columns: table => new { Id = table.Column<Guid>(nullable: false), RequisitionId = table.Column<Guid>(nullable: false), FileName = table.Column<string>(maxLength: 256, nullable: false), ContentType = table.Column<string>(maxLength: 128, nullable: false), UploadedBy = table.Column<string>(maxLength: 256, nullable: false), UploadedAt = table.Column<DateTimeOffset>(nullable: false), StorageReference = table.Column<string>(maxLength: 512, nullable: false) }, constraints: table => { table.PrimaryKey("PK_RequisitionAttachments", x => x.Id); table.ForeignKey("FK_RequisitionAttachments_Requisitions_RequisitionId", x => x.RequisitionId, "Requisitions", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "RequisitionStatusHistories", columns: table => new { Id = table.Column<Guid>(nullable: false), RequisitionId = table.Column<Guid>(nullable: false), FromStatus = table.Column<string>(maxLength: 64, nullable: false), ToStatus = table.Column<string>(maxLength: 64, nullable: false), Actor = table.Column<string>(maxLength: 256, nullable: false), Notes = table.Column<string>(maxLength: 1000, nullable: false), ChangedAt = table.Column<DateTimeOffset>(nullable: false) }, constraints: table => { table.PrimaryKey("PK_RequisitionStatusHistories", x => x.Id); table.ForeignKey("FK_RequisitionStatusHistories_Requisitions_RequisitionId", x => x.RequisitionId, "Requisitions", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateIndex("IX_Requisitions_RequisitionNumber", "Requisitions", "RequisitionNumber", unique: true); migrationBuilder.CreateIndex("IX_BudgetCommitments_RequisitionId", "BudgetCommitments", "RequisitionId"); migrationBuilder.CreateIndex("IX_RequisitionItems_RequisitionId", "RequisitionItems", "RequisitionId"); migrationBuilder.CreateIndex("IX_RequisitionAttachments_RequisitionId", "RequisitionAttachments", "RequisitionId"); migrationBuilder.CreateIndex("IX_RequisitionStatusHistories_RequisitionId", "RequisitionStatusHistories", "RequisitionId");
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropTable("BudgetCommitments"); migrationBuilder.DropTable("RequisitionAttachments"); migrationBuilder.DropTable("RequisitionItems"); migrationBuilder.DropTable("RequisitionStatusHistories"); migrationBuilder.DropTable("Requisitions"); }
}
