using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lca.EProcurement.EntityFrameworkCore.Migrations
{
    public partial class ReportingEvidencePhase1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(name: "KpiDefinitions", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Code = table.Column<string>(type: "nvarchar(max)", nullable: false), Name = table.Column<string>(type: "nvarchar(max)", nullable: false), Description = table.Column<string>(type: "nvarchar(max)", nullable: false), Category = table.Column<string>(type: "nvarchar(max)", nullable: false), CalculationType = table.Column<string>(type: "nvarchar(max)", nullable: false), TargetValue = table.Column<decimal>(type: "decimal(18,2)", nullable: true), Unit = table.Column<string>(type: "nvarchar(max)", nullable: false), Status = table.Column<string>(type: "nvarchar(max)", nullable: false), IsActive = table.Column<bool>(type: "bit", nullable: false) }, constraints: table => table.PrimaryKey("PK_KpiDefinitions", x => x.Id));
            migrationBuilder.CreateTable(name: "KpiCalculationResults", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), KpiCode = table.Column<string>(type: "nvarchar(max)", nullable: false), Value = table.Column<decimal>(type: "decimal(18,2)", nullable: false), TargetValue = table.Column<decimal>(type: "decimal(18,2)", nullable: true), Status = table.Column<string>(type: "nvarchar(max)", nullable: false), CalculatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), FilterJson = table.Column<string>(type: "nvarchar(max)", nullable: false), Explanation = table.Column<string>(type: "nvarchar(max)", nullable: false) }, constraints: table => table.PrimaryKey("PK_KpiCalculationResults", x => x.Id));
            migrationBuilder.CreateTable(name: "RequirementEvidenceItems", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Code = table.Column<string>(type: "nvarchar(max)", nullable: false), Source = table.Column<string>(type: "nvarchar(max)", nullable: false), RequirementArea = table.Column<string>(type: "nvarchar(max)", nullable: false), RequirementText = table.Column<string>(type: "nvarchar(max)", nullable: false), ResponseCommitment = table.Column<string>(type: "nvarchar(max)", nullable: false), SystemFeature = table.Column<string>(type: "nvarchar(max)", nullable: false), Module = table.Column<string>(type: "nvarchar(max)", nullable: false), Route = table.Column<string>(type: "nvarchar(max)", nullable: false), ApiEndpoint = table.Column<string>(type: "nvarchar(max)", nullable: false), Status = table.Column<string>(type: "nvarchar(max)", nullable: false), EvidenceNotes = table.Column<string>(type: "nvarchar(max)", nullable: false), LastVerifiedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false) }, constraints: table => table.PrimaryKey("PK_RequirementEvidenceItems", x => x.Id));
            migrationBuilder.CreateTable(name: "ReportSubscriptions", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), ReportCode = table.Column<string>(type: "nvarchar(max)", nullable: false), UserId = table.Column<string>(type: "nvarchar(max)", nullable: false), Frequency = table.Column<string>(type: "nvarchar(max)", nullable: false), Format = table.Column<string>(type: "nvarchar(max)", nullable: false), FiltersJson = table.Column<string>(type: "nvarchar(max)", nullable: false), IsActive = table.Column<bool>(type: "bit", nullable: false), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false) }, constraints: table => table.PrimaryKey("PK_ReportSubscriptions", x => x.Id));
            migrationBuilder.CreateTable(name: "ReportRunHistories", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), ReportCode = table.Column<string>(type: "nvarchar(max)", nullable: false), UserId = table.Column<string>(type: "nvarchar(max)", nullable: false), StartedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), CompletedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), Status = table.Column<string>(type: "nvarchar(max)", nullable: false), OutputReference = table.Column<string>(type: "nvarchar(max)", nullable: true), ErrorMessage = table.Column<string>(type: "nvarchar(max)", nullable: true) }, constraints: table => table.PrimaryKey("PK_ReportRunHistories", x => x.Id));
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ReportRunHistories"); migrationBuilder.DropTable(name: "ReportSubscriptions"); migrationBuilder.DropTable(name: "RequirementEvidenceItems"); migrationBuilder.DropTable(name: "KpiCalculationResults"); migrationBuilder.DropTable(name: "KpiDefinitions");
        }
    }
}
