using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace Lca.EProcurement.EntityFrameworkCore.Migrations;
public partial class ProcurementFinancialCompletionPhase1 : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
IF OBJECT_ID(N'[dbo].[PurchaseOrderReturns]', N'U') IS NULL CREATE TABLE [dbo].[PurchaseOrderReturns]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_PurchaseOrderReturns] PRIMARY KEY,[ReturnNumber] nvarchar(64) NOT NULL UNIQUE,[PurchaseOrderId] uniqueidentifier NOT NULL,[SupplierId] uniqueidentifier NOT NULL,[SupplierName] nvarchar(256) NOT NULL,[Reason] nvarchar(1000) NOT NULL,[Status] nvarchar(64) NOT NULL,[CreatedBy] nvarchar(256) NOT NULL,[CreatedAt] datetimeoffset NOT NULL,[SubmittedAt] datetimeoffset NULL,[ApprovedBy] nvarchar(256) NULL,[ApprovedAt] datetimeoffset NULL,[CompletedAt] datetimeoffset NULL,[CancelledAt] datetimeoffset NULL,[Notes] nvarchar(2000) NULL,CONSTRAINT [FK_PurchaseOrderReturns_PurchaseOrders] FOREIGN KEY([PurchaseOrderId]) REFERENCES [dbo].[PurchaseOrders]([Id]));
IF OBJECT_ID(N'[dbo].[PurchaseOrderReturnLines]', N'U') IS NULL CREATE TABLE [dbo].[PurchaseOrderReturnLines]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_PurchaseOrderReturnLines] PRIMARY KEY,[PurchaseOrderReturnId] uniqueidentifier NOT NULL,[PurchaseOrderLineId] uniqueidentifier NOT NULL,[ItemNumber] int NOT NULL,[Description] nvarchar(1000) NOT NULL,[ReturnedQuantity] decimal(18,2) NOT NULL,[UnitPrice] decimal(18,2) NOT NULL,[TotalAmount] decimal(18,2) NOT NULL,[Reason] nvarchar(1000) NOT NULL,[ConditionNotes] nvarchar(2000) NULL,CONSTRAINT [FK_PurchaseOrderReturnLines_Returns] FOREIGN KEY([PurchaseOrderReturnId]) REFERENCES [dbo].[PurchaseOrderReturns]([Id]) ON DELETE CASCADE,CONSTRAINT [FK_PurchaseOrderReturnLines_POLines] FOREIGN KEY([PurchaseOrderLineId]) REFERENCES [dbo].[PurchaseOrderLines]([Id]));
IF OBJECT_ID(N'[dbo].[SupplierInvoices]', N'U') IS NULL CREATE TABLE [dbo].[SupplierInvoices]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_SupplierInvoices] PRIMARY KEY,[InvoiceNumber] nvarchar(64) NOT NULL UNIQUE,[SupplierInvoiceNumber] nvarchar(128) NOT NULL,[PurchaseOrderId] uniqueidentifier NOT NULL,[GoodsReceiptId] uniqueidentifier NULL,[SupplierId] uniqueidentifier NOT NULL,[SupplierName] nvarchar(256) NOT NULL,[InvoiceDate] datetimeoffset NOT NULL,[ReceivedDate] datetimeoffset NOT NULL,[Currency] nvarchar(8) NOT NULL,[SubtotalAmount] decimal(18,2) NOT NULL,[TaxAmount] decimal(18,2) NOT NULL,[TotalAmount] decimal(18,2) NOT NULL,[Status] nvarchar(64) NOT NULL,[SubmittedBy] nvarchar(256) NOT NULL,[SubmittedAt] datetimeoffset NULL,[ReviewedBy] nvarchar(256) NULL,[ReviewedAt] datetimeoffset NULL,[ApprovedForPaymentAt] datetimeoffset NULL,[RejectedAt] datetimeoffset NULL,[RejectionReason] nvarchar(2000) NULL,[Notes] nvarchar(2000) NULL,CONSTRAINT [FK_SupplierInvoices_PurchaseOrders] FOREIGN KEY([PurchaseOrderId]) REFERENCES [dbo].[PurchaseOrders]([Id]));
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SupplierInvoices_Supplier_Duplicate') CREATE UNIQUE INDEX [IX_SupplierInvoices_Supplier_Duplicate] ON [dbo].[SupplierInvoices]([SupplierId],[SupplierInvoiceNumber]);
IF OBJECT_ID(N'[dbo].[SupplierInvoiceLines]', N'U') IS NULL CREATE TABLE [dbo].[SupplierInvoiceLines]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_SupplierInvoiceLines] PRIMARY KEY,[SupplierInvoiceId] uniqueidentifier NOT NULL,[PurchaseOrderLineId] uniqueidentifier NULL,[GoodsReceiptId] uniqueidentifier NULL,[ItemNumber] int NOT NULL,[Description] nvarchar(1000) NOT NULL,[Quantity] decimal(18,2) NOT NULL,[UnitPrice] decimal(18,2) NOT NULL,[TaxAmount] decimal(18,2) NOT NULL,[TotalAmount] decimal(18,2) NOT NULL,CONSTRAINT [FK_SupplierInvoiceLines_Invoices] FOREIGN KEY([SupplierInvoiceId]) REFERENCES [dbo].[SupplierInvoices]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[InvoiceAttachments]', N'U') IS NULL CREATE TABLE [dbo].[InvoiceAttachments]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_InvoiceAttachments] PRIMARY KEY,[SupplierInvoiceId] uniqueidentifier NOT NULL,[DocumentType] nvarchar(128) NOT NULL,[FileName] nvarchar(256) NOT NULL,[StorageReference] nvarchar(1000) NOT NULL,[UploadedBy] nvarchar(256) NOT NULL,[UploadedAt] datetimeoffset NOT NULL,CONSTRAINT [FK_InvoiceAttachments_Invoices] FOREIGN KEY([SupplierInvoiceId]) REFERENCES [dbo].[SupplierInvoices]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[InvoiceStatusHistories]', N'U') IS NULL CREATE TABLE [dbo].[InvoiceStatusHistories]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_InvoiceStatusHistories] PRIMARY KEY,[SupplierInvoiceId] uniqueidentifier NOT NULL,[FromStatus] nvarchar(64) NOT NULL,[ToStatus] nvarchar(64) NOT NULL,[Actor] nvarchar(256) NOT NULL,[ChangedAt] datetimeoffset NOT NULL,[Notes] nvarchar(2000) NOT NULL,CONSTRAINT [FK_InvoiceStatusHistories_Invoices] FOREIGN KEY([SupplierInvoiceId]) REFERENCES [dbo].[SupplierInvoices]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[InvoiceReviews]', N'U') IS NULL CREATE TABLE [dbo].[InvoiceReviews]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_InvoiceReviews] PRIMARY KEY,[SupplierInvoiceId] uniqueidentifier NOT NULL,[ReviewerUserId] nvarchar(256) NOT NULL,[ReviewerName] nvarchar(256) NOT NULL,[Decision] nvarchar(64) NOT NULL,[Comments] nvarchar(2000) NOT NULL,[ReviewedAt] datetimeoffset NOT NULL,CONSTRAINT [FK_InvoiceReviews_Invoices] FOREIGN KEY([SupplierInvoiceId]) REFERENCES [dbo].[SupplierInvoices]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[PaymentPreparations]', N'U') IS NULL CREATE TABLE [dbo].[PaymentPreparations]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_PaymentPreparations] PRIMARY KEY,[SupplierInvoiceId] uniqueidentifier NOT NULL,[PaymentReference] nvarchar(128) NOT NULL,[Status] nvarchar(64) NOT NULL,[PreparedBy] nvarchar(256) NOT NULL,[PreparedAt] datetimeoffset NOT NULL,[SentToFinanceAt] datetimeoffset NULL,[ErrorMessage] nvarchar(2000) NULL,CONSTRAINT [FK_PaymentPreparations_Invoices] FOREIGN KEY([SupplierInvoiceId]) REFERENCES [dbo].[SupplierInvoices]([Id]));
IF OBJECT_ID(N'[dbo].[ThreeWayMatches]', N'U') IS NULL CREATE TABLE [dbo].[ThreeWayMatches]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_ThreeWayMatches] PRIMARY KEY,[SupplierInvoiceId] uniqueidentifier NOT NULL,[PurchaseOrderId] uniqueidentifier NOT NULL,[GoodsReceiptId] uniqueidentifier NULL,[MatchStatus] nvarchar(64) NOT NULL,[PoAmount] decimal(18,2) NOT NULL,[ReceiptAmount] decimal(18,2) NOT NULL,[InvoiceAmount] decimal(18,2) NOT NULL,[VarianceAmount] decimal(18,2) NOT NULL,[VariancePercentage] decimal(18,2) NOT NULL,[QuantityMatched] bit NOT NULL,[PriceMatched] bit NOT NULL,[ReceiptMatched] bit NOT NULL,[TaxMatched] bit NOT NULL,[ResultJson] nvarchar(max) NOT NULL,[CreatedAt] datetimeoffset NOT NULL,[CreatedBy] nvarchar(256) NOT NULL);
IF OBJECT_ID(N'[dbo].[InvoiceMatchingResults]', N'U') IS NULL CREATE TABLE [dbo].[InvoiceMatchingResults]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_InvoiceMatchingResults] PRIMARY KEY,[ThreeWayMatchId] uniqueidentifier NOT NULL,[SupplierInvoiceLineId] uniqueidentifier NOT NULL,[PurchaseOrderLineId] uniqueidentifier NULL,[MatchStatus] nvarchar(64) NOT NULL,[ExpectedQuantity] decimal(18,2) NOT NULL,[InvoicedQuantity] decimal(18,2) NOT NULL,[ReceivedQuantity] decimal(18,2) NOT NULL,[ExpectedUnitPrice] decimal(18,2) NOT NULL,[InvoicedUnitPrice] decimal(18,2) NOT NULL,[VarianceAmount] decimal(18,2) NOT NULL,[Message] nvarchar(2000) NOT NULL,CONSTRAINT [FK_InvoiceMatchingResults_ThreeWayMatches] FOREIGN KEY([ThreeWayMatchId]) REFERENCES [dbo].[ThreeWayMatches]([Id]) ON DELETE CASCADE);
");
    }
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"DROP TABLE IF EXISTS [dbo].[InvoiceMatchingResults];DROP TABLE IF EXISTS [dbo].[ThreeWayMatches];DROP TABLE IF EXISTS [dbo].[PaymentPreparations];DROP TABLE IF EXISTS [dbo].[InvoiceReviews];DROP TABLE IF EXISTS [dbo].[InvoiceStatusHistories];DROP TABLE IF EXISTS [dbo].[InvoiceAttachments];DROP TABLE IF EXISTS [dbo].[SupplierInvoiceLines];DROP TABLE IF EXISTS [dbo].[SupplierInvoices];DROP TABLE IF EXISTS [dbo].[PurchaseOrderReturnLines];DROP TABLE IF EXISTS [dbo].[PurchaseOrderReturns];");
    }
}
