using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace Lca.EProcurement.EntityFrameworkCore.Migrations;
public partial class EvaluationManagement : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
IF OBJECT_ID(N'[dbo].[EvaluationSessions]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationSessions]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationSessions] PRIMARY KEY,[SessionNumber] nvarchar(64) NOT NULL UNIQUE,[TenderId] uniqueidentifier NOT NULL,[BidOpeningSessionId] uniqueidentifier NOT NULL,[Title] nvarchar(256) NOT NULL,[Status] nvarchar(64) NOT NULL,[CurrentStage] nvarchar(64) NOT NULL,[CreatedBy] nvarchar(256) NOT NULL,[CreatedAt] datetimeoffset NOT NULL,[Chairperson] nvarchar(256) NOT NULL,[Notes] nvarchar(2000) NULL,[StartedAt] datetimeoffset NULL,[CompletedAt] datetimeoffset NULL);
IF OBJECT_ID(N'[dbo].[EvaluationCommitteeMembers]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationCommitteeMembers]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationCommitteeMembers] PRIMARY KEY,[EvaluationSessionId] uniqueidentifier NOT NULL,[Name] nvarchar(256) NOT NULL,[Email] nvarchar(256) NOT NULL,[Role] nvarchar(128) NOT NULL,[IsChairperson] bit NOT NULL,[HasAcceptedDeclaration] bit NOT NULL,[DeclarationAcceptedAt] datetimeoffset NULL,CONSTRAINT [FK_EvaluationCommitteeMembers_EvaluationSessions] FOREIGN KEY([EvaluationSessionId]) REFERENCES [dbo].[EvaluationSessions]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[EvaluationTemplates]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationTemplates]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationTemplates] PRIMARY KEY,[Code] nvarchar(128) NOT NULL UNIQUE,[Name] nvarchar(256) NOT NULL,[Description] nvarchar(2000) NOT NULL,[TenderType] nvarchar(64) NOT NULL,[TotalWeight] decimal(18,2) NOT NULL,[Status] nvarchar(64) NOT NULL,[CreatedBy] nvarchar(256) NOT NULL,[CreatedAt] datetimeoffset NOT NULL,[PublishedAt] datetimeoffset NULL,[PublishedBy] nvarchar(256) NULL);
IF OBJECT_ID(N'[dbo].[EvaluationCriteria]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationCriteria]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationCriteria] PRIMARY KEY,[Code] nvarchar(128) NOT NULL UNIQUE,[Name] nvarchar(256) NOT NULL,[Description] nvarchar(2000) NOT NULL,[Stage] nvarchar(64) NOT NULL,[Weight] decimal(18,2) NOT NULL,[MaximumScore] decimal(18,2) NOT NULL,[MinimumPassingScore] decimal(18,2) NOT NULL,[DisplayOrder] int NOT NULL);
IF OBJECT_ID(N'[dbo].[EvaluationTemplateCriteria]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationTemplateCriteria]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationTemplateCriteria] PRIMARY KEY,[EvaluationTemplateId] uniqueidentifier NOT NULL,[EvaluationCriterionId] uniqueidentifier NOT NULL,[DisplayOrder] int NOT NULL,[IsMandatory] bit NOT NULL,CONSTRAINT [FK_EvaluationTemplateCriteria_EvaluationTemplates] FOREIGN KEY([EvaluationTemplateId]) REFERENCES [dbo].[EvaluationTemplates]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[EvaluationSubmissions]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationSubmissions]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationSubmissions] PRIMARY KEY,[EvaluationSessionId] uniqueidentifier NOT NULL,[BidSubmissionId] uniqueidentifier NOT NULL,[SupplierId] uniqueidentifier NOT NULL,[SupplierName] nvarchar(256) NOT NULL,[SubmissionNumber] nvarchar(64) NOT NULL,[Status] nvarchar(64) NOT NULL,[AdministrativePassed] bit NOT NULL,[TechnicalScore] decimal(18,2) NOT NULL,[FinancialScore] decimal(18,2) NOT NULL,[TotalScore] decimal(18,2) NOT NULL,[Rank] int NOT NULL,[Notes] nvarchar(2000) NULL,CONSTRAINT [FK_EvaluationSubmissions_EvaluationSessions] FOREIGN KEY([EvaluationSessionId]) REFERENCES [dbo].[EvaluationSessions]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[EvaluationScores]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationScores]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationScores] PRIMARY KEY,[EvaluationSessionId] uniqueidentifier NOT NULL,[EvaluationSubmissionId] uniqueidentifier NOT NULL,[EvaluationCriterionId] uniqueidentifier NOT NULL,[EvaluatorEmail] nvarchar(256) NOT NULL,[Stage] nvarchar(64) NOT NULL,[Score] decimal(18,2) NOT NULL,[Comments] nvarchar(2000) NOT NULL,[ScoredAt] datetimeoffset NOT NULL,CONSTRAINT [FK_EvaluationScores_EvaluationSessions] FOREIGN KEY([EvaluationSessionId]) REFERENCES [dbo].[EvaluationSessions]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[EvaluationConsensusScores]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationConsensusScores]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationConsensusScores] PRIMARY KEY,[EvaluationSessionId] uniqueidentifier NOT NULL,[EvaluationSubmissionId] uniqueidentifier NOT NULL,[EvaluationCriterionId] uniqueidentifier NOT NULL,[Stage] nvarchar(64) NOT NULL,[ConsensusScore] decimal(18,2) NOT NULL,[ConsensusComments] nvarchar(2000) NOT NULL,[RecordedBy] nvarchar(256) NOT NULL,[RecordedAt] datetimeoffset NOT NULL,CONSTRAINT [FK_EvaluationConsensusScores_EvaluationSessions] FOREIGN KEY([EvaluationSessionId]) REFERENCES [dbo].[EvaluationSessions]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[EvaluationDeclarations]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationDeclarations]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationDeclarations] PRIMARY KEY,[EvaluationSessionId] uniqueidentifier NOT NULL,[EvaluatorEmail] nvarchar(256) NOT NULL,[DeclarationType] nvarchar(128) NOT NULL,[Accepted] bit NOT NULL,[AcceptedAt] datetimeoffset NOT NULL,[Notes] nvarchar(2000) NULL,CONSTRAINT [FK_EvaluationDeclarations_EvaluationSessions] FOREIGN KEY([EvaluationSessionId]) REFERENCES [dbo].[EvaluationSessions]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[EvaluationRecommendations]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationRecommendations]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationRecommendations] PRIMARY KEY,[EvaluationSessionId] uniqueidentifier NOT NULL,[RecommendedBidSubmissionId] uniqueidentifier NOT NULL,[SupplierId] uniqueidentifier NOT NULL,[SupplierName] nvarchar(256) NOT NULL,[RecommendationText] nvarchar(4000) NOT NULL,[RecommendedAmount] decimal(18,2) NOT NULL,[RecommendedBy] nvarchar(256) NOT NULL,[RecommendedAt] datetimeoffset NOT NULL,[Status] nvarchar(64) NOT NULL,CONSTRAINT [FK_EvaluationRecommendations_EvaluationSessions] FOREIGN KEY([EvaluationSessionId]) REFERENCES [dbo].[EvaluationSessions]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[EvaluationReports]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationReports]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationReports] PRIMARY KEY,[EvaluationSessionId] uniqueidentifier NOT NULL,[ReportNumber] nvarchar(64) NOT NULL,[GeneratedAt] datetimeoffset NOT NULL,[GeneratedBy] nvarchar(256) NOT NULL,[SummaryJson] nvarchar(max) NOT NULL,CONSTRAINT [FK_EvaluationReports_EvaluationSessions] FOREIGN KEY([EvaluationSessionId]) REFERENCES [dbo].[EvaluationSessions]([Id]) ON DELETE CASCADE);
IF OBJECT_ID(N'[dbo].[EvaluationHistories]', N'U') IS NULL CREATE TABLE [dbo].[EvaluationHistories]([Id] uniqueidentifier NOT NULL CONSTRAINT [PK_EvaluationHistories] PRIMARY KEY,[EvaluationSessionId] uniqueidentifier NOT NULL,[EventType] nvarchar(128) NOT NULL,[Actor] nvarchar(256) NOT NULL,[Details] nvarchar(4000) NOT NULL,[OccurredAt] datetimeoffset NOT NULL,CONSTRAINT [FK_EvaluationHistories_EvaluationSessions] FOREIGN KEY([EvaluationSessionId]) REFERENCES [dbo].[EvaluationSessions]([Id]) ON DELETE CASCADE);
");
    }
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"DROP TABLE IF EXISTS [dbo].[EvaluationHistories];DROP TABLE IF EXISTS [dbo].[EvaluationReports];DROP TABLE IF EXISTS [dbo].[EvaluationRecommendations];DROP TABLE IF EXISTS [dbo].[EvaluationDeclarations];DROP TABLE IF EXISTS [dbo].[EvaluationConsensusScores];DROP TABLE IF EXISTS [dbo].[EvaluationScores];DROP TABLE IF EXISTS [dbo].[EvaluationSubmissions];DROP TABLE IF EXISTS [dbo].[EvaluationTemplateCriteria];DROP TABLE IF EXISTS [dbo].[EvaluationCriteria];DROP TABLE IF EXISTS [dbo].[EvaluationTemplates];DROP TABLE IF EXISTS [dbo].[EvaluationCommitteeMembers];DROP TABLE IF EXISTS [dbo].[EvaluationSessions];");
    }
}
