using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lca.EProcurement.EntityFrameworkCore.Migrations;

public partial class TenderSourcingFoundation : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "Tenders", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), TenderNumber = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), Title = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), Description = table.Column<string>(type: "nvarchar(max)", maxLength: 4000, nullable: false), TenderType = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false), ProcurementMethod = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), Status = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), PublicationDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), ClosingDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), CreatedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), PublishedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), PublishedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true) }, constraints: table => table.PrimaryKey("PK_Tenders", x => x.Id));
        migrationBuilder.CreateIndex(name: "IX_Tenders_TenderNumber", table: "Tenders", column: "TenderNumber", unique: true);
        migrationBuilder.CreateTable(name: "TenderLots", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), TenderId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), LotNumber = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), Title = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), Description = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: false) }, constraints: table => { table.PrimaryKey("PK_TenderLots", x => x.Id); table.ForeignKey("FK_TenderLots_Tenders_TenderId", x => x.TenderId, "Tenders", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "TenderDocuments", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), TenderId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), DocumentType = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), FileName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), Description = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false), IsRequired = table.Column<bool>(type: "bit", nullable: false), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), CreatedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false) }, constraints: table => { table.PrimaryKey("PK_TenderDocuments", x => x.Id); table.ForeignKey("FK_TenderDocuments_Tenders_TenderId", x => x.TenderId, "Tenders", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "TenderSupplierInvitations", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), TenderId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), SupplierId = table.Column<Guid>(type: "uniqueidentifier", nullable: true), SupplierName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), SupplierEmail = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), InvitedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), InvitedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), NotifiedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true) }, constraints: table => { table.PrimaryKey("PK_TenderSupplierInvitations", x => x.Id); table.ForeignKey("FK_TenderSupplierInvitations_Tenders_TenderId", x => x.TenderId, "Tenders", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "TenderClarifications", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), TenderId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Question = table.Column<string>(type: "nvarchar(max)", maxLength: 4000, nullable: false), AskedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), AskedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), IsPublic = table.Column<bool>(type: "bit", nullable: false) }, constraints: table => { table.PrimaryKey("PK_TenderClarifications", x => x.Id); table.ForeignKey("FK_TenderClarifications_Tenders_TenderId", x => x.TenderId, "Tenders", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "TenderStatusHistories", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), TenderId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), FromStatus = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), ToStatus = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), Actor = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), ChangedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), Notes = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false) }, constraints: table => { table.PrimaryKey("PK_TenderStatusHistories", x => x.Id); table.ForeignKey("FK_TenderStatusHistories_Tenders_TenderId", x => x.TenderId, "Tenders", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "TenderClarificationResponses", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), TenderClarificationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Response = table.Column<string>(type: "nvarchar(max)", maxLength: 4000, nullable: false), RespondedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), RespondedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false) }, constraints: table => { table.PrimaryKey("PK_TenderClarificationResponses", x => x.Id); table.ForeignKey("FK_TenderClarificationResponses_TenderClarifications_TenderClarificationId", x => x.TenderClarificationId, "TenderClarifications", "Id", onDelete: ReferentialAction.Cascade); });
        foreach (var table in new[] { "TenderLots", "TenderDocuments", "TenderSupplierInvitations", "TenderClarifications", "TenderStatusHistories" }) migrationBuilder.CreateIndex($"IX_{table}_TenderId", table, "TenderId");
        migrationBuilder.CreateIndex("IX_TenderClarificationResponses_TenderClarificationId", "TenderClarificationResponses", "TenderClarificationId");
    }
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable("TenderClarificationResponses"); migrationBuilder.DropTable("TenderDocuments"); migrationBuilder.DropTable("TenderLots"); migrationBuilder.DropTable("TenderStatusHistories"); migrationBuilder.DropTable("TenderSupplierInvitations"); migrationBuilder.DropTable("TenderClarifications"); migrationBuilder.DropTable("Tenders");
    }
}
