using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lca.EProcurement.EntityFrameworkCore.Migrations
{
    public partial class IntegrationManagement : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(name: "IntegrationEndpoints", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Code = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), Name = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), SystemType = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), BaseUrl = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: false), AuthType = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), IsEnabled = table.Column<bool>(type: "bit", nullable: false), SettingsJson = table.Column<string>(type: "nvarchar(max)", nullable: false), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true) }, constraints: table => table.PrimaryKey("PK_IntegrationEndpoints", x => x.Id));
            migrationBuilder.CreateTable(name: "IntegrationMessages", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), EndpointId = table.Column<Guid>(type: "uniqueidentifier", nullable: true), EntityType = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), EntityId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Direction = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false), PayloadJson = table.Column<string>(type: "nvarchar(max)", nullable: false), Status = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), ProcessedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true), ErrorMessage = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true) }, constraints: table => table.PrimaryKey("PK_IntegrationMessages", x => x.Id));
            migrationBuilder.CreateTable(name: "IntegrationLogs", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), EndpointId = table.Column<Guid>(type: "uniqueidentifier", nullable: true), MessageId = table.Column<Guid>(type: "uniqueidentifier", nullable: true), EntityType = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), EntityId = table.Column<Guid>(type: "uniqueidentifier", nullable: true), ExternalSystemCode = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), Direction = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false), Status = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), Error = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true), Timestamp = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false) }, constraints: table => table.PrimaryKey("PK_IntegrationLogs", x => x.Id));
            migrationBuilder.CreateTable(name: "ExternalSystemReferences", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), EntityType = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), EntityId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), ExternalSystemCode = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), ExternalReference = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false), Status = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true) }, constraints: table => table.PrimaryKey("PK_ExternalSystemReferences", x => x.Id));
            migrationBuilder.CreateTable(name: "DocumentIntegrationReferences", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), DocumentId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), EntityType = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false), EntityId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), StorageReference = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: false), ExternalDocumentId = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true), SyncStatus = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false), CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false), UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true) }, constraints: table => table.PrimaryKey("PK_DocumentIntegrationReferences", x => x.Id));
            migrationBuilder.CreateIndex(name: "IX_IntegrationEndpoints_Code", table: "IntegrationEndpoints", column: "Code", unique: true);
            migrationBuilder.CreateIndex(name: "IX_ExternalSystemReferences_EntityType_EntityId_ExternalSystemCode", table: "ExternalSystemReferences", columns: new[] { "EntityType", "EntityId", "ExternalSystemCode" }, unique: true);
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "DocumentIntegrationReferences"); migrationBuilder.DropTable(name: "ExternalSystemReferences"); migrationBuilder.DropTable(name: "IntegrationLogs"); migrationBuilder.DropTable(name: "IntegrationMessages"); migrationBuilder.DropTable(name: "IntegrationEndpoints");
        }
    }
}
