import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { GitBranch, Gauge, ListChecks, Settings, SlidersHorizontal, Workflow } from "lucide-react";
import "./styles.css";

type WorkflowDefinition = { code: string; name: string; entityType: string; versions?: { status: string; nodes: Node[]; transitions: Transition[] }[] };
type Node = { code: string; name: string; kind: string; createsTask: boolean; isStart: boolean; isTerminal: boolean };
type Transition = { fromNodeCode: string; actionCode: string; actionName: string; toNodeCode: string; requiredRuleCode?: string };
type Rule = { code: string; name: string; appliesTo: string; expression: string };
type FormDefinition = { code: string; name: string; entityType: string; versions?: { status: string; sections: Section[] }[] };
type Section = { code: string; title: string; fields: Field[] };
type Field = { code: string; label: string; fieldType: string; isRequired: boolean };
type Dashboard = { workflowsCount: number; rulesCount: number; formsCount: number; activeWorkflowInstances: number; pendingTasks: number };
const api = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:5000";
async function getJson<T>(path: string, fallback: T): Promise<T> { try { const r = await fetch(`${api}${path}`); return r.ok ? await r.json() : fallback; } catch { return fallback; } }
async function postJson(path: string, body: unknown) { await fetch(`${api}${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); }
function useRefresh() { const [v, set] = useState(0); return [v, () => set(x => x + 1)] as const; }
function App() {
  const [refresh, reload] = useRefresh();
  const [dashboard, setDashboard] = useState<Dashboard>({ workflowsCount: 0, rulesCount: 0, formsCount: 0, activeWorkflowInstances: 0, pendingTasks: 0 });
  const [workflows, setWorkflows] = useState<WorkflowDefinition[]>([]); const [rules, setRules] = useState<Rule[]>([]); const [forms, setForms] = useState<FormDefinition[]>([]); const [lookups, setLookups] = useState<any[]>([]); const [effects, setEffects] = useState<any[]>([]); const [mappings, setMappings] = useState<any[]>([]); const [docs, setDocs] = useState<any[]>([]);
  useEffect(() => { void Promise.all([getJson<Dashboard>("/api/workflows/dashboard", dashboard), getJson<WorkflowDefinition[]>("/api/workflows", []), getJson<Rule[]>("/api/business-rules", []), getJson<FormDefinition[]>("/api/form-definitions", []), getJson<any[]>("/api/platform-configuration/lookup-values", []), getJson<any[]>("/api/platform-configuration/transition-effects", []), getJson<any[]>("/api/platform-configuration/workflow-mappings", []), getJson<any[]>("/api/platform-configuration/document-type-requirements", [])]).then(([d,w,r,f,l,e,m,dr]) => { setDashboard(d); setWorkflows(w); setRules(r); setForms(f); setLookups(l); setEffects(e); setMappings(m); setDocs(dr); }); }, [refresh]);
  const currentWorkflow = workflows[0]; const draftWorkflow = currentWorkflow?.versions?.[0]; const currentForm = forms[0]; const draftForm = currentForm?.versions?.[0];
  return <div className="shell"><aside><h2>Administration Studio</h2><nav>{["Platform Dashboard","Workflow Designer","Rule Designer","Dynamic Form Designer","Configuration"].map(x => <a href={`#${x.replace(/ /g, "-")}`} key={x}>{x}</a>)}</nav></aside><main><header><div><p>Database-configured enterprise platform</p><h1>Administration Studio</h1></div><button onClick={reload}>Refresh configuration</button></header>
    <section id="Platform-Dashboard" className="cards"><Card icon={<Workflow/>} label="Workflows" value={dashboard.workflowsCount}/><Card icon={<ListChecks/>} label="Rules" value={dashboard.rulesCount}/><Card icon={<SlidersHorizontal/>} label="Forms" value={dashboard.formsCount}/><Card icon={<Gauge/>} label="Active instances" value={dashboard.activeWorkflowInstances}/><Card icon={<GitBranch/>} label="Pending tasks" value={dashboard.pendingTasks}/></section>
    <section className="grid"><Panel title="Workflow Designer"><CreateWorkflow onDone={reload}/><h3>Workflow definitions</h3>{workflows.map(w => <article className="item" key={w.code}><b>{w.name}</b><small>{w.code} · {w.entityType}</small></article>)}<AddNode code={currentWorkflow?.code} onDone={reload}/><AddTransition code={currentWorkflow?.code} onDone={reload}/><button disabled={!currentWorkflow} onClick={() => postJson(`/api/workflows/${currentWorkflow!.code}/publish`, { actor: "admin@lca.org.ls" }).then(reload)}>Publish workflow</button><div className="path">{draftWorkflow?.transitions?.map(t => <span key={t.actionCode}>{t.fromNodeCode} → {t.toNodeCode}</span>)}</div></Panel>
    <Panel title="Rule Designer"><CreateRule onDone={reload}/>{rules.map(r => <article className="item" key={r.code}><b>{r.name}</b><code>{r.expression}</code><button onClick={() => alert("Provide an entity id from an entity detail page to execute this configured rule.")}>Test rule</button></article>)}</Panel>
    <Panel title="Dynamic Form Designer"><CreateForm onDone={reload}/>{forms.map(f => <article className="item" key={f.code}><b>{f.name}</b><small>{f.code} · {f.entityType}</small></article>)}<AddSection code={currentForm?.code} onDone={reload}/><AddField code={currentForm?.code} section={draftForm?.sections?.[0]?.code} onDone={reload}/><button disabled={!currentForm} onClick={() => postJson(`/api/form-definitions/${currentForm!.code}/publish`, { actor: "admin@lca.org.ls" }).then(reload)}>Publish form</button></Panel>
    <Panel title="Configuration"><CreateLookup onDone={reload}/><div className="columns"><List title="Lookup values" items={lookups}/><List title="Supplier categories" items={lookups.filter(x => x.lookupType === "SupplierCategory")}/><List title="Document types" items={docs}/><List title="Workflow mappings" items={mappings}/><List title="Transition effects" items={effects}/></div></Panel></section></main></div>;
}
function Card(p:{icon:React.ReactNode;label:string;value:number}){return <article>{p.icon}<b>{p.value}</b><span>{p.label}</span></article>}
function Panel(p:{title:string;children:React.ReactNode}){return <div id={p.title.replace(/ /g, "-")} className="panel"><h2>{p.title}</h2>{p.children}</div>}
function Text({name,placeholder}:{name:string;placeholder?:string}){return <input name={name} placeholder={placeholder ?? name} />}
function formData(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); return Object.fromEntries(new FormData(e.currentTarget).entries()) as any}
function CreateWorkflow({onDone}:{onDone:()=>void}){return <form onSubmit={e=>{const d=formData(e); postJson("/api/workflows",{...d,nodes:[],transitions:[]}).then(onDone)}}><Text name="code"/><Text name="name"/><Text name="entityType" placeholder="Entity type"/><button>Create workflow</button></form>}
function AddNode({code,onDone}:{code?:string;onDone:()=>void}){return <form onSubmit={e=>{const d=formData(e); postJson(`/api/workflows/${code}/nodes`,{...d,kind:d.kind||"Task",createsTask:!!d.createsTask,isStart:!!d.isStart,isTerminal:!!d.isTerminal}).then(onDone)}}><Text name="code"/><Text name="name"/><select name="kind"><option>Start</option><option>Task</option><option>Automatic</option><option>End</option></select><label><input name="createsTask" type="checkbox"/>Creates task</label><label><input name="isStart" type="checkbox"/>Start</label><label><input name="isTerminal" type="checkbox"/>Terminal</label><button disabled={!code}>Add node</button></form>}
function AddTransition({code,onDone}:{code?:string;onDone:()=>void}){return <form onSubmit={e=>postJson(`/api/workflows/${code}/transitions`,formData(e)).then(onDone)}><Text name="fromNodeCode"/><Text name="actionCode"/><Text name="actionName"/><Text name="toNodeCode"/><Text name="requiredRuleCode"/><button disabled={!code}>Add transition</button></form>}
function CreateRule({onDone}:{onDone:()=>void}){return <form onSubmit={e=>postJson("/api/business-rules",formData(e)).then(onDone)}><Text name="code"/><Text name="name"/><Text name="appliesTo"/><Text name="expression"/><button>Create rule</button></form>}
function CreateForm({onDone}:{onDone:()=>void}){return <form onSubmit={e=>{const d=formData(e); postJson("/api/form-definitions",{...d,sections:[]}).then(onDone)}}><Text name="code"/><Text name="name"/><Text name="entityType"/><button>Create form</button></form>}
function AddSection({code,onDone}:{code?:string;onDone:()=>void}){return <form onSubmit={e=>{const d=formData(e); postJson(`/api/form-definitions/${code}/sections`,{...d,displayOrder:Number(d.displayOrder||1),fields:[]}).then(onDone)}}><Text name="code"/><Text name="title"/><Text name="displayOrder"/><button disabled={!code}>Add section</button></form>}
function AddField({code,section,onDone}:{code?:string;section?:string;onDone:()=>void}){return <form onSubmit={e=>{const d=formData(e); postJson(`/api/form-definitions/${code}/sections/${section}/fields`,{...d,displayOrder:Number(d.displayOrder||1),isRequired:!!d.isRequired}).then(onDone)}}><Text name="code"/><Text name="label"/><Text name="fieldType"/><Text name="displayOrder"/><label><input name="isRequired" type="checkbox"/>Required</label><button disabled={!code||!section}>Add field</button></form>}
function CreateLookup({onDone}:{onDone:()=>void}){return <form onSubmit={e=>postJson("/api/platform-configuration/lookup-values",formData(e)).then(onDone)}><Text name="lookupType"/><Text name="code"/><Text name="name"/><button>Add lookup</button></form>}
function List({title,items}:{title:string;items:any[]}){return <div><h3>{title}</h3>{items.map((x,i)=><p className="item" key={i}>{x.name ?? x.code ?? x.workflowCode}</p>)}</div>}
createRoot(document.getElementById("root")!).render(<App />);
