using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Lca.EProcurement.Domain;
using Lca.EProcurement.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Lca.EProcurement.Application;

public sealed record GovernanceDashboardDto(int ActivePolicies, int RetentionRules, int PrivacyClassifications, int MigrationBatches, int DataQualityChecks, int ArchiveBatches, int ExportRequests, int ProcessingLogs);
public sealed record ArchivePreviewDto(string EntityType, DateTimeOffset CutoffDate, int EligibleCount, List<object> Items);
public sealed record CreatePolicyDto(string Code,string Name,string Description,DataGovernancePolicyType PolicyType,string EntityType,bool IsActive=true);
public sealed record CreateRetentionRuleDto(string Code,string Name,string EntityType,int RetentionPeriodDays,int ArchiveAfterDays,int? DeleteAfterDays,bool LegalHoldSupported=true,bool RequiresApprovalForDeletion=true,bool IsActive=true);
public sealed record CreatePrivacyClassificationDto(string EntityType,string FieldName,DataPrivacyClassificationLevel Classification,string Reason,bool IsSensitive=true,bool MaskInUi=true,bool MaskInExports=true);
public sealed record MigrationTemplateDto(string Code,string Name,string EntityType,string Description,string FileFormat,List<MigrationTemplateFieldDto> Fields);
public sealed record MigrationTemplateFieldDto(string FieldName,string DisplayName,string DataType,bool IsRequired,int? MaxLength=null,string? LookupType=null,string? ExampleValue=null,string? ValidationRule=null,int DisplayOrder=0);
public sealed record UploadMigrationBatchDto(Guid TemplateId,string SourceName,string FileName,string CsvContent,string UploadedBy,string? Notes=null);
public sealed record DataExportRequestDto(string EntityType,string RequestedBy,string Format,bool IncludeSensitiveData,string Reason,bool HasSensitivePermission=false);
public sealed record ArchiveBatchRequestDto(string EntityType,DateTimeOffset CutoffDate,string Reason,string Actor);
public sealed record DataQualityResultDto(string Code,string EntityType,string Severity,string Message,Guid? EntityId);

public interface IDataGovernanceApplicationService
{
    Task<GovernanceDashboardDto> GetDashboardAsync(CancellationToken ct=default);
    Task<List<DataGovernancePolicy>> GetPoliciesAsync(CancellationToken ct=default); Task<DataGovernancePolicy> CreatePolicyAsync(CreatePolicyDto dto,string actor="system",CancellationToken ct=default); Task<DataGovernancePolicy?> UpdatePolicyAsync(Guid id,CreatePolicyDto dto,string actor="system",CancellationToken ct=default);
    Task<List<DataRetentionRule>> GetRetentionRulesAsync(CancellationToken ct=default); Task<DataRetentionRule> CreateRetentionRuleAsync(CreateRetentionRuleDto dto,string actor="system",CancellationToken ct=default); Task<DataRetentionRule?> UpdateRetentionRuleAsync(Guid id,CreateRetentionRuleDto dto,string actor="system",CancellationToken ct=default);
    Task<List<DataPrivacyClassification>> GetPrivacyClassificationsAsync(CancellationToken ct=default); Task<DataPrivacyClassification> CreatePrivacyClassificationAsync(CreatePrivacyClassificationDto dto,string actor="system",CancellationToken ct=default); Task<DataPrivacyClassification?> UpdatePrivacyClassificationAsync(Guid id,CreatePrivacyClassificationDto dto,string actor="system",CancellationToken ct=default);
    Task<List<DataProcessingLog>> GetProcessingLogsAsync(CancellationToken ct=default);
}
public interface IMigrationApplicationService { Task<List<MigrationTemplate>> GetTemplatesAsync(CancellationToken ct=default); Task<MigrationTemplate?> GetTemplateAsync(Guid id,CancellationToken ct=default); Task<MigrationTemplate> CreateTemplateAsync(MigrationTemplateDto dto,string actor="system",CancellationToken ct=default); Task<MigrationTemplate?> UpdateTemplateAsync(Guid id,MigrationTemplateDto dto,string actor="system",CancellationToken ct=default); Task<string> GenerateSampleCsvAsync(Guid templateId,CancellationToken ct=default); Task<List<MigrationBatch>> GetBatchesAsync(CancellationToken ct=default); Task<MigrationBatch?> GetBatchAsync(Guid id,CancellationToken ct=default); Task<MigrationBatch> UploadBatchAsync(UploadMigrationBatchDto dto,CancellationToken ct=default); Task<MigrationBatch?> ValidateBatchAsync(Guid id,CancellationToken ct=default); Task<MigrationBatch?> ImportBatchAsync(Guid id,string actor="system",CancellationToken ct=default); Task<MigrationBatch?> CancelBatchAsync(Guid id,CancellationToken ct=default); Task<List<MigrationValidationIssue>> GetIssuesAsync(Guid batchId,CancellationToken ct=default); Task<List<MigrationImportItem>> GetItemsAsync(Guid batchId,CancellationToken ct=default); }
public interface IDataArchivalService { Task<ArchivePreviewDto> PreviewArchiveAsync(string entityType,DateTimeOffset cutoffDate,CancellationToken ct=default); Task<DataArchiveBatch> CreateArchiveBatchAsync(string entityType,DateTimeOffset cutoffDate,string reason,string actor="system",CancellationToken ct=default); Task<DataArchiveBatch?> RunArchiveBatchAsync(Guid batchId,CancellationToken ct=default); Task<List<DataArchiveBatch>> GetArchiveBatchesAsync(CancellationToken ct=default); Task<DataArchiveBatch?> GetArchiveBatchAsync(Guid batchId,CancellationToken ct=default); }
public interface IDataQualityApplicationService { Task<List<DataQualityCheck>> GetChecksAsync(CancellationToken ct=default); Task<DataQualityCheck> CreateCheckAsync(DataQualityCheck check,CancellationToken ct=default); Task<DataQualityCheck?> UpdateCheckAsync(Guid id,DataQualityCheck check,CancellationToken ct=default); Task<List<DataQualityResultDto>> RunAsync(CancellationToken ct=default); Task<List<DataQualityResultDto>> GetResultsAsync(CancellationToken ct=default); }
public interface IDataExportApplicationService { Task<DataExportRequest> RequestExportAsync(DataExportRequestDto dto,CancellationToken ct=default); Task<List<DataExportRequest>> GetExportsAsync(CancellationToken ct=default); Task<DataExportRequest?> GetExportAsync(Guid id,CancellationToken ct=default); Task<string> DownloadAsync(Guid id,string actor="system",CancellationToken ct=default); }

public sealed class DataGovernanceApplicationService(EProcurementDbContext db) : IDataGovernanceApplicationService
{
    async Task Log(DataProcessingOperationType op,string entity,string actor,string purpose,string details,CancellationToken ct){ db.DataProcessingLogs.Add(new(op,entity,null,actor,purpose,details,DateTimeOffset.UtcNow)); db.AuditEvents.Add(new AuditEvent($"{purpose}",entity,Guid.Empty,op.ToString(),actor,details,DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); }
    public async Task<GovernanceDashboardDto> GetDashboardAsync(CancellationToken ct=default)=>new(await db.DataGovernancePolicies.CountAsync(x=>x.IsActive,ct),await db.DataRetentionRules.CountAsync(ct),await db.DataPrivacyClassifications.CountAsync(ct),await db.MigrationBatches.CountAsync(ct),await db.DataQualityChecks.CountAsync(ct),await db.DataArchiveBatches.CountAsync(ct),await db.DataExportRequests.CountAsync(ct),await db.DataProcessingLogs.CountAsync(ct));
    public Task<List<DataGovernancePolicy>> GetPoliciesAsync(CancellationToken ct=default)=>db.DataGovernancePolicies.AsNoTracking().ToListAsync(ct);
    public async Task<DataGovernancePolicy> CreatePolicyAsync(CreatePolicyDto d,string actor="system",CancellationToken ct=default){var e=new DataGovernancePolicy(d.Code,d.Name,d.Description,d.PolicyType,d.EntityType,d.IsActive,DateTimeOffset.UtcNow,null,actor,DateTimeOffset.UtcNow);db.Add(e);await Log(DataProcessingOperationType.RetentionRuleApplied,d.EntityType,actor,"Data governance policy created",d.Code,ct);return e;}
    public async Task<DataGovernancePolicy?> UpdatePolicyAsync(Guid id,CreatePolicyDto d,string actor="system",CancellationToken ct=default){var e=await db.DataGovernancePolicies.FindAsync([id],ct); if(e is null)return null; db.Entry(e).CurrentValues.SetValues(e with{Code=d.Code,Name=d.Name,Description=d.Description,PolicyType=d.PolicyType,EntityType=d.EntityType,IsActive=d.IsActive,UpdatedBy=actor,UpdatedAt=DateTimeOffset.UtcNow}); await Log(DataProcessingOperationType.RetentionRuleApplied,d.EntityType,actor,"Data governance policy updated",d.Code,ct); return await db.DataGovernancePolicies.FindAsync([id],ct);} 
    public Task<List<DataRetentionRule>> GetRetentionRulesAsync(CancellationToken ct=default)=>db.DataRetentionRules.AsNoTracking().ToListAsync(ct);
    public async Task<DataRetentionRule> CreateRetentionRuleAsync(CreateRetentionRuleDto d,string actor="system",CancellationToken ct=default){var e=new DataRetentionRule(d.Code,d.Name,d.EntityType,d.RetentionPeriodDays,d.ArchiveAfterDays,d.DeleteAfterDays,d.LegalHoldSupported,d.RequiresApprovalForDeletion,d.IsActive,actor,DateTimeOffset.UtcNow);db.Add(e);await Log(DataProcessingOperationType.RetentionRuleApplied,d.EntityType,actor,"Retention rule created",d.Code,ct);return e;}
    public async Task<DataRetentionRule?> UpdateRetentionRuleAsync(Guid id,CreateRetentionRuleDto d,string actor="system",CancellationToken ct=default){var e=await db.DataRetentionRules.FindAsync([id],ct); if(e is null)return null; db.Entry(e).CurrentValues.SetValues(e with{Code=d.Code,Name=d.Name,EntityType=d.EntityType,RetentionPeriodDays=d.RetentionPeriodDays,ArchiveAfterDays=d.ArchiveAfterDays,DeleteAfterDays=d.DeleteAfterDays,LegalHoldSupported=d.LegalHoldSupported,RequiresApprovalForDeletion=d.RequiresApprovalForDeletion,IsActive=d.IsActive,UpdatedBy=actor,UpdatedAt=DateTimeOffset.UtcNow}); await Log(DataProcessingOperationType.RetentionRuleApplied,d.EntityType,actor,"Retention rule updated",d.Code,ct); return await db.DataRetentionRules.FindAsync([id],ct);} 
    public Task<List<DataPrivacyClassification>> GetPrivacyClassificationsAsync(CancellationToken ct=default)=>db.DataPrivacyClassifications.AsNoTracking().ToListAsync(ct);
    public async Task<DataPrivacyClassification> CreatePrivacyClassificationAsync(CreatePrivacyClassificationDto d,string actor="system",CancellationToken ct=default){var e=new DataPrivacyClassification(d.EntityType,d.FieldName,d.Classification,d.Reason,d.IsSensitive,d.MaskInUi,d.MaskInExports,DateTimeOffset.UtcNow,actor);db.Add(e);await Log(DataProcessingOperationType.PrivacyMasking,d.EntityType,actor,"Privacy classification created",d.FieldName,ct);return e;}
    public async Task<DataPrivacyClassification?> UpdatePrivacyClassificationAsync(Guid id,CreatePrivacyClassificationDto d,string actor="system",CancellationToken ct=default){var e=await db.DataPrivacyClassifications.FindAsync([id],ct); if(e is null)return null; db.Entry(e).CurrentValues.SetValues(e with{EntityType=d.EntityType,FieldName=d.FieldName,Classification=d.Classification,Reason=d.Reason,IsSensitive=d.IsSensitive,MaskInUi=d.MaskInUi,MaskInExports=d.MaskInExports}); await Log(DataProcessingOperationType.PrivacyMasking,d.EntityType,actor,"Privacy classification updated",d.FieldName,ct); return await db.DataPrivacyClassifications.FindAsync([id],ct);} 
    public Task<List<DataProcessingLog>> GetProcessingLogsAsync(CancellationToken ct=default)=>db.DataProcessingLogs.AsNoTracking().OrderByDescending(x=>x.OccurredAt).ToListAsync(ct);
}

public sealed class MigrationApplicationService(EProcurementDbContext db) : IMigrationApplicationService
{
    static List<Dictionary<string,string>> Parse(string csv){var lines=csv.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries); if(lines.Length==0)return[]; var h=lines[0].Split(',').Select(x=>x.Trim()).ToArray(); return lines.Skip(1).Select(l=>l.Split(',')).Select((v,i)=>h.Select((k,j)=>(k,val:j<v.Length?v[j].Trim():"")).ToDictionary(x=>x.k,x=>x.val)).ToList();}
    async Task Log(DataProcessingOperationType op,string entity,string actor,string purpose,string details,CancellationToken ct){db.DataProcessingLogs.Add(new(op,entity,null,actor,purpose,details,DateTimeOffset.UtcNow));db.AuditEvents.Add(new AuditEvent(purpose,entity,Guid.Empty,op.ToString(),actor,details,DateTimeOffset.UtcNow));await db.SaveChangesAsync(ct);}    
    public Task<List<MigrationTemplate>> GetTemplatesAsync(CancellationToken ct=default)=>db.MigrationTemplates.Include(x=>x.Fields).AsNoTracking().ToListAsync(ct); public Task<MigrationTemplate?> GetTemplateAsync(Guid id,CancellationToken ct=default)=>db.MigrationTemplates.Include(x=>x.Fields).FirstOrDefaultAsync(x=>x.Id==id,ct);
    public async Task<MigrationTemplate> CreateTemplateAsync(MigrationTemplateDto d,string actor="system",CancellationToken ct=default){var t=new MigrationTemplate(d.Code,d.Name,d.EntityType,d.Description,d.FileFormat,true,actor,DateTimeOffset.UtcNow);t.Fields.AddRange(d.Fields.Select(f=>new MigrationTemplateField(t.Id,f.FieldName,f.DisplayName,f.DataType,f.IsRequired,f.MaxLength,f.LookupType,f.ExampleValue,f.ValidationRule,f.DisplayOrder)));db.Add(t);await Log(DataProcessingOperationType.Import,d.EntityType,actor,"Migration template created",d.Code,ct);return t;}
    public async Task<MigrationTemplate?> UpdateTemplateAsync(Guid id,MigrationTemplateDto d,string actor="system",CancellationToken ct=default){var t=await db.MigrationTemplates.Include(x=>x.Fields).FirstOrDefaultAsync(x=>x.Id==id,ct); if(t is null)return null; db.MigrationTemplateFields.RemoveRange(t.Fields); db.Entry(t).CurrentValues.SetValues(t with{Code=d.Code,Name=d.Name,EntityType=d.EntityType,Description=d.Description,FileFormat=d.FileFormat}); t.Fields.AddRange(d.Fields.Select(f=>new MigrationTemplateField(t.Id,f.FieldName,f.DisplayName,f.DataType,f.IsRequired,f.MaxLength,f.LookupType,f.ExampleValue,f.ValidationRule,f.DisplayOrder))); await db.SaveChangesAsync(ct); return t;}
    public async Task<string> GenerateSampleCsvAsync(Guid id,CancellationToken ct=default){var t=await GetTemplateAsync(id,ct)??throw new InvalidOperationException("Template not found"); return string.Join(',',t.Fields.OrderBy(f=>f.DisplayOrder).Select(f=>f.FieldName))+"\n"+string.Join(',',t.Fields.OrderBy(f=>f.DisplayOrder).Select(f=>f.ExampleValue??""));}
    public Task<List<MigrationBatch>> GetBatchesAsync(CancellationToken ct=default)=>db.MigrationBatches.AsNoTracking().ToListAsync(ct); public Task<MigrationBatch?> GetBatchAsync(Guid id,CancellationToken ct=default)=>db.MigrationBatches.Include(x=>x.Items).Include(x=>x.Issues).FirstOrDefaultAsync(x=>x.Id==id,ct);
    public async Task<MigrationBatch> UploadBatchAsync(UploadMigrationBatchDto d,CancellationToken ct=default){var t=await GetTemplateAsync(d.TemplateId,ct)??throw new InvalidOperationException("Template not found"); var rows=Parse(d.CsvContent); var b=new MigrationBatch($"MIG-{DateTimeOffset.UtcNow:yyyyMMddHHmmss}",d.SourceName,t.EntityType,d.FileName,d.UploadedBy,DateTimeOffset.UtcNow,MigrationBatchStatus.Uploaded,TotalRows:rows.Count,Notes:d.Notes); int n=1; foreach(var r in rows)b.Items.Add(new MigrationImportItem(b.Id,++n,r.Values.FirstOrDefault(),t.EntityType,null,JsonSerializer.Serialize(r),JsonSerializer.Serialize(r),MigrationBatchStatus.Uploaded)); db.Add(b); await Log(DataProcessingOperationType.Import,t.EntityType,d.UploadedBy,"Migration batch uploaded",d.FileName,ct); return b;}
    public async Task<MigrationBatch?> ValidateBatchAsync(Guid id,CancellationToken ct=default){var b=await GetBatchAsync(id,ct); if(b is null)return null; var t=await db.MigrationTemplates.Include(x=>x.Fields).FirstAsync(x=>x.EntityType==b.EntityType,ct); db.MigrationValidationIssues.RemoveRange(b.Issues); var seen=new HashSet<string>(); foreach(var item in b.Items){var row=JsonSerializer.Deserialize<Dictionary<string,string>>(item.RawDataJson)??[]; foreach(var f in t.Fields.Where(x=>x.IsRequired)) if(!row.TryGetValue(f.FieldName,out var val)||string.IsNullOrWhiteSpace(val)) db.MigrationValidationIssues.Add(new(b.Id,item.Id,item.RowNumber,f.FieldName,MigrationIssueSeverity.Error,$"{f.DisplayName} is required",DateTimeOffset.UtcNow)); foreach(var f in t.Fields){ if(!row.TryGetValue(f.FieldName,out var val)||string.IsNullOrWhiteSpace(val))continue; if(f.DataType.Equals("Date",StringComparison.OrdinalIgnoreCase)&&!DateTimeOffset.TryParse(val,out _)) db.MigrationValidationIssues.Add(new(b.Id,item.Id,item.RowNumber,f.FieldName,MigrationIssueSeverity.Error,$"{f.DisplayName} has invalid date format",DateTimeOffset.UtcNow)); if(f.DataType.Equals("Decimal",StringComparison.OrdinalIgnoreCase)&&(!decimal.TryParse(val,out var dec)||dec<0)) db.MigrationValidationIssues.Add(new(b.Id,item.Id,item.RowNumber,f.FieldName,MigrationIssueSeverity.Error,$"{f.DisplayName} must be a positive decimal",DateTimeOffset.UtcNow)); if(f.FieldName.Contains("Email")&&!Regex.IsMatch(val,@"^[^@\s]+@[^@\s]+\.[^@\s]+$")) db.MigrationValidationIssues.Add(new(b.Id,item.Id,item.RowNumber,f.FieldName,MigrationIssueSeverity.Error,$"{f.DisplayName} must be a valid email",DateTimeOffset.UtcNow)); } var ext=row.Values.FirstOrDefault()??$"row-{item.RowNumber}"; if(!seen.Add(ext)) db.MigrationValidationIssues.Add(new(b.Id,item.Id,item.RowNumber,"ExternalReference",MigrationIssueSeverity.Error,"Duplicate external reference",DateTimeOffset.UtcNow)); if(b.EntityType=="Tender"&&DateTimeOffset.TryParse(row.GetValueOrDefault("PublicationDate"),out var p)&&DateTimeOffset.TryParse(row.GetValueOrDefault("ClosingDate"),out var c)&&c<=p) db.MigrationValidationIssues.Add(new(b.Id,item.Id,item.RowNumber,"ClosingDate",MigrationIssueSeverity.Error,"Closing date must be after publication date",DateTimeOffset.UtcNow)); }
        await db.SaveChangesAsync(ct); var errors=await db.MigrationValidationIssues.CountAsync(x=>x.BatchId==b.Id&&x.Severity==MigrationIssueSeverity.Error,ct); db.Entry(b).CurrentValues[nameof(MigrationBatch.Status)]=errors>0?MigrationBatchStatus.ValidationFailed:MigrationBatchStatus.ReadyToImport; db.Entry(b).CurrentValues[nameof(MigrationBatch.ValidationSummaryJson)]=$"{{\"errors\":{errors}}}"; await Log(DataProcessingOperationType.MigrationValidation,b.EntityType,b.UploadedBy,errors>0?"Migration validation failed":"Migration batch validated",b.BatchNumber,ct); return await GetBatchAsync(id,ct);}
    public async Task<MigrationBatch?> ImportBatchAsync(Guid id,string actor="system",CancellationToken ct=default){var b=await GetBatchAsync(id,ct); if(b is null)return null; if(await db.MigrationValidationIssues.AnyAsync(x=>x.BatchId==id&&x.Severity==MigrationIssueSeverity.Error,ct)) throw new InvalidOperationException("Import blocked while error validation issues exist."); int ok=0; foreach(var item in b.Items){var row=JsonSerializer.Deserialize<Dictionary<string,string>>(item.RawDataJson)??[]; if(b.EntityType=="Supplier") db.Suppliers.Add(new Supplier(row.GetValueOrDefault("SupplierReference")??$"SUP-{item.RowNumber}",row.GetValueOrDefault("LegalName")??"Imported Supplier",Enum.TryParse<SupplierStatus>(row.GetValueOrDefault("Status"),true,out var ss)?ss:SupplierStatus.Draft)); if(b.EntityType=="Tender") db.Tenders.Add(new Tender(row.GetValueOrDefault("TenderNumber")??$"TEN-{item.RowNumber}",row.GetValueOrDefault("Title")??"Imported Tender",row.GetValueOrDefault("Description")??"Imported",TenderType.RFP,row.GetValueOrDefault("ProcurementMethod")??"Open Tender",TenderStatus.Draft,DateTimeOffset.TryParse(row.GetValueOrDefault("PublicationDate"),out var pd)?pd:null,DateTimeOffset.TryParse(row.GetValueOrDefault("ClosingDate"),out var cd)?cd:DateTimeOffset.UtcNow.AddDays(30),actor,DateTimeOffset.UtcNow)); ok++; db.Entry(item).CurrentValues[nameof(MigrationImportItem.Status)]=MigrationBatchStatus.Imported; db.Entry(item).CurrentValues[nameof(MigrationImportItem.ImportedAt)]=DateTimeOffset.UtcNow;} db.Entry(b).CurrentValues[nameof(MigrationBatch.Status)]=MigrationBatchStatus.Imported; db.Entry(b).CurrentValues[nameof(MigrationBatch.SuccessfulRows)]=ok; await Log(DataProcessingOperationType.Import,b.EntityType,actor,"Migration import completed",b.BatchNumber,ct); return await GetBatchAsync(id,ct);} 
    public async Task<MigrationBatch?> CancelBatchAsync(Guid id,CancellationToken ct=default){var b=await db.MigrationBatches.FindAsync([id],ct); if(b is null)return null; db.Entry(b).CurrentValues[nameof(MigrationBatch.Status)]=MigrationBatchStatus.Cancelled; await db.SaveChangesAsync(ct); return b;} public Task<List<MigrationValidationIssue>> GetIssuesAsync(Guid batchId,CancellationToken ct=default)=>db.MigrationValidationIssues.Where(x=>x.BatchId==batchId).AsNoTracking().ToListAsync(ct); public Task<List<MigrationImportItem>> GetItemsAsync(Guid batchId,CancellationToken ct=default)=>db.MigrationImportItems.Where(x=>x.BatchId==batchId).AsNoTracking().ToListAsync(ct);
}

public sealed class DataArchivalService(EProcurementDbContext db) : IDataArchivalService
{
    async Task Log(string entity,string actor,string purpose,string details,CancellationToken ct){db.DataProcessingLogs.Add(new(DataProcessingOperationType.Archive,entity,null,actor,purpose,details,DateTimeOffset.UtcNow));db.AuditEvents.Add(new AuditEvent(purpose,entity,Guid.Empty,"Archive",actor,details,DateTimeOffset.UtcNow));await db.SaveChangesAsync(ct);}    
    public async Task<ArchivePreviewDto> PreviewArchiveAsync(string entityType,DateTimeOffset cutoffDate,CancellationToken ct=default){List<object> items=entityType switch{"Supplier"=>await db.Suppliers.Take(25).Select(x=>new{x.Id,Reference=x.ReferenceNumber,x.LegalName}).Cast<object>().ToListAsync(ct),"Tender"=>await db.Tenders.Where(x=>x.ClosingDate<cutoffDate).Take(25).Select(x=>new{x.Id,Reference=x.TenderNumber,x.Title}).Cast<object>().ToListAsync(ct),_=>[]}; db.DataProcessingLogs.Add(new(DataProcessingOperationType.Archive,entityType,null,"system","Archive preview generated",$"Cutoff {cutoffDate:O}",DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return new(entityType,cutoffDate,items.Count,items);}
    public async Task<DataArchiveBatch> CreateArchiveBatchAsync(string entityType,DateTimeOffset cutoffDate,string reason,string actor="system",CancellationToken ct=default){var preview=await PreviewArchiveAsync(entityType,cutoffDate,ct); var b=new DataArchiveBatch($"ARC-{DateTimeOffset.UtcNow:yyyyMMddHHmmss}",entityType,reason,DataArchiveBatchStatus.Draft,actor,DateTimeOffset.UtcNow,TotalItems:preview.EligibleCount); foreach(dynamic i in preview.Items)b.Items.Add(new DataArchiveItem(b.Id,entityType,(Guid)i.Id,(string)i.Reference,"Active","Pending",reason)); db.Add(b); await Log(entityType,actor,"Archive batch created",b.BatchNumber,ct); return b;}
    public async Task<DataArchiveBatch?> RunArchiveBatchAsync(Guid batchId,CancellationToken ct=default){var b=await db.DataArchiveBatches.Include(x=>x.Items).FirstOrDefaultAsync(x=>x.Id==batchId,ct); if(b is null)return null; db.Entry(b).CurrentValues[nameof(DataArchiveBatch.Status)]=DataArchiveBatchStatus.Completed; db.Entry(b).CurrentValues[nameof(DataArchiveBatch.StartedAt)]=DateTimeOffset.UtcNow; db.Entry(b).CurrentValues[nameof(DataArchiveBatch.CompletedAt)]=DateTimeOffset.UtcNow; db.Entry(b).CurrentValues[nameof(DataArchiveBatch.ArchivedItems)]=b.Items.Count; foreach(var i in b.Items){db.Entry(i).CurrentValues[nameof(DataArchiveItem.ArchiveStatus)]="Archived"; db.Entry(i).CurrentValues[nameof(DataArchiveItem.ArchivedAt)]=DateTimeOffset.UtcNow;} await Log(b.EntityType,b.CreatedBy,"Archive batch completed",b.BatchNumber,ct); return b;}
    public Task<List<DataArchiveBatch>> GetArchiveBatchesAsync(CancellationToken ct=default)=>db.DataArchiveBatches.AsNoTracking().ToListAsync(ct); public Task<DataArchiveBatch?> GetArchiveBatchAsync(Guid id,CancellationToken ct=default)=>db.DataArchiveBatches.Include(x=>x.Items).AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id,ct);
}
public sealed class DataQualityApplicationService(EProcurementDbContext db) : IDataQualityApplicationService
{
    static List<DataQualityResultDto> last=[]; public Task<List<DataQualityCheck>> GetChecksAsync(CancellationToken ct=default)=>db.DataQualityChecks.AsNoTracking().ToListAsync(ct); public async Task<DataQualityCheck> CreateCheckAsync(DataQualityCheck c,CancellationToken ct=default){db.Add(c);await db.SaveChangesAsync(ct);return c;} public async Task<DataQualityCheck?> UpdateCheckAsync(Guid id,DataQualityCheck c,CancellationToken ct=default){var e=await db.DataQualityChecks.FindAsync([id],ct); if(e is null)return null; db.Entry(e).CurrentValues.SetValues(c); await db.SaveChangesAsync(ct); return e;}
    public async Task<List<DataQualityResultDto>> RunAsync(CancellationToken ct=default){last=[]; last.AddRange(await db.Suppliers.Where(s=>!s.Categories.Any()).Select(s=>new DataQualityResultDto("SUP-MISSING-CATEGORY","Supplier","Warning","Supplier missing category",s.Id)).ToListAsync(ct)); last.AddRange(await db.Tenders.Where(t=>t.PublicationDate!=null&&t.ClosingDate<=t.PublicationDate).Select(t=>new DataQualityResultDto("TEN-CLOSING-BEFORE-PUBLICATION","Tender","Error","Tender closing date before publication date",t.Id)).ToListAsync(ct)); db.DataProcessingLogs.Add(new(DataProcessingOperationType.DataQualityCheck,"Platform",null,"system","Data quality check run",$"{last.Count} issues",DateTimeOffset.UtcNow)); db.AuditEvents.Add(new AuditEvent("Data quality check run","Platform",Guid.Empty,"DataQuality","system",$"{last.Count} issues",DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return last;} public Task<List<DataQualityResultDto>> GetResultsAsync(CancellationToken ct=default)=>Task.FromResult(last);
}
public sealed class DataExportApplicationService(EProcurementDbContext db) : IDataExportApplicationService
{
    static string Mask(string? v)=>string.IsNullOrEmpty(v)?"":v.Length<=2?"****":v[..1]+"****"+v[^1..];
    public async Task<DataExportRequest> RequestExportAsync(DataExportRequestDto d,CancellationToken ct=default){if(d.IncludeSensitiveData&&!d.HasSensitivePermission){db.DataProcessingLogs.Add(new(DataProcessingOperationType.Export,d.EntityType,null,d.RequestedBy,"Sensitive export denied",d.Reason,DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); throw new UnauthorizedAccessException("DataExportSensitive permission is required.");} var r=new DataExportRequest($"EXP-{DateTimeOffset.UtcNow:yyyyMMddHHmmss}",d.EntityType,d.RequestedBy,DateTimeOffset.UtcNow,DataExportStatus.Completed,d.Format,d.IncludeSensitiveData,d.Reason,DateTimeOffset.UtcNow,$"exports/{Guid.NewGuid()}.csv"); db.Add(r); db.DataProcessingLogs.Add(new(DataProcessingOperationType.Export,d.EntityType,r.Id,d.RequestedBy,d.IncludeSensitiveData?"Sensitive export requested":"Export requested",d.Reason,DateTimeOffset.UtcNow)); db.AuditEvents.Add(new AuditEvent("Export completed",d.EntityType,r.Id,"Export",d.RequestedBy,d.Reason,DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return r;}
    public Task<List<DataExportRequest>> GetExportsAsync(CancellationToken ct=default)=>db.DataExportRequests.AsNoTracking().ToListAsync(ct); public Task<DataExportRequest?> GetExportAsync(Guid id,CancellationToken ct=default)=>db.DataExportRequests.FindAsync([id],ct).AsTask();
    public async Task<string> DownloadAsync(Guid id,string actor="system",CancellationToken ct=default){var r=await db.DataExportRequests.FindAsync([id],ct)??throw new InvalidOperationException("Export not found"); var sensitive=await db.DataPrivacyClassifications.Where(x=>x.EntityType==r.EntityType&&x.MaskInExports).Select(x=>x.FieldName).ToListAsync(ct); var sb=new StringBuilder(); if(r.EntityType=="Supplier"){sb.AppendLine("ReferenceNumber,LegalName,Email,PhoneNumber,TaxNumber"); foreach(var s in await db.Suppliers.ToListAsync(ct)){var email=sensitive.Contains("Email")&&!r.IncludeSensitiveData?Mask("supplier@example.com"):"supplier@example.com"; var phone=sensitive.Contains("PhoneNumber")&&!r.IncludeSensitiveData?Mask("+26650000000") : "+26650000000"; var tax=sensitive.Contains("TaxNumber")&&!r.IncludeSensitiveData?Mask("TAX-12345") : "TAX-12345"; sb.AppendLine($"{s.ReferenceNumber},{s.LegalName},{email},{phone},{tax}");}} else if(r.EntityType=="Tender"){sb.AppendLine("TenderNumber,Title,Status,ClosingDate"); foreach(var t in await db.Tenders.ToListAsync(ct))sb.AppendLine($"{t.TenderNumber},{t.Title},{t.Status},{t.ClosingDate:O}");} else sb.AppendLine("EntityType,ExportedAt\n"+r.EntityType+","+DateTimeOffset.UtcNow.ToString("O")); db.DataProcessingLogs.Add(new(DataProcessingOperationType.Export,r.EntityType,r.Id,actor,"Export downloaded",r.RequestNumber,DateTimeOffset.UtcNow)); db.AuditEvents.Add(new AuditEvent("Export downloaded",r.EntityType,r.Id,"Download",actor,r.RequestNumber,DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return sb.ToString();}
}
