using System.Security.Cryptography;
using System.Text.Json;
using Lca.EProcurement.Domain;
using Lca.EProcurement.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Lca.EProcurement.Application;

public sealed record DocumentUploadRequest(string EntityType, Guid EntityId, string DocumentType, string Title, string? Description, DocumentClassification Classification, bool IsPublic, string OriginalFileName, string ContentType, Stream File, string UploadedBy);
public sealed record DocumentUploadResponse(Guid DocumentId, Guid VersionId, string DocumentNumber, int VersionNumber, string ContentHash);
public sealed record DocumentSummaryDto(Guid Id, string DocumentNumber, string EntityType, Guid EntityId, string DocumentType, string Title, DocumentClassification Classification, DocumentStatus Status, int CurrentVersion, bool IsPublic, DateTimeOffset UploadedAt);
public sealed record DocumentDetailDto(DocumentRecord Record, DocumentVersion? CurrentVersion, List<DocumentVersionDto> Versions);
public sealed record DocumentVersionDto(Guid Id, int VersionNumber, string OriginalFileName, string ContentType, long FileSize, string ContentHash, bool IsCurrent, DateTimeOffset UploadedAt);
public sealed record DocumentAccessLogDto(Guid Id, Guid DocumentRecordId, Guid? DocumentVersionId, string UserId, string UserEmail, DocumentAction Action, bool AccessAllowed, string? DeniedReason, DateTimeOffset AccessedAt);
public sealed record DocumentRetentionPolicyDto(Guid? Id, string EntityType, string DocumentType, int RetentionPeriodDays, int ArchiveAfterDays, int? DeleteAfterDays, bool IsActive, string Actor);
public sealed record DocumentRequirementValidationResultDto(bool Passed, List<string> Errors, List<string> Warnings, List<DocumentRequirementLineDto> Items);
public sealed record DocumentRequirementLineDto(string DocumentType, int MinimumFiles, int MaximumFiles, int CurrentFiles, bool Passed, string? Message);
public sealed record StoredDocument(string StorageProvider, string StorageReference, string FileName, long FileSize, string ContentHash, string HashAlgorithm);
public sealed record DocumentDownloadDto(DocumentRecord Record, DocumentVersion Version, Stream Content);

public interface IDocumentStorageProvider { Task<StoredDocument> SaveAsync(Stream content, string originalFileName, CancellationToken ct = default); Task<Stream> OpenReadAsync(string storageReference, CancellationToken ct = default); Task DeleteAsync(string storageReference, CancellationToken ct = default); Task<bool> ExistsAsync(string storageReference, CancellationToken ct = default); Task<Dictionary<string,string>> GetMetadataAsync(string storageReference, CancellationToken ct = default); }
public interface ILocalDocumentStorageProvider : IDocumentStorageProvider { }
public interface IDocumentAccessService { Task<bool> CanAccessAsync(DocumentRecord doc, DocumentPermission permission, string userId, IEnumerable<string> roles, IEnumerable<string> permissions, CancellationToken ct = default); Task LogAsync(DocumentRecord doc, Guid? versionId, string userId, string userEmail, DocumentAction action, bool allowed, string? reason, CancellationToken ct = default); }
public interface IDocumentVirusScanner { Task<DocumentVirusScanResult> ScanAsync(DocumentVersion version, Stream content, CancellationToken ct = default); }
public interface IDocumentApplicationService { Task<DocumentUploadResponse> UploadAsync(DocumentUploadRequest request, CancellationToken ct = default); Task<DocumentUploadResponse> UploadNewVersionAsync(Guid id, DocumentUploadRequest request, string? reason, CancellationToken ct = default); Task<List<DocumentSummaryDto>> GetAsync(string? entityType, Guid? entityId, string? documentType, DocumentClassification? classification, DocumentStatus? status, bool? isPublic, CancellationToken ct = default); Task<DocumentDetailDto?> GetAsync(Guid id, CancellationToken ct = default); Task<DocumentDownloadDto> DownloadAsync(Guid id, Guid? versionId, string userId, string userEmail, IEnumerable<string> roles, IEnumerable<string> permissions, CancellationToken ct = default); Task<List<DocumentVersionDto>> GetVersionsAsync(Guid id, CancellationToken ct = default); Task<DocumentRecord?> PublishAsync(Guid id, string actor, bool isPublic, CancellationToken ct = default); Task<DocumentRecord?> ArchiveAsync(Guid id, string actor, string reason, CancellationToken ct = default); Task<DocumentRecord?> DeleteAsync(Guid id, string actor, CancellationToken ct = default); Task<List<DocumentAccessLogDto>> GetAccessLogAsync(Guid id, CancellationToken ct = default); }
public interface IDocumentRequirementValidationService { Task<DocumentRequirementValidationResultDto> ValidateRequiredDocumentsAsync(string entityType, Guid entityId, Guid documentRequirementSetId, CancellationToken ct = default); }
public interface IDocumentRetentionService { Task<List<DocumentRetentionPolicy>> GetPoliciesAsync(CancellationToken ct = default); Task<DocumentRetentionPolicy> SavePolicyAsync(DocumentRetentionPolicyDto dto, CancellationToken ct = default); Task<int> RunArchiveCheckAsync(string actor, CancellationToken ct = default); }
public interface IDocumentIntegrationService { Task<IntegrationMessage> SyncToExternalDmsAsync(Guid documentId, string actor, CancellationToken ct = default); }

public sealed class LocalDocumentStorageProvider(IConfiguration config) : ILocalDocumentStorageProvider
{
    readonly string root = config["Storage:Documents:RootPath"] ?? config["Documents:RootPath"] ?? "./App_Data/Documents";
    public async Task<StoredDocument> SaveAsync(Stream content, string originalFileName, CancellationToken ct = default)
    {
        var safeExt = Path.GetExtension(originalFileName).ToLowerInvariant();
        var fileName = $"{DateTimeOffset.UtcNow:yyyy/MM/dd}/{Guid.NewGuid():N}{safeExt}";
        var full = Path.GetFullPath(Path.Combine(root, fileName)); Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        await using var file = File.Create(full); using var sha = SHA256.Create(); await using var crypto = new CryptoStream(file, sha, CryptoStreamMode.Write);
        await content.CopyToAsync(crypto, ct); await crypto.FlushAsync(ct); crypto.FlushFinalBlock();
        return new("LocalFileSystem", fileName.Replace('\\','/'), Path.GetFileName(fileName), file.Length, Convert.ToHexString(sha.Hash!).ToLowerInvariant(), "SHA256");
    }
    public Task<Stream> OpenReadAsync(string storageReference, CancellationToken ct = default) => Task.FromResult<Stream>(File.OpenRead(Path.GetFullPath(Path.Combine(root, storageReference))));
    public Task DeleteAsync(string storageReference, CancellationToken ct = default) { var p=Path.GetFullPath(Path.Combine(root, storageReference)); if(File.Exists(p)) File.Delete(p); return Task.CompletedTask; }
    public Task<bool> ExistsAsync(string storageReference, CancellationToken ct = default) => Task.FromResult(File.Exists(Path.GetFullPath(Path.Combine(root, storageReference))));
    public Task<Dictionary<string,string>> GetMetadataAsync(string storageReference, CancellationToken ct = default) { var i=new FileInfo(Path.GetFullPath(Path.Combine(root, storageReference))); return Task.FromResult(new Dictionary<string,string>{{"Length", i.Exists?i.Length.ToString():"0"},{"StorageReference", storageReference}}); }
}
public sealed class NoOpVirusScanner : IDocumentVirusScanner { public Task<DocumentVirusScanResult> ScanAsync(DocumentVersion version, Stream content, CancellationToken ct = default) => Task.FromResult(new DocumentVirusScanResult(version.Id, "NoOpDevelopmentScanner", VirusScanStatus.Skipped, DateTimeOffset.UtcNow, "Skipped", null, "Development placeholder; external scanner can replace this service.")); }

public sealed class DocumentAccessService(EProcurementDbContext db, IConfiguration config) : IDocumentAccessService
{
    public Task<bool> CanAccessAsync(DocumentRecord d, DocumentPermission p, string userId, IEnumerable<string> roles, IEnumerable<string> perms, CancellationToken ct = default)
    {
        var ps=perms.ToHashSet(StringComparer.OrdinalIgnoreCase); var rs=roles.ToHashSet(StringComparer.OrdinalIgnoreCase);
        if (rs.Contains("System Administrator") || rs.Contains("Administrator")) return Task.FromResult(true);
        if (d.Status == DocumentStatus.Quarantined || d.Status == DocumentStatus.Deleted) return Task.FromResult(false);
        if (d.Status == DocumentStatus.Archived && !ps.Contains("Document.Archive.View")) return Task.FromResult(false);
        if (d.Classification == DocumentClassification.Public && d.IsPublic && d.Status == DocumentStatus.Active && p is DocumentPermission.ViewMetadata or DocumentPermission.Download) return Task.FromResult(true);
        if (d.Classification == DocumentClassification.SealedBid && p == DocumentPermission.Download && !bool.Parse(config["Documents:AllowSealedBidDocumentDownloadBeforeOpening"] ?? "false")) return Task.FromResult(false);
        if (d.AccessRules.Any(r => (r.UserId == userId || rs.Contains(r.RoleCode)) && r.Permission == p && (r.StartsAt == null || r.StartsAt <= DateTimeOffset.UtcNow) && (r.EndsAt == null || r.EndsAt >= DateTimeOffset.UtcNow))) return Task.FromResult(true);
        return Task.FromResult(ps.Contains($"Document.{p}") || (p == DocumentPermission.Download && ps.Contains("Document.Download")));
    }
    public async Task LogAsync(DocumentRecord d, Guid? versionId, string userId, string userEmail, DocumentAction action, bool allowed, string? reason, CancellationToken ct = default) { db.DocumentAccessLogs.Add(new(d.Id, versionId, userId, userEmail, action, allowed, reason, null, null, DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); }
}

public sealed class DocumentApplicationService(EProcurementDbContext db, IDocumentStorageProvider storage, IDocumentAccessService access, IDocumentVirusScanner scanner) : IDocumentApplicationService
{
    public async Task<DocumentUploadResponse> UploadAsync(DocumentUploadRequest r, CancellationToken ct = default) { var doc = new DocumentRecord($"DOC-{DateTimeOffset.UtcNow:yyyyMMddHHmmss}-{Random.Shared.Next(1000,9999)}", r.EntityType, r.EntityId, r.DocumentType, r.Title, r.Description, r.Classification, DocumentStatus.Active, null, r.IsPublic && r.Classification==DocumentClassification.Public, r.Classification is DocumentClassification.Confidential or DocumentClassification.SealedBid or DocumentClassification.Restricted, r.UploadedBy, DateTimeOffset.UtcNow); db.DocumentRecords.Add(doc); await db.SaveChangesAsync(ct); return await AddVersion(doc, r, null, DocumentAction.Uploaded, ct); }
    public async Task<DocumentUploadResponse> UploadNewVersionAsync(Guid id, DocumentUploadRequest r, string? reason, CancellationToken ct = default) { var doc=await db.DocumentRecords.Include(x=>x.Versions).SingleAsync(x=>x.Id==id,ct); foreach(var v in doc.Versions.Where(x=>x.IsCurrent)) db.Entry(v).CurrentValues[nameof(DocumentVersion.IsCurrent)] = false; return await AddVersion(doc,r,reason,DocumentAction.Versioned,ct); }
    async Task<DocumentUploadResponse> AddVersion(DocumentRecord doc, DocumentUploadRequest r, string? reason, DocumentAction action, CancellationToken ct) { var stored=await storage.SaveAsync(r.File,r.OriginalFileName,ct); var version=new DocumentVersion(doc.Id, (doc.Versions.Count==0?0:doc.Versions.Max(x=>x.VersionNumber))+1, stored.FileName, Path.GetFileName(r.OriginalFileName), r.ContentType, Path.GetExtension(r.OriginalFileName).ToLowerInvariant(), stored.FileSize, stored.StorageProvider, stored.StorageReference, stored.ContentHash, stored.HashAlgorithm, r.UploadedBy, DateTimeOffset.UtcNow, true, reason); db.DocumentVersions.Add(version); await db.SaveChangesAsync(ct); db.Entry(doc).CurrentValues[nameof(DocumentRecord.CurrentVersionId)] = version.Id; db.DocumentAccessLogs.Add(new(doc.Id, version.Id, r.UploadedBy, r.UploadedBy, action, true, null, null, null, DateTimeOffset.UtcNow)); await using var read=await storage.OpenReadAsync(stored.StorageReference, ct); db.DocumentVirusScanResults.Add(await scanner.ScanAsync(version, read, ct)); db.AuditEvents.Add(new($"Document {action}", doc.EntityType, doc.EntityId, doc.DocumentNumber, r.UploadedBy, $"{doc.Title} v{version.VersionNumber}", DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return new(doc.Id, version.Id, doc.DocumentNumber, version.VersionNumber, stored.ContentHash); }
    public Task<List<DocumentSummaryDto>> GetAsync(string? e, Guid? id, string? dt, DocumentClassification? c, DocumentStatus? s, bool? pub, CancellationToken ct = default) => db.DocumentRecords.AsNoTracking().Include(x=>x.Versions).Where(x=>(e==null||x.EntityType==e)&&(id==null||x.EntityId==id)&&(dt==null||x.DocumentType==dt)&&(c==null||x.Classification==c)&&(s==null||x.Status==s)&&(pub==null||x.IsPublic==pub) && x.Status != DocumentStatus.Archived && x.Status != DocumentStatus.Deleted).Select(x=>new DocumentSummaryDto(x.Id,x.DocumentNumber,x.EntityType,x.EntityId,x.DocumentType,x.Title,x.Classification,x.Status,x.Versions.Where(v=>v.IsCurrent).Select(v=>v.VersionNumber).FirstOrDefault(),x.IsPublic,x.CreatedAt)).ToListAsync(ct);
    public async Task<DocumentDetailDto?> GetAsync(Guid id, CancellationToken ct = default) { var d=await db.DocumentRecords.AsNoTracking().Include(x=>x.Versions).SingleOrDefaultAsync(x=>x.Id==id,ct); return d==null?null:new(d,d.Versions.SingleOrDefault(v=>v.Id==d.CurrentVersionId),d.Versions.OrderByDescending(v=>v.VersionNumber).Select(ToDto).ToList()); }
    public async Task<DocumentDownloadDto> DownloadAsync(Guid id, Guid? versionId, string userId, string email, IEnumerable<string> roles, IEnumerable<string> perms, CancellationToken ct = default) { var d=await db.DocumentRecords.Include(x=>x.Versions).Include(x=>x.AccessRules).SingleAsync(x=>x.Id==id,ct); var v=d.Versions.Single(x=> versionId==null?x.Id==d.CurrentVersionId:x.Id==versionId); var ok=await access.CanAccessAsync(d,DocumentPermission.Download,userId,roles,perms,ct); await access.LogAsync(d,v.Id,userId,email,ok?DocumentAction.Downloaded:DocumentAction.AccessDenied,ok,ok?null:"Document download denied",ct); if(!ok) throw new UnauthorizedAccessException("Document download denied."); db.AuditEvents.Add(new("Document downloaded", d.EntityType, d.EntityId, d.DocumentNumber, userId, d.Title, DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return new(d,v,await storage.OpenReadAsync(v.StorageReference,ct)); }
    public Task<List<DocumentVersionDto>> GetVersionsAsync(Guid id, CancellationToken ct = default) => db.DocumentVersions.AsNoTracking().Where(x=>x.DocumentRecordId==id).OrderByDescending(x=>x.VersionNumber).Select(x=>ToDto(x)).ToListAsync(ct);
    public async Task<DocumentRecord?> PublishAsync(Guid id, string actor, bool pub, CancellationToken ct = default) { var d=await db.DocumentRecords.FindAsync([id],ct); if(d==null)return null; db.Entry(d).CurrentValues[nameof(DocumentRecord.IsPublic)]=pub; db.Entry(d).CurrentValues[nameof(DocumentRecord.Status)]=DocumentStatus.Active; db.Entry(d).CurrentValues[nameof(DocumentRecord.UpdatedBy)]=actor; db.Entry(d).CurrentValues[nameof(DocumentRecord.UpdatedAt)]=DateTimeOffset.UtcNow; db.AuditEvents.Add(new(pub?"Document published":"Document unpublished",d.EntityType,d.EntityId,d.DocumentNumber,actor,d.Title,DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return d; }
    public async Task<DocumentRecord?> ArchiveAsync(Guid id, string actor, string reason, CancellationToken ct = default) { var d=await db.DocumentRecords.FindAsync([id],ct); if(d==null)return null; db.Entry(d).CurrentValues[nameof(DocumentRecord.Status)]=DocumentStatus.Archived; db.DocumentArchiveRecords.Add(new(id,DateTimeOffset.UtcNow,actor,reason,null,"Archived")); db.AuditEvents.Add(new("Document archived",d.EntityType,d.EntityId,d.DocumentNumber,actor,reason,DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return d; }
    public async Task<DocumentRecord?> DeleteAsync(Guid id, string actor, CancellationToken ct = default) { var d=await db.DocumentRecords.FindAsync([id],ct); if(d==null)return null; db.Entry(d).CurrentValues[nameof(DocumentRecord.Status)]=DocumentStatus.Deleted; db.AuditEvents.Add(new("Document deleted",d.EntityType,d.EntityId,d.DocumentNumber,actor,d.Title,DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return d; }
    public Task<List<DocumentAccessLogDto>> GetAccessLogAsync(Guid id, CancellationToken ct = default) => db.DocumentAccessLogs.AsNoTracking().Where(x=>x.DocumentRecordId==id).OrderByDescending(x=>x.AccessedAt).Select(x=>new DocumentAccessLogDto(x.Id,x.DocumentRecordId,x.DocumentVersionId,x.UserId,x.UserEmail,x.Action,x.AccessAllowed,x.DeniedReason,x.AccessedAt)).ToListAsync(ct);
    static DocumentVersionDto ToDto(DocumentVersion x)=>new(x.Id,x.VersionNumber,x.OriginalFileName,x.ContentType,x.FileSize,x.ContentHash,x.IsCurrent,x.UploadedAt);
}

public sealed class DocumentRequirementValidationService(EProcurementDbContext db) : IDocumentRequirementValidationService
{ public async Task<DocumentRequirementValidationResultDto> ValidateRequiredDocumentsAsync(string entityType, Guid entityId, Guid setId, CancellationToken ct = default) { var reqs=await db.DocumentRequirements.AsNoTracking().Where(x=>x.DocumentRequirementSetId==setId).ToListAsync(ct); var docs=await db.DocumentRecords.AsNoTracking().Include(x=>x.Versions).Where(x=>x.EntityType==entityType&&x.EntityId==entityId&&x.Status==DocumentStatus.Active).ToListAsync(ct); var errors=new List<string>(); var items=new List<DocumentRequirementLineDto>(); foreach(var r in reqs){ var matches=docs.Where(d=>d.DocumentType==r.DocumentType).ToList(); var ok=(!r.Required||matches.Count>=r.MinimumFiles)&&matches.Count<=r.MaximumFiles; foreach(var d in matches) foreach(var v in d.Versions.Where(v=>v.IsCurrent)){ if(!string.IsNullOrWhiteSpace(r.AllowedExtensions)&&!r.AllowedExtensions.Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries).Contains(v.FileExtension,StringComparer.OrdinalIgnoreCase)) { ok=false; errors.Add($"{r.DocumentType} extension {v.FileExtension} is not allowed."); } if(r.MaximumFileSize>0&&v.FileSize>r.MaximumFileSize){ok=false; errors.Add($"{r.DocumentType} exceeds maximum file size.");}} if(!ok) errors.Add($"{r.DocumentType} requirement not satisfied."); items.Add(new(r.DocumentType,r.MinimumFiles,r.MaximumFiles,matches.Count,ok,ok?null:"Requirement not satisfied")); } db.AuditEvents.Add(new(errors.Count==0?"Document requirement validation passed":"Document requirement validation failed",entityType,entityId,setId.ToString(),"system",JsonSerializer.Serialize(errors),DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return new(errors.Count==0,errors,[],items); } }
public sealed class DocumentRetentionService(EProcurementDbContext db, IDocumentApplicationService docs) : IDocumentRetentionService { public Task<List<DocumentRetentionPolicy>> GetPoliciesAsync(CancellationToken ct=default)=>db.DocumentRetentionPolicies.AsNoTracking().ToListAsync(ct); public async Task<DocumentRetentionPolicy> SavePolicyAsync(DocumentRetentionPolicyDto x,CancellationToken ct=default){ DocumentRetentionPolicy p; if(x.Id is Guid id && await db.DocumentRetentionPolicies.FindAsync([id],ct) is { } e){ db.Entry(e).CurrentValues[nameof(DocumentRetentionPolicy.RetentionPeriodDays)]=x.RetentionPeriodDays; db.Entry(e).CurrentValues[nameof(DocumentRetentionPolicy.ArchiveAfterDays)]=x.ArchiveAfterDays; db.Entry(e).CurrentValues[nameof(DocumentRetentionPolicy.DeleteAfterDays)]=x.DeleteAfterDays; db.Entry(e).CurrentValues[nameof(DocumentRetentionPolicy.IsActive)]=x.IsActive; p=e; db.AuditEvents.Add(new("Document retention policy updated",x.EntityType,Guid.Empty,x.DocumentType,x.Actor,"Updated",DateTimeOffset.UtcNow)); } else { p=new(x.EntityType,x.DocumentType,x.RetentionPeriodDays,x.ArchiveAfterDays,x.DeleteAfterDays,x.IsActive,DateTimeOffset.UtcNow,x.Actor); db.DocumentRetentionPolicies.Add(p); db.AuditEvents.Add(new("Document retention policy created",x.EntityType,Guid.Empty,x.DocumentType,x.Actor,"Created",DateTimeOffset.UtcNow)); } await db.SaveChangesAsync(ct); return p;} public Task<int> RunArchiveCheckAsync(string actor,CancellationToken ct=default)=>Task.FromResult(0); }
public sealed class DocumentIntegrationService(EProcurementDbContext db) : IDocumentIntegrationService { public async Task<IntegrationMessage> SyncToExternalDmsAsync(Guid documentId,string actor,CancellationToken ct=default){ var d=await db.DocumentRecords.AsNoTracking().SingleAsync(x=>x.Id==documentId,ct); var endpoint=await db.IntegrationEndpoints.AsNoTracking().FirstOrDefaultAsync(x=>x.SystemType==IntegrationSystemType.DocumentManagement&&x.IsEnabled,ct); var msg=new IntegrationMessage(endpoint?.Id,"DocumentRecord",d.Id,IntegrationDirection.Outbound,JsonSerializer.Serialize(new{d.Id,d.DocumentNumber,d.EntityType,d.EntityId,d.DocumentType,d.Title,d.IsPublic,d.Classification}),endpoint is null?IntegrationMessageStatus.PendingExternalConfiguration:IntegrationMessageStatus.Pending,DateTimeOffset.UtcNow,null,endpoint is null?"No DocumentManagement endpoint configured":null); db.IntegrationMessages.Add(msg); db.DocumentIntegrationReferences.Add(new(d.Id,d.EntityType,d.EntityId,d.CurrentVersionId?.ToString()??d.DocumentNumber,null,endpoint is null?"PendingExternalConfiguration":"Pending",DateTimeOffset.UtcNow)); db.AuditEvents.Add(new("Document metadata sync requested",d.EntityType,d.EntityId,d.DocumentNumber,actor,"External DMS metadata sync",DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return msg;} }
