using System.Text.Json;
using Lca.EProcurement.Domain;
using Lca.EProcurement.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Lca.EProcurement.Application;

public sealed record CoverageDto(int Total, int Covered, int PartiallyCovered, int NeedsConfiguration, int NotCovered, decimal CoveragePercentage, DateTimeOffset? LastVerifiedDate, List<AreaCoverageDto> Areas);
public sealed record AreaCoverageDto(string Area, int Total, int Covered, int PartiallyCovered, int NeedsConfiguration, int NotCovered, decimal CoveragePercentage);
public sealed record DemoCheckDto(string Name, bool Passed, string Message, string? EvidenceRoute = null);
public sealed record DemoStatusDto(bool Ready, List<DemoCheckDto> Checks);
public sealed record ReadinessCategoryDto(string Category, int ScorePercentage, ReadinessStatus Status, List<string> CriticalIssues, List<string> Recommendations, List<string> EvidenceLinks);
public sealed record EvidencePackDto(DateTimeOffset ExportedAt, List<ComplianceRequirement> ComplianceMatrix, List<ProposalCommitment> ProposalCommitments, List<ReadinessCategoryDto> ReadinessAssessment, List<DemoStep> DemoScript, List<UatTestSuite> UatTestSuites, List<TrainingModule> TrainingModules, List<ImplementationPhase> ImplementationPhases, List<HandoverChecklist> HandoverChecklists, List<SupportServiceLevel> SupportServiceLevels);
public sealed record CreateUatSuiteDto(string Code, string Name, string Description, string Module, string CreatedBy);
public sealed record CreateUatRunDto(Guid SuiteId, string ExecutedBy, string Notes);
public sealed record RecordUatResultDto(Guid TestCaseId, UatResultStatus Result, string ActualResult, string EvidenceNotes, string? DefectReference, string ExecutedBy);

public interface IRfpEvidenceApplicationService
{
    Task<List<ComplianceRequirement>> GetRequirementsAsync(CancellationToken ct = default);
    Task<ComplianceRequirement?> GetRequirementAsync(Guid id, CancellationToken ct = default);
    Task<ComplianceRequirement> CreateRequirementAsync(ComplianceRequirement requirement, CancellationToken ct = default);
    Task<ComplianceRequirement?> UpdateRequirementAsync(Guid id, ComplianceRequirement requirement, CancellationToken ct = default);
    Task<ComplianceRequirement?> VerifyRequirementAsync(Guid id, string verifiedBy, CancellationToken ct = default);
    Task<CoverageDto> GetCoverageAsync(CancellationToken ct = default);
    Task<List<ProposalCommitment>> GetCommitmentsAsync(CancellationToken ct = default);
    Task<EvidencePackDto> ExportPackAsync(CancellationToken ct = default);
}
public interface IDemoDataVerificationService { Task<DemoStatusDto> GetStatusAsync(CancellationToken ct = default); Task<DemoStatusDto> VerifyAsync(CancellationToken ct = default); Task<bool> ResetAsync(bool allowReset, CancellationToken ct = default); Task ReseedAsync(CancellationToken ct = default); }
public interface IReadinessAssessmentService { Task<List<ReadinessCategoryDto>> GetAsync(CancellationToken ct = default); Task<ReadinessCategoryDto?> GetAsync(string category, CancellationToken ct = default); }

public sealed class RfpEvidenceApplicationService(EProcurementDbContext db, IReadinessAssessmentService readiness) : IRfpEvidenceApplicationService
{
    public Task<List<ComplianceRequirement>> GetRequirementsAsync(CancellationToken ct = default) => db.ComplianceRequirements.AsNoTracking().OrderBy(x => x.RequirementCode).ToListAsync(ct);
    public Task<ComplianceRequirement?> GetRequirementAsync(Guid id, CancellationToken ct = default) => db.ComplianceRequirements.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, ct);
    public async Task<ComplianceRequirement> CreateRequirementAsync(ComplianceRequirement r, CancellationToken ct = default) { db.ComplianceRequirements.Add(r); await Audit("Compliance requirement updated", r.Id, r.RequirementCode, ct); await db.SaveChangesAsync(ct); return r; }
    public async Task<ComplianceRequirement?> UpdateRequirementAsync(Guid id, ComplianceRequirement r, CancellationToken ct = default) { var e = await db.ComplianceRequirements.FindAsync([id], ct); if (e is null) return null; db.Entry(e).CurrentValues.SetValues(r with { UpdatedAt = DateTimeOffset.UtcNow }); await Audit("Compliance requirement updated", id, r.RequirementCode, ct); await db.SaveChangesAsync(ct); return e; }
    public async Task<ComplianceRequirement?> VerifyRequirementAsync(Guid id, string verifiedBy, CancellationToken ct = default) { var e = await db.ComplianceRequirements.FindAsync([id], ct); if (e is null) return null; db.Entry(e).CurrentValues[nameof(ComplianceRequirement.LastVerifiedAt)] = DateTimeOffset.UtcNow; db.Entry(e).CurrentValues[nameof(ComplianceRequirement.VerifiedBy)] = verifiedBy; db.Entry(e).CurrentValues[nameof(ComplianceRequirement.UpdatedAt)] = DateTimeOffset.UtcNow; await Audit("Compliance requirement verified", id, e.RequirementCode, ct); await db.SaveChangesAsync(ct); return e; }
    public async Task<CoverageDto> GetCoverageAsync(CancellationToken ct = default) { var items = await db.ComplianceRequirements.AsNoTracking().ToListAsync(ct); var areas = items.GroupBy(x => x.RequirementArea).Select(g => Area(g.Key, g.ToList())).OrderBy(x => x.Area).ToList(); var all = Area("All", items); return new(all.Total, all.Covered, all.PartiallyCovered, all.NeedsConfiguration, all.NotCovered, all.CoveragePercentage, items.Max(x => x.LastVerifiedAt), areas); }
    public Task<List<ProposalCommitment>> GetCommitmentsAsync(CancellationToken ct = default) => db.ProposalCommitments.AsNoTracking().OrderBy(x => x.CommitmentCode).ToListAsync(ct);
    public async Task<EvidencePackDto> ExportPackAsync(CancellationToken ct = default) { var pack = new EvidencePackDto(DateTimeOffset.UtcNow, await GetRequirementsAsync(ct), await GetCommitmentsAsync(ct), await readiness.GetAsync(ct), await db.DemoSteps.AsNoTracking().OrderBy(x=>x.StepNumber).ToListAsync(ct), await db.UatTestSuites.AsNoTracking().Include(x=>x.TestCases).ToListAsync(ct), await db.TrainingModules.AsNoTracking().Include(x=>x.Lessons).ToListAsync(ct), await db.ImplementationPhases.AsNoTracking().Include(x=>x.Milestones).ThenInclude(x=>x.Tasks).ToListAsync(ct), await db.HandoverChecklists.AsNoTracking().Include(x=>x.Items).ToListAsync(ct), await db.SupportServiceLevels.AsNoTracking().ToListAsync(ct)); await Audit("Evidence pack exported", Guid.Empty, "RFP evidence pack JSON export without secrets", ct); await db.SaveChangesAsync(ct); return pack; }
    static AreaCoverageDto Area(string area, List<ComplianceRequirement> xs) { var total=xs.Count; var covered=xs.Count(x=>x.Status==ComplianceStatus.Covered); var partial=xs.Count(x=>x.Status==ComplianceStatus.PartiallyCovered); var need=xs.Count(x=>x.Status==ComplianceStatus.NeedsConfiguration); var not=xs.Count(x=>x.Status==ComplianceStatus.NotCovered); var pct=total==0?0:Math.Round(((covered + partial*.5m)/total)*100,2); return new(area,total,covered,partial,need,not,pct); }
    async Task Audit(string action, Guid id, string details, CancellationToken ct) => await db.AuditEvents.AddAsync(new AuditEvent(action, "RfpEvidence", id, "System", "system", details, DateTimeOffset.UtcNow), ct);
}

public sealed class DemoDataVerificationService(EProcurementDbContext db) : IDemoDataVerificationService
{
    public async Task<DemoStatusDto> GetStatusAsync(CancellationToken ct = default) { var checks = new List<DemoCheckDto> { new("Demo users exist", await db.ApplicationUsers.CountAsync(ct) >= 3, "Core presenter users are seeded."), new("Demo roles exist", await db.Roles.CountAsync(ct) >= 3, "Role catalogue is present."), new("Permissions assigned", await db.RolePermissions.AnyAsync(ct), "Role permissions are assigned."), new("Annual procurement plan exists", await db.AnnualProcurementPlans.AnyAsync(ct), "APP-2026-ICT expected.", "/app/planning"), new("Budget exists", await db.Budgets.AnyAsync(ct), "Budget validation can be shown."), new("Requisition exists", await db.Requisitions.AnyAsync(ct), "REQ-2026-ICT-001 expected."), new("Tender exists", await db.Tenders.AnyAsync(ct), "LCA-RFP-2026-ICT-001 expected."), new("Public tender publication exists", await db.PublicTenderPublications.AnyAsync(ct), "Public opportunity is visible.", "/public/opportunities/LCA-RFP-2026-ICT-001"), new("At least three suppliers exist", await db.Suppliers.CountAsync(ct) >= 3, "Supplier competition can be demonstrated."), new("At least three bid submissions exist", await db.BidSubmissions.CountAsync(ct) >= 3, "Bid comparison can be demonstrated."), new("Sealed bid exists", await db.SealedBidEnvelopes.AnyAsync(ct), "Sealed bid protection evidence is present."), new("Bid opening session exists", await db.BidOpeningSessions.AnyAsync(ct), "Controlled opening can be shown."), new("Evaluation session exists", await db.EvaluationSessions.AnyAsync(ct), "Evaluation workflow can be shown."), new("Award exists", await db.Awards.AnyAsync(ct), "Award approval can be shown."), new("Purchase order exists", await db.PurchaseOrders.AnyAsync(ct), "PO generation can be shown."), new("Contract exists", await db.Contracts.AnyAsync(ct), "Contract integration can be shown."), new("Audit events exist", await db.AuditEvents.AnyAsync(ct), "Auditability evidence is present."), new("Reporting data exists", await db.KpiDefinitions.AnyAsync(ct) || await db.ReportDefinitions.AnyAsync(ct), "Dashboard inputs are present.") }; return new(checks.All(x=>x.Passed), checks); }
    public async Task<DemoStatusDto> VerifyAsync(CancellationToken ct = default) { var s=await GetStatusAsync(ct); db.AuditEvents.Add(new AuditEvent("Demo data verified", "Demo", Guid.Empty, "Verify", "system", JsonSerializer.Serialize(s.Checks.Select(c=>new{c.Name,c.Passed})), DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return s; }
    public async Task<bool> ResetAsync(bool allowReset, CancellationToken ct = default) { db.AuditEvents.Add(new AuditEvent("Demo reset attempted", "Demo", Guid.Empty, "Reset", "system", allowReset ? "Allowed" : "Blocked by Operations.AllowDemoReset", DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return allowReset; }
    public async Task ReseedAsync(CancellationToken ct = default) { await SeedData.SeedAsync(db, ct); db.AuditEvents.Add(new AuditEvent("Demo data reseeded", "Demo", Guid.Empty, "Reseed", "system", "SeedData.SeedAsync executed", DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); }
}

public sealed class ReadinessAssessmentService(EProcurementDbContext db) : IReadinessAssessmentService
{
    public async Task<List<ReadinessCategoryDto>> GetAsync(CancellationToken ct = default) { var cov = await db.ComplianceRequirements.AsNoTracking().ToListAsync(ct); var demo = await new DemoDataVerificationService(db).GetStatusAsync(ct); var uatTotal=await db.UatTestCases.CountAsync(ct); var training=await db.TrainingModules.CountAsync(ct); var support=await db.SupportServiceLevels.CountAsync(x=>x.IsActive, ct); var list = new List<ReadinessCategoryDto> { Build("Functional Coverage", Score(cov), "/app/rfp-evidence/coverage"), Build("Security Readiness", Score(cov.Where(x=>x.RequirementType==ComplianceRequirementType.Security).ToList()), "/app/rfp-evidence/compliance-matrix"), Build("Data Readiness", demo.Checks.Count(x=>x.Passed)*100/Math.Max(1,demo.Checks.Count), "/app/demo"), Build("Integration Readiness", Score(cov.Where(x=>x.RequirementType==ComplianceRequirementType.Integration).ToList()), "/app/rfp-evidence/integrations"), Build("Reporting Readiness", Score(cov.Where(x=>x.RequirementType==ComplianceRequirementType.Reporting).ToList()), "/app/reporting"), Build("Operational Readiness", support>0?80:30, "/app/support-maintenance"), Build("Training Readiness", training>0?85:20, "/app/training"), Build("UAT Readiness", uatTotal>0?75:20, "/app/uat"), Build("Support Readiness", support>=4?90:40, "/app/support-maintenance") }; db.AuditEvents.Add(new AuditEvent("Readiness assessment viewed", "Readiness", Guid.Empty, "View", "system", "All categories", DateTimeOffset.UtcNow)); await db.SaveChangesAsync(ct); return list; }
    public async Task<ReadinessCategoryDto?> GetAsync(string category, CancellationToken ct = default) => (await GetAsync(ct)).FirstOrDefault(x => string.Equals(x.Category, category, StringComparison.OrdinalIgnoreCase));
    static int Score(List<ComplianceRequirement> xs) => xs.Count==0?0:(int)Math.Round(xs.Average(x => x.Status==ComplianceStatus.Covered?100:x.Status==ComplianceStatus.PartiallyCovered?60:x.Status==ComplianceStatus.NeedsConfiguration?40:x.Status==ComplianceStatus.NotApplicable?100:0));
    static ReadinessCategoryDto Build(string cat, int score, string link) => new(cat, score, score>=85?ReadinessStatus.Ready:score>=70?ReadinessStatus.MostlyReady:score>=40?ReadinessStatus.NeedsAttention:ReadinessStatus.NotReady, score>=70?[]:["Configuration or evidence gaps remain."], score>=85?["Maintain evidence currency."]:["Complete seeded evidence, verify requirements, and close UAT gaps."], [link]);
}
