import { useEffect, useState } from "react";
import { PageHeader } from "../../components/ui/PageHeader";
import { Panel } from "../../components/ui/Panel";
import { MetricCard } from "../../components/ui/MetricCard";
import { dataGovernanceApi, type AnyRecord } from "../../services/dataGovernanceApi";
function Table({ rows }: { rows: AnyRecord[] }) { const keys = Array.from(new Set(rows.flatMap((r) => Object.keys(r)))).filter((k) => !["fields", "items", "issues"].includes(k)).slice(0, 8); if (!rows.length) return <p className="text-muted mb-0">No records available.</p>; return <div className="table-responsive"><table className="table table-sm table-striped"><thead><tr>{keys.map((k) => <th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={String(r.id ?? i)}>{keys.map((k) => <td key={k}>{String(r[k] ?? "")}</td>)}</tr>)}</tbody></table></div>; }
function useRows(loader: () => Promise<{data: AnyRecord[]}>) { const [rows,setRows]=useState<AnyRecord[]>([]); useEffect(()=>{loader().then(r=>setRows(r.data));},[]); return rows; }
export function DataGovernanceDashboardPage() { const [d,setD]=useState<AnyRecord>({}); useEffect(()=>{dataGovernanceApi.dashboard().then(r=>setD(r.data));},[]); const metrics=["activePolicies","retentionRules","privacyClassifications","migrationBatches","dataQualityChecks","archiveBatches","exportRequests","processingLogs"]; return <><PageHeader title="Data Governance" description="LCA data ownership, retention, privacy, migration readiness and evidence dashboard." /><div className="row">{metrics.map(m=><div className="col-md-3" key={m}><MetricCard label={m} value={String(d[m] ?? 0)} /></div>)}</div></>; }
export function PoliciesPage(){return <Simple title="Data Governance Policies" load={dataGovernanceApi.policies}/>}
export function RetentionPage(){return <Simple title="Retention Rules" load={dataGovernanceApi.retention}/>}
export function PrivacyPage(){return <Simple title="Privacy Classifications" load={dataGovernanceApi.privacy}/>}
export function ProcessingLogsPage(){return <Simple title="Processing Logs" load={dataGovernanceApi.logs}/>}
export function MigrationPage(){const rows=useRows(dataGovernanceApi.templates); const batches=useRows(dataGovernanceApi.batches); return <><PageHeader title="Migration" description="Upload CSV, validate, import and keep migration evidence."/><Panel title="Templates"><Table rows={rows}/></Panel><Panel title="Batches"><Table rows={batches}/></Panel></>}
export function MigrationBatchDetailPage({id}:{id:string}){const [b,setB]=useState<AnyRecord>({}); useEffect(()=>{dataGovernanceApi.batch(id).then(r=>setB(r.data));},[id]); return <><PageHeader title="Migration Batch Detail" description="Summary, rows, validation issues, imported records and audit timeline."/><Panel title="Batch"><pre>{JSON.stringify(b,null,2)}</pre></Panel></>}
export function DataQualityPage(){const checks=useRows(dataGovernanceApi.qualityChecks); const [results,setResults]=useState<AnyRecord[]>([]); return <><PageHeader title="Data Quality" description="Run checks and review issues by entity and severity."/><button className="btn btn-primary mb-3" onClick={()=>dataGovernanceApi.runQuality().then(r=>setResults(r.data))}>Run checks</button><Panel title="Checks"><Table rows={checks}/></Panel><Panel title="Results"><Table rows={results}/></Panel></>}
export function DataArchivePage(){return <Simple title="Data Archive" description="Preview eligible records, create batches and review archived markers." load={dataGovernanceApi.archiveBatches}/>}
export function DataExportsPage(){const rows=useRows(dataGovernanceApi.exports); return <><PageHeader title="Data Exports" description="Request CSV exports of LCA-owned data with privacy masking by default."/><Panel title="Export requests"><Table rows={rows}/></Panel></>}
function Simple({title,description,load}:{title:string;description?:string;load:()=>Promise<{data:AnyRecord[]}>}){const rows=useRows(load);return <><PageHeader title={title} description={description ?? "Governance records for audit-ready administration."}/><Panel title={title}><Table rows={rows}/></Panel></>}
