import { useEffect, useState } from "react";
import { PageHeader } from "../../components/ui/PageHeader";
import { MetricCard } from "../../components/ui/MetricCard";
import { DataTable } from "../../components/ui/DataTable";
import { Panel } from "../../components/ui/Panel";
import { LoadingState } from "../../components/ui/LoadingState";
import { apiGet, apiPost } from "../../services/apiClient";
function useApi<T>(path:string,fallback:T){const [data,setData]=useState(fallback);const [loading,setLoading]=useState(true);useEffect(()=>{void apiGet<T>(path,fallback).then(r=>{setData(r.data);setLoading(false);});},[path]);return{data,loading};}
const status=(s:string)=><span className={`badge ${s.includes("Not")||s==="Fail"?"text-bg-danger":s.includes("Needs")||s==="Blocked"||s==="Open"?"text-bg-warning":s.includes("Mostly")?"text-bg-info":"text-bg-success"}`}>{s.replace(/([A-Z])/g," $1").trim()}</span>;
export function DemoControlCenterPage(){const {data}=useApi<any>("/api/demo/script",[]);const {data:st}=useApi<any>("/api/demo/status",{ready:false,checks:[]});return <><PageHeader title="End-to-end Demo Control Center" description="Supply and Delivery of ICT Equipment for LCA Regional Monitoring Offices."/><div className="grid cols-3"><MetricCard label="Demo readiness" value={st.ready?"Ready":"Needs attention"}/><MetricCard label="Checks passed" value={st.checks.filter((x:any)=>x.passed).length}/><MetricCard label="Script steps" value={data.length}/></div><DataTable rows={data} columns={[{header:"Step",cell:(r:any)=>r.stepNumber},{header:"Title",cell:(r:any)=>r.title},{header:"Reference",cell:(r:any)=>r.entityReference},{header:"Role",cell:(r:any)=>r.role},{header:"Route",cell:(r:any)=><a href={r.route}>{r.route}</a>},{header:"Talking points",cell:(r:any)=>r.talkingPoints},{header:"Outcome",cell:(r:any)=>r.expectedOutcome}]} /></>}
export function DemoScriptPage(){return <DemoControlCenterPage/>}
export function UatPage(){const {data,loading}=useApi<any[]>("/api/uat/suites",[]);if(loading)return <LoadingState/>;return <><PageHeader title="UAT support" description="UAT suites, test cases, runs and evidence capture for implementation acceptance."/><DataTable rows={data} columns={[{header:"Code",cell:r=>r.code},{header:"Suite",cell:r=>r.name},{header:"Module",cell:r=>r.module},{header:"Test cases",cell:r=>r.testCases?.length??0},{header:"Created",cell:r=>new Date(r.createdAt).toLocaleDateString()}]}/></>}
export function TrainingPage({moduleCode}:{moduleCode?:string}){const path=moduleCode?`/api/training/modules/${moduleCode}`:"/api/training/modules";const {data}=useApi<any>(path,moduleCode?null:[]);if(moduleCode&&data)return <><PageHeader title={data.name} description={data.description}/><DataTable rows={data.lessons??[]} columns={[{header:"Lesson",cell:(r:any)=>r.title},{header:"Content",cell:(r:any)=>r.content},{header:"Route",cell:(r:any)=><a href={r.route}>{r.route}</a>}]} /></>;return <><PageHeader title="Training library" description="Role-based training and knowledge transfer content."/><DataTable rows={data} columns={[{header:"Code",cell:(r:any)=>r.code},{header:"Module",cell:(r:any)=>r.name},{header:"Audience",cell:(r:any)=>r.audience},{header:"Area",cell:(r:any)=>r.moduleArea},{header:"Minutes",cell:(r:any)=>r.estimatedMinutes},{header:"Open",cell:(r:any)=><a href={`/app/training/${r.code}`}>Open</a>}]} /></>}
export function ImplementationPage(){const {data}=useApi<any[]>("/api/implementation/phases",[]);return <><PageHeader title="Implementation milestone tracker" description="Methodology, timelines, milestones and task progress."/><DataTable rows={data} columns={[{header:"Phase",cell:r=>r.name},{header:"Status",cell:r=>status(r.status)},{header:"Start",cell:r=>new Date(r.startDate).toLocaleDateString()},{header:"End",cell:r=>new Date(r.endDate).toLocaleDateString()},{header:"Milestones",cell:r=>r.milestones?.length??0}]} /></>}
export function SupportMaintenancePage(){const {data}=useApi<any[]>("/api/support-maintenance/service-levels",[]);return <><PageHeader title="Support and maintenance evidence" description="Support model, channels, service levels, escalation, release management and operations links."/><Panel title="Support model"><p>Multi-channel support through service desk, email and operations dashboard with severity-based escalation, maintenance windows, release notes, backups and restore references.</p></Panel><DataTable rows={data} columns={[{header:"Severity",cell:r=>r.severity},{header:"Response hours",cell:r=>r.responseTimeHours},{header:"Resolution target hours",cell:r=>r.resolutionTargetHours},{header:"Escalation role",cell:r=>r.escalationRole},{header:"Active",cell:r=>String(r.isActive)}]} /></>}
export function HandoverPage(){const {data}=useApi<any[]>("/api/handover/checklists",[]);const rows=data.flatMap(x=>(x.items??[]).map((i:any)=>({...i,checklist:x.name})));return <><PageHeader title="Implementation handover" description="Phase 1 handover checklist for configuration, security, data, training, UAT and support."/><DataTable rows={rows} columns={[{header:"Checklist",cell:r=>r.checklist},{header:"Category",cell:r=>r.category},{header:"Required",cell:r=>String(r.required)},{header:"Status",cell:r=>status(r.status)},{header:"Evidence",cell:r=><a href={r.evidenceRoute}>{r.evidenceRoute}</a>},{header:"Notes",cell:r=>r.evidenceNotes}]} /></>}
export function ReadinessPage(){const {data}=useApi<any[]>("/api/readiness",[]);return <><PageHeader title="Readiness assessment" description="Functional, security, data, integration, reporting, operational, training, UAT and support readiness scoring."/><DataTable rows={data} columns={[{header:"Category",cell:r=>r.category},{header:"Score",cell:r=>`${r.scorePercentage}%`},{header:"Status",cell:r=>status(r.status)},{header:"Issues",cell:r=>r.criticalIssues?.join("; ")},{header:"Recommendations",cell:r=>r.recommendations?.join("; ")},{header:"Evidence",cell:r=>r.evidenceLinks?.map((l:string)=><a className="me-2" href={l} key={l}>{l}</a>)}]} /></>}
