import { useEffect, useState } from "react";
import { PageHeader } from "../../components/ui/PageHeader";
import { MetricCard } from "../../components/ui/MetricCard";
import { DataTable } from "../../components/ui/DataTable";
import { Panel } from "../../components/ui/Panel";
import { EmptyState } from "../../components/ui/EmptyState";
import { LoadingState } from "../../components/ui/LoadingState";
import { apiGet, apiPost } from "../../services/apiClient";

type Requirement = { id:string; requirementCode:string; source:string; requirementArea:string; requirementText:string; requirementType:string; priority:string; status:string; systemModule:string; route:string; apiEndpoint:string; evidenceNotes:string; owner:string; lastVerifiedAt?:string };
type Coverage = { total:number; covered:number; partiallyCovered:number; needsConfiguration:number; notCovered:number; coveragePercentage:number; lastVerifiedDate?:string; areas:{area:string;total:number;covered:number;coveragePercentage:number;needsConfiguration:number;notCovered:number}[] };
type Commitment = { commitmentCode:string; section:string; commitmentText:string; systemFeature:string; module:string; route:string; apiEndpoint:string; status:string; evidenceNotes:string };
const badge = (s:string) => <span className={`badge ${s.includes("Not")?"text-bg-danger":s.includes("Needs")?"text-bg-warning":s.includes("Partially")?"text-bg-info":"text-bg-success"}`}>{s.replace(/([A-Z])/g," $1").trim()}</span>;
function useApi<T>(path:string, fallback:T){ const [data,setData]=useState<T>(fallback); const [loading,setLoading]=useState(true); useEffect(()=>{void apiGet<T>(path,fallback).then(r=>{setData(r.data); setLoading(false);});},[path]); return {data,loading};}
export function RfpEvidenceDashboardPage(){ const {data,loading}=useApi<Coverage>("/api/rfp-evidence/coverage",{total:0,covered:0,partiallyCovered:0,needsConfiguration:0,notCovered:0,coveragePercentage:0,areas:[]}); if(loading)return <LoadingState/>; return <><PageHeader title="RFP Evidence Center" description="Executive-ready compliance, proposal commitment, architecture, UAT, training and handover evidence for ProcuraFlow."/><div className="grid cols-4 dashboard-section"><MetricCard label="Total requirements" value={data.total}/><MetricCard label="Covered" value={data.covered}/><MetricCard label="Needs configuration" value={data.needsConfiguration}/><MetricCard label="Coverage" value={`${data.coveragePercentage}%`}/></div><Panel title="Critical gaps"><p>{data.notCovered} not covered requirements and {data.needsConfiguration} configuration items remain. Last verified: {data.lastVerifiedDate?new Date(data.lastVerifiedDate).toLocaleString():"Not yet verified"}</p></Panel><CoveragePage embedded/></> }
export function ComplianceMatrixPage(){ const {data,loading}=useApi<Requirement[]>("/api/rfp-evidence/requirements",[]); if(loading)return <LoadingState/>; return <><PageHeader title="Compliance matrix" description="Detailed RFP functional and technical requirement mapping with evidence routes and APIs."/><DataTable rows={data} striped columns={[{header:"Code",cell:r=>r.requirementCode,sortable:true},{header:"Area",cell:r=>r.requirementArea,sortable:true},{header:"Requirement",cell:r=>r.requirementText},{header:"Module",cell:r=>r.systemModule},{header:"Route",cell:r=><a href={r.route}>{r.route}</a>},{header:"API",cell:r=>r.apiEndpoint},{header:"Status",cell:r=>badge(r.status)},{header:"Evidence",cell:r=>r.evidenceNotes},{header:"Last verified",cell:r=>r.lastVerifiedAt?new Date(r.lastVerifiedAt).toLocaleDateString():"—"}]}/></> }
export function ProposalCommitmentsPage(){ const {data,loading}=useApi<Commitment[]>("/api/rfp-evidence/proposal-commitments",[]); if(loading)return <LoadingState/>; return <><PageHeader title="Proposal commitments" description="Evidence mapping from technical proposal promises to ProcuraFlow features."/><DataTable rows={data} striped columns={[{header:"Code",cell:r=>r.commitmentCode},{header:"Commitment",cell:r=>r.commitmentText},{header:"Feature",cell:r=>r.systemFeature},{header:"Module",cell:r=>r.module},{header:"Route",cell:r=><a href={r.route}>{r.route}</a>},{header:"Status",cell:r=>badge(r.status)},{header:"Evidence",cell:r=>r.evidenceNotes}]}/></> }
export function CoveragePage({embedded=false}:{embedded?:boolean}){ const {data}=useApi<Coverage>("/api/rfp-evidence/coverage",{total:0,covered:0,partiallyCovered:0,needsConfiguration:0,notCovered:0,coveragePercentage:0,areas:[]}); return <>{!embedded&&<PageHeader title="Coverage by area" description="Requirement coverage across supplier management, tendering, security, reporting, integration, training and support."/>}<DataTable rows={data.areas} compact columns={[{header:"Area",cell:r=>r.area},{header:"Total",cell:r=>r.total},{header:"Covered",cell:r=>r.covered},{header:"Needs configuration",cell:r=>r.needsConfiguration},{header:"Not covered",cell:r=>r.notCovered},{header:"Coverage",cell:r=>`${r.coveragePercentage}%`}]} /></> }
export function EvidenceExportsPage(){ const [done,setDone]=useState(false); return <><PageHeader title="Export evidence pack" description="Export JSON evidence covering compliance, commitments, readiness, demo, UAT, training, implementation, handover and support."/><Panel title="Evidence pack"><button className="btn btn-primary" onClick={()=>void apiPost("/api/rfp-evidence/export-pack",{}).then(()=>setDone(true))}>Export JSON pack</button>{done&&<p className="text-success mt-3">Evidence pack export requested successfully.</p>}</Panel></> }
export function ArchitectureEvidencePage(){ return <><PageHeader title="Architecture evidence" description="System architecture view for RFP response and handover."/><Panel title="ProcuraFlow modular monolith architecture"><div className="grid cols-3">{["Public Portal","Supplier Portal","Internal Portal","ProcuraFlow Studio","API Layer","Application Services","Domain","SQL Server","Document Storage","Integration Layer","Notification Services","Reporting Layer","Audit Layer","Security Layer"].map(x=><div className="callout callout-info" key={x}>{x}</div>)}</div></Panel></> }
export function IntegrationEvidencePage(){ const rows=["Contract Management","Document Management","Email","SMS","Enterprise Identity","Finance","Future Systems"].map(name=>({name,status:name==="Future Systems"?"NeedsConfiguration":"Covered",auth:name==="Enterprise Identity"?"OIDC/SAML ready":"API key/OAuth ready",route:"/app/integrations"})); return <><PageHeader title="Integration evidence" description="Integration approach, technology readiness and test evidence."/><DataTable rows={rows} columns={[{header:"Integration",cell:r=>r.name},{header:"Status",cell:r=>badge(r.status)},{header:"Auth type",cell:r=>r.auth},{header:"Endpoint configured",cell:()=>"Configuration-driven"},{header:"Last test",cell:()=>"See integration logs"},{header:"Related route",cell:r=><a href={r.route}>{r.route}</a>}]} /></> }
export function NotFoundEvidence(){return <EmptyState title="Evidence page not found" message="Select a route from the RFP Evidence Center."/>}
